import {test,expect} from "@playwright/test";
import {execFileSync} from "node:child_process";
import {randomUUID} from "node:crypto";
import pg from "pg";
import {owner,dispatch} from "../clipper-helpers";
import {fixtureClips,publishJob,posters} from "../content-helpers";
function invoke(...args:string[]){return JSON.parse(execFileSync(process.execPath,['--import','tsx','tests/invoke-billing.ts',...args],{env:{...process.env,DATABASE_URL:process.env.TEST_DATABASE_URL,OBJECT_STORAGE_BUCKET:process.env.TEST_OBJECT_STORAGE_BUCKET,APP_ENV:'local',ENABLE_TEST_BILLING:'1',ENABLE_FAKE_PAYMENT_PROVIDER:'1',PAYMENT_PROVIDER:'fake'},encoding:'utf8',windowsHide:true}));}
async function connect(){const db=new pg.Client({connectionString:process.env.TEST_DATABASE_URL});await db.connect();return db;}
test('ambiguous payment creation is held and never recreated; authoritative recovery and late paid event',async()=>{const a=await owner(`p7-unknown-${Date.now()}@example.test`,false),db=await connect();const guard=`p7_create_${Date.now()}`;let installed=false;try{const root=`/api/workspaces/${a.workspaceId}/billing`,pack=(await (await a.c.get(`${root}/packages`)).json()).packages[0],input={packageVersionId:pack.id,idempotencyKey:randomUUID()};await db.query(`CREATE FUNCTION ${guard}() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN RAISE EXCEPTION 'controlled ambiguous create'; END $$`);await db.query(`CREATE TRIGGER ${guard} BEFORE INSERT ON fake_payment_states FOR EACH ROW EXECUTE FUNCTION ${guard}()`);installed=true;
 const first=(await (await a.c.post(`${root}/payments`,{data:input})).json()).payment;expect(first).toMatchObject({status:'CREATING',needsSupport:true});await db.query(`DROP TRIGGER ${guard} ON fake_payment_states`);await db.query(`DROP FUNCTION ${guard}()`);installed=false;const before=(await db.query('SELECT creation_attempted_at FROM payments WHERE id=$1',[first.id])).rows[0];const replay=(await (await a.c.post(`${root}/payments`,{data:input})).json()).payment;expect(replay.id).toBe(first.id);expect(replay.needsSupport).toBe(true);expect((await db.query('SELECT count(*) FROM fake_payment_states WHERE external_id=$1',[`fake_${first.id}`])).rows[0].count).toBe('0');expect((await db.query('SELECT creation_attempted_at FROM payments WHERE id=$1',[first.id])).rows[0]).toEqual(before);
 await db.query("INSERT INTO fake_payment_states(external_id,reference_id,fiat_minor,currency,status) SELECT 'fake_'||id,reference_id,fiat_minor,currency,'PAID' FROM payments WHERE id=$1",[first.id]);for(let batch=0;batch<20&&(await db.query('SELECT status FROM payments WHERE id=$1',[first.id])).rows[0].status!=='PAID';batch++)invoke('payments');expect((await db.query('SELECT status FROM payments WHERE id=$1',[first.id])).rows[0].status).toBe('PAID');expect((await db.query("SELECT count(*) FROM token_ledger_entries WHERE payment_id=$1 AND entry_type='PURCHASE'",[first.id])).rows[0].count).toBe('1');
 const late=(await (await a.c.post(`${root}/payments`,{data:{...input,idempotencyKey:randomUUID()}})).json()).payment;await a.c.post(`${root}/payments/${late.id}/simulate`,{data:{status:'FAILED'}});await a.c.post(`${root}/payments/${late.id}/simulate`,{data:{status:'EXPIRED'}});await a.c.post(`${root}/payments/${late.id}/simulate`,{data:{status:'PAID'}});await a.c.post(`${root}/payments/${late.id}/simulate`,{data:{status:'PAID'}});expect((await db.query("SELECT count(*) FROM token_ledger_entries WHERE payment_id=$1",[late.id])).rows[0].count).toBe('1');expect((await (await a.c.get(root)).json()).wallet.availableTokens).toBe('20000');
 }finally{if(installed){await db.query(`DROP TRIGGER ${guard} ON fake_payment_states`);await db.query(`DROP FUNCTION ${guard}()`);}await a.c.dispose();await db.end();}});
test('ledger cursors preserve tied timestamps; reconciliation reports drift without rewriting projection',async()=>{const a=await owner(`p7-history-${Date.now()}@example.test`,false),db=await connect();let drift=false;try{const operator=(await db.query('SELECT created_by FROM workspaces WHERE id=$1',[a.workspaceId])).rows[0].created_by;await db.query("INSERT INTO token_ledger_entries(workspace_id,entry_type,available_delta,reserved_delta,idempotency_key,operator_id,reason) SELECT $1,'PROMOTIONAL_GRANT',1,0,'pagination:'||n,$2,'Explicit pagination test fixture' FROM generate_series(1,52) n",[a.workspaceId,operator]);const path=`/api/workspaces/${a.workspaceId}/billing/ledger`,first=await (await a.c.get(path)).json(),second=await (await a.c.get(`${path}?cursor=${encodeURIComponent(first.nextCursor)}`)).json();expect(first.entries).toHaveLength(50);expect(second.entries).toHaveLength(2);expect(second.nextCursor).toBe(null);expect(new Set([...first.entries,...second.entries].map(e=>e.id)).size).toBe(52);
 const pack=(await db.query("SELECT v.id,v.token_amount,v.fiat_minor,v.currency FROM token_package_versions v JOIN token_packages p ON p.active_version_id=v.id WHERE p.realm='TEST' LIMIT 1")).rows[0];await db.query("INSERT INTO payments(workspace_id,created_by,package_version_id,token_amount,fiat_minor,currency,provider,provider_mode,reference_id,request_key,request_hash,creation_attempted_at,creation_unknown) SELECT $1,$2,$3,$4,$5,$6,'fake','TEST','topup_'||gen_random_uuid(),'history-payment-'||n,repeat('a',64),now(),true FROM generate_series(1,52) n",[a.workspaceId,operator,pack.id,pack.token_amount,pack.fiat_minor,pack.currency]);const payRoot=`/api/workspaces/${a.workspaceId}/billing/payments`,p1=await (await a.c.get(payRoot)).json(),p2=await (await a.c.get(`${payRoot}?cursor=${encodeURIComponent(p1.nextCursor)}`)).json();expect(p1.payments).toHaveLength(50);expect(p2.payments).toHaveLength(2);expect(new Set([...p1.payments,...p2.payments].map(p=>p.id)).size).toBe(52);
 await db.query('BEGIN');await db.query('ALTER TABLE workspace_wallets DISABLE TRIGGER wallet_projection_guard');await db.query('UPDATE workspace_wallets SET available_tokens=53 WHERE workspace_id=$1',[a.workspaceId]);await db.query('ALTER TABLE workspace_wallets ENABLE TRIGGER wallet_projection_guard');await db.query('COMMIT');drift=true;const report=invoke('report','repair');expect(report.WALLET_LEDGER_MISMATCH.some((r:{workspace_id:string})=>r.workspace_id===a.workspaceId)).toBe(true);expect((await db.query('SELECT available_tokens FROM workspace_wallets WHERE workspace_id=$1',[a.workspaceId])).rows[0].available_tokens).toBe('53');
 }finally{if(drift){await db.query('BEGIN');await db.query('ALTER TABLE workspace_wallets DISABLE TRIGGER wallet_projection_guard');await db.query('UPDATE workspace_wallets SET available_tokens=52 WHERE workspace_id=$1',[a.workspaceId]);await db.query('ALTER TABLE workspace_wallets ENABLE TRIGGER wallet_projection_guard');await db.query('COMMIT');}await a.c.dispose();await db.end();}});
test('Clipper sealed multi-output job captures one quote; publication/poster/review/variant/download/archive are free',async()=>{test.setTimeout(120000);const a=await owner(`p7-clip-charge-${Date.now()}@example.test`),db=await connect();try{const fixture=await fixtureClips(a.c,a.workspaceId,db);dispatch();invoke('settle',a.workspaceId,fixture.jobId);const billing=(await db.query('SELECT status,token_amount FROM job_billing WHERE job_id=$1',[fixture.jobId])).rows[0];expect(billing).toMatchObject({status:'CAPTURED',token_amount:'700'});const before=(await db.query('SELECT available_tokens,reserved_tokens FROM workspace_wallets WHERE workspace_id=$1',[a.workspaceId])).rows[0],ids=publishJob(a.workspaceId,fixture.jobId,10)[0] as string[];expect(ids).toHaveLength(2);posters();const root=`/api/workspaces/${a.workspaceId}/content`;for(const id of ids){const detail=(await (await a.c.get(`${root}/${id}`)).json()).content;expect((await a.c.post(`${root}/${id}/review`,{data:{decision:'APPROVE',versionId:detail.version.id,expectedRevision:detail.reviewRevision,requestKey:randomUUID()}})).ok()).toBe(true);expect((await a.c.get(`${root}/${id}/versions/${detail.version.id}/media?kind=download`)).status()).toBe(200);}const variant=await a.c.post(`${root}/${ids[1]}/relations`,{data:{relationType:"VARIANT_OF",parentContentId:ids[0]}});expect(variant.status()).toBe(200);for(const id of ids)expect((await a.c.post(`${root}/${id}/archive`)).status()).toBe(200);expect((await db.query('SELECT available_tokens,reserved_tokens FROM workspace_wallets WHERE workspace_id=$1',[a.workspaceId])).rows[0]).toEqual(before);expect((await db.query('SELECT count(*) FROM token_ledger_entries WHERE job_id=$1',[fixture.jobId])).rows[0].count).toBe('2');
 }finally{await a.c.dispose();await db.end();}});
