import {test,expect,type APIRequestContext} from "@playwright/test";
import {execFileSync,execFile} from "node:child_process";
import {promisify} from "node:util";
import {createHmac,randomUUID} from "node:crypto";
import pg from "pg";
import {owner,dispatch,source,submit} from "../clipper-helpers";
import {fundFixture} from "../billing-helpers";
import {product,fields} from "../content-helpers";
const run=promisify(execFile),env=()=>({...process.env,DATABASE_URL:process.env.TEST_DATABASE_URL,OBJECT_STORAGE_BUCKET:process.env.TEST_OBJECT_STORAGE_BUCKET,APP_ENV:"local",ENABLE_TEST_BILLING:"1",VIDEO_PROVIDER:"fake",ENABLE_FAKE_VIDEO_PROVIDER:"1",PAYMENT_PROVIDER:"fake",ENABLE_FAKE_PAYMENT_PROVIDER:"1"});
const args=["--env-file=.env.local","--import","tsx","tests/invoke-billing.ts"];
function invoke(...input:string[]){return JSON.parse(execFileSync(process.execPath,[...args,...input],{env:env(),encoding:"utf8",windowsHide:true}));}
async function concurrentInvoke(count:number,...input:string[]){return Promise.all(Array.from({length:count},()=>run(process.execPath,[...args,...input],{env:env(),windowsHide:true})));}
const payload=(productId:string,key=randomUUID(),extra:Record<string,unknown>={})=>({productId,prompt:"Show the saved Product on a studio table with a gentle camera orbit.",tier:"QUALITY",durationSeconds:5,aspectRatio:"1:1",quantity:1,idempotencyKey:key,...extra});
async function quote(c:APIRequestContext,ws:string,data:Record<string,unknown>,operation="AI_VIDEO"){const r=await c.post(`/api/workspaces/${ws}/billing/quotes`,{data:{...data,operation}});expect(r.status(),await r.text()).toBe(200);return (await r.json()).quote;}
async function post(c:APIRequestContext,ws:string,data:Record<string,unknown>,q:Record<string,unknown>){return c.post(`/api/workspaces/${ws}/ai-videos`,{data:{...data,quoteId:q.id,quoteHash:q.quoteHash}});}
async function wallet(c:APIRequestContext,ws:string){return (await (await c.get(`/api/workspaces/${ws}/billing`)).json()).wallet;}
async function connect(){const db=new pg.Client({connectionString:process.env.TEST_DATABASE_URL});await db.connect();return db;}
async function finish(db:pg.Client,id:string){for(let n=0;n<40;n++){await db.query("UPDATE provider_executions SET next_action_at=now() WHERE job_id=$1",[id]);await db.query("UPDATE job_outbox SET available_at=now() WHERE job_id=$1",[id]);await db.query("UPDATE jobs SET available_at=now() WHERE id=$1",[id]);dispatch();const j=(await db.query("SELECT status FROM jobs WHERE id=$1",[id])).rows[0];if(["SUCCEEDED","FAILED","CANCELLED"].includes(j.status))return j.status;await new Promise(r=>setTimeout(r,150));}throw new Error("Fixture did not complete");}
function signed(event:Record<string,unknown>){const raw=JSON.stringify(event);return {data:raw,headers:{"content-type":"application/json","x-fake-signature":createHmac("sha256",process.env.FAKE_PAYMENT_WEBHOOK_SECRET!).update(raw).digest("hex")}};}
test("zero wallets, verified purchases, concurrent callbacks, rollback and provider reconciliation",async()=>{test.setTimeout(180000);const a=await owner(`p7-pay-${Date.now()}@example.test`,false),db=await connect();try{
 expect(await wallet(a.c,a.workspaceId)).toMatchObject({availableTokens:"0",reservedTokens:"0"});const catalog=(await (await a.c.get(`/api/workspaces/${a.workspaceId}/billing/packages`)).json()).packages,root=`/api/workspaces/${a.workspaceId}/billing/payments`;
 const requests=await Promise.all(Array.from({length:10},()=>a.c.post(root,{data:{packageVersionId:catalog[0].id,idempotencyKey:"payment-ten-replays"}})));for(const r of requests)expect(r.status(),await r.text()).toBe(201);const ids=await Promise.all(requests.map(async r=>(await r.json()).payment.id));expect(new Set(ids).size).toBe(1);
 const p=(await db.query("SELECT * FROM payments WHERE id=$1",[ids[0]])).rows[0];expect(p.status).toBe("PENDING");expect(await wallet(a.c,a.workspaceId)).toMatchObject({availableTokens:"0"});const event={eventKey:`${p.external_id}:PAID`,referenceId:p.reference_id,externalId:p.external_id,status:"PAID",fiatMinor:p.fiat_minor,currency:p.currency};
 expect((await a.c.post('/api/payments/webhooks/fake',{data:event})).status()).toBe(401);
 for(const [change,expected] of [[{eventKey:`${p.external_id}:wrong-amount`,fiatMinor:"10001"},"PAYMENT_IDENTITY_MISMATCH"],[{eventKey:`${p.external_id}:wrong-currency`,currency:"USD"},"PAYMENT_IDENTITY_MISMATCH"],[{eventKey:`${p.external_id}:unknown-payment`,referenceId:`topup_${randomUUID()}`},"UNKNOWN_PAYMENT"]] as const){const r=await a.c.post('/api/payments/webhooks/fake',signed({...event,...change}));expect(r.status(),await r.text()).toBe(200);expect((await r.json()).disposition).toBe(expected);}
 expect((await wallet(a.c,a.workspaceId)).availableTokens).toBe("0");
 const callbacks=await Promise.all(Array.from({length:10},()=>a.c.post('/api/payments/webhooks/fake',signed(event))));for(const r of callbacks)expect(r.status(),await r.text()).toBe(200);expect((await wallet(a.c,a.workspaceId)).availableTokens).toBe("10000");expect((await db.query("SELECT count(*) FROM token_ledger_entries WHERE payment_id=$1",[p.id])).rows[0].count).toBe("1");
 const second=(await (await a.c.post(root,{data:{packageVersionId:catalog[0].id,idempotencyKey:"lost-webhook-payment"}})).json()).payment;await a.c.post(`${root}/${second.id}/simulate`,{data:{status:"PAID",deliverWebhook:false}});expect((await wallet(a.c,a.workspaceId)).availableTokens).toBe("10000");invoke("payments");invoke("payments");expect((await wallet(a.c,a.workspaceId)).availableTokens).toBe("20000");
 const third=(await (await a.c.post(root,{data:{packageVersionId:catalog[0].id,idempotencyKey:"rollback-paid-payment"}})).json()).payment;
 const guard=`p7_credit_${Date.now()}`;await db.query(`CREATE FUNCTION ${guard}() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN IF NEW.payment_id='${third.id}'::uuid THEN RAISE EXCEPTION 'controlled credit rollback'; END IF; RETURN NEW; END $$`);await db.query(`CREATE TRIGGER ${guard} BEFORE INSERT ON token_ledger_entries FOR EACH ROW EXECUTE FUNCTION ${guard}()`);
 try{const fail=await a.c.post(`${root}/${third.id}/simulate`,{data:{status:"PAID"}});expect(fail.status()).toBe(500);expect((await db.query("SELECT status,purchase_ledger_id FROM payments WHERE id=$1",[third.id])).rows[0]).toMatchObject({status:"PENDING",purchase_ledger_id:null});expect((await wallet(a.c,a.workspaceId)).availableTokens).toBe("20000");}finally{await db.query(`DROP TRIGGER ${guard} ON token_ledger_entries`);await db.query(`DROP FUNCTION ${guard}()`);}
 // Batches are bounded; earlier test runs may leave more than 100 unrelated pending payments.
 for(let n=0;n<20&&(await db.query("SELECT status FROM payments WHERE id=$1",[third.id])).rows[0].status!=="PAID";n++)invoke("payments");expect((await wallet(a.c,a.workspaceId)).availableTokens).toBe("30000");
 await a.c.post(`${root}/${third.id}/simulate`,{data:{status:"REFUNDED"}});expect((await wallet(a.c,a.workspaceId)).availableTokens).toBe("30000");expect((await db.query("SELECT code FROM billing_reconciliation_issues WHERE payment_id=$1",[third.id])).rows.some(r=>r.code==="FIAT_REFUND_REQUIRES_SUPPORT")).toBe(true);
 for(const sql of ["UPDATE token_ledger_entries SET available_delta=1 WHERE payment_id=$1","DELETE FROM token_ledger_entries WHERE payment_id=$1"])await expect(db.query(sql,[p.id])).rejects.toThrow();await expect(db.query("UPDATE workspace_wallets SET available_tokens=1 WHERE workspace_id=$1",[a.workspaceId])).rejects.toThrow();
 const ledger=await (await a.c.get(`/api/workspaces/${a.workspaceId}/billing/ledger`)).json();expect(ledger.entries.filter((e:{entry_type:string})=>e.entry_type==="PURCHASE")).toHaveLength(3);
 }finally{await a.c.dispose();await db.end();}});

test("quotes bind inputs and versions; two-device spending, ten replays, transactional rollback",async()=>{test.setTimeout(180000);const a=await owner(`p7-race-${Date.now()}@example.test`,false),db=await connect();let active:string|undefined,catalogId:string|undefined;try{
 const p=await product(a.c,a.workspaceId),data=payload(p.id),q=await quote(a.c,a.workspaceId,data);expect(q.tokenAmount).toBe("700");expect(q.affordable).toBe(false);expect((await post(a.c,a.workspaceId,data,q)).status()).toBe(402);expect((await db.query("SELECT count(*) FROM jobs WHERE workspace_id=$1",[a.workspaceId])).rows[0].count).toBe("0");
 fundFixture(a.workspaceId,"1000");const otherData=payload(p.id),otherQuote=await quote(a.c,a.workspaceId,otherData);const two=await Promise.all([post(a.c,a.workspaceId,data,q),post(a.c,a.workspaceId,otherData,otherQuote)]);expect(two.map(r=>r.status()).sort()).toEqual([201,402]);const winner=two.findIndex(r=>r.status()===201),winningData=winner===0?data:otherData,winningQuote=winner===0?q:otherQuote;const success=two[winner];const jobId=(await success.json()).job.id;expect(await wallet(a.c,a.workspaceId)).toMatchObject({availableTokens:"300",reservedTokens:"700"});
 const replays=await Promise.all(Array.from({length:10},()=>post(a.c,a.workspaceId,winningData,winningQuote)));for(const r of replays)expect(r.status()).toBe(200);expect((await db.query("SELECT count(*) FROM token_ledger_entries WHERE job_id=$1 AND entry_type='RESERVE'",[jobId])).rows[0].count).toBe("1");expect((await post(a.c,a.workspaceId,{...winningData,prompt:"A different valid prompt that changes the normalized request."},winningQuote)).status()).toBe(409);
 await a.c.post(`/api/workspaces/${a.workspaceId}/jobs/${jobId}/cancel`);await concurrentInvoke(10,"settle",a.workspaceId,jobId);expect(await wallet(a.c,a.workspaceId)).toMatchObject({availableTokens:"1000",reservedTokens:"0"});
 const freshTenData=payload(p.id),freshTenQuote=await quote(a.c,a.workspaceId,freshTenData);const ten=await Promise.all(Array.from({length:10},()=>post(a.c,a.workspaceId,freshTenData,freshTenQuote)));expect(ten.map(r=>r.status()).sort()).toEqual([...Array(9).fill(200),201]);const tenIds=await Promise.all(ten.map(async r=>(await r.json()).job.id));expect(new Set(tenIds).size).toBe(1);const tenId=tenIds[0];expect((await db.query("SELECT (SELECT count(*) FROM jobs WHERE workspace_id=$1 AND idempotency_key=$2) AS jobs,(SELECT count(*) FROM job_billing WHERE job_id=$3) AS billings,(SELECT count(*) FROM token_ledger_entries WHERE job_id=$3 AND entry_type='RESERVE') AS reserves",[a.workspaceId,freshTenData.idempotencyKey,tenId])).rows[0]).toEqual({jobs:"1",billings:"1",reserves:"1"});await a.c.post(`/api/workspaces/${a.workspaceId}/jobs/${tenId}/cancel`);await concurrentInvoke(10,"settle",a.workspaceId,tenId);expect((await wallet(a.c,a.workspaceId)).availableTokens).toBe("1000");
 const original=(await db.query("SELECT id,active_version_id FROM price_catalogs WHERE operation='AI_VIDEO' AND realm='TEST'")).rows[0];active=original.active_version_id;catalogId=original.id;
 const oldData=payload(p.id),oldQ=await quote(a.c,a.workspaceId,oldData);const v=(await db.query("INSERT INTO price_versions(catalog_id,version_number,label,rules) VALUES($1,$2,'TEST version change', $3::jsonb) RETURNING id",[catalogId,Math.floor(Date.now()/1000),JSON.stringify({tier:"QUALITY",base:"0",perSecond:"160"})])).rows[0];await db.query("UPDATE price_catalogs SET active_version_id=$1 WHERE id=$2",[v.id,catalogId]);expect((await quote(a.c,a.workspaceId,payload(p.id))).tokenAmount).toBe("800");const valid=await post(a.c,a.workspaceId,oldData,oldQ);expect(valid.status(),await valid.text()).toBe(201);const oldId=(await valid.json()).job.id;expect((await db.query("SELECT token_amount,price_version_id FROM job_billing WHERE job_id=$1",[oldId])).rows[0]).toMatchObject({token_amount:"700",price_version_id:active});await a.c.post(`/api/workspaces/${a.workspaceId}/jobs/${oldId}/cancel`);invoke("settle",a.workspaceId,oldId);
 await expect(db.query("UPDATE price_versions SET rules='{}' WHERE id=$1",[v.id])).rejects.toThrow();await db.query("UPDATE price_catalogs SET active_version_id=$1 WHERE id=$2",[active,catalogId]);
 const expiredId=randomUUID();await db.query("INSERT INTO billing_quotes(id,workspace_id,created_by,operation,price_version_id,request_hash,input_hash,input_snapshot,token_amount,quote_hash,expires_at) SELECT $1,workspace_id,created_by,operation,price_version_id,request_hash,input_hash,input_snapshot,token_amount,quote_hash,now()-interval '1 second' FROM billing_quotes WHERE id=$2",[expiredId,oldQ.id]);expect((await post(a.c,a.workspaceId,{...oldData,idempotencyKey:randomUUID()},{...oldQ,id:expiredId})).status()).toBe(409);
 const freshData=payload(p.id),fresh=await quote(a.c,a.workspaceId,freshData);await a.c.patch(`/api/workspaces/${a.workspaceId}/products/${p.id}`,{data:{...fields,description:"Changed product context"}});expect((await post(a.c,a.workspaceId,freshData,fresh)).status()).toBe(409);
 const rollbackData=payload(p.id),rollback=await quote(a.c,a.workspaceId,rollbackData),guard=`p7_reserve_${Date.now()}`;await db.query(`CREATE FUNCTION ${guard}() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN IF NEW.workspace_id='${a.workspaceId}'::uuid AND NEW.entry_type='RESERVE' THEN RAISE EXCEPTION 'controlled reservation rollback'; END IF; RETURN NEW; END $$`);await db.query(`CREATE TRIGGER ${guard} BEFORE INSERT ON token_ledger_entries FOR EACH ROW EXECUTE FUNCTION ${guard}()`);try{expect((await post(a.c,a.workspaceId,rollbackData,rollback)).status()).toBe(500);expect((await db.query("SELECT count(*) FROM jobs WHERE workspace_id=$1 AND idempotency_key=$2",[a.workspaceId,rollbackData.idempotencyKey])).rows[0].count).toBe("0");expect((await wallet(a.c,a.workspaceId)).availableTokens).toBe("1000");}finally{await db.query(`DROP TRIGGER ${guard} ON token_ledger_entries`);await db.query(`DROP FUNCTION ${guard}()`);}
 }finally{if(active&&catalogId)await db.query("UPDATE price_catalogs SET active_version_id=$1 WHERE id=$2",[active,catalogId]);await a.c.dispose();await db.end();}});

test("paid fake success/failure/retries/unknown outcomes settle once; token refunds and late success quarantine",async()=>{test.setTimeout(240000);const a=await owner(`p7-settle-${Date.now()}@example.test`),db=await connect();try{const p=await product(a.c,a.workspaceId),operator=(await db.query("SELECT created_by FROM workspaces WHERE id=$1",[a.workspaceId])).rows[0].created_by;
 for(const scenario of ["SUCCESS","FAILURE","RATE_LIMIT","SUBMISSION_UNKNOWN","DOWNLOAD_FAIL_ONCE"]){const data=payload(p.id,randomUUID(),{testScenario:scenario}),q=await quote(a.c,a.workspaceId,data);const r=await post(a.c,a.workspaceId,data,q);expect(r.status(),await r.text()).toBe(201);const id=(await r.json()).job.id;dispatch();if(scenario==="SUBMISSION_UNKNOWN"){expect((await db.query("SELECT status FROM jobs WHERE id=$1",[id])).rows[0].status).toBe("RECONCILING");expect((await db.query("SELECT status FROM job_billing WHERE job_id=$1",[id])).rows[0].status).toBe("RESERVED");}
 const terminal=await finish(db,id);expect(terminal).toBe(scenario==="FAILURE"?"FAILED":"SUCCEEDED");await concurrentInvoke(10,"settle",a.workspaceId,id);expect((await db.query("SELECT status FROM job_billing WHERE job_id=$1",[id])).rows[0].status).toBe(scenario==="FAILURE"?"RELEASED":"CAPTURED");expect((await db.query("SELECT count(*) FROM token_ledger_entries WHERE job_id=$1",[id])).rows[0].count).toBe("2");
 if(scenario==="RATE_LIMIT")expect((await db.query("SELECT count(*) FROM job_attempts WHERE job_id=$1",[id])).rows[0].count).toBe("2");
 if(scenario==="SUCCESS"){const before=await wallet(a.c,a.workspaceId);invoke("refund",a.workspaceId,operator,id,"support-refund-one","Controlled token refund");invoke("refund",a.workspaceId,operator,id,"support-refund-one","Controlled token refund");expect(BigInt((await wallet(a.c,a.workspaceId)).availableTokens)-BigInt(before.availableTokens)).toBe(BigInt(700));expect((await db.query("SELECT count(*) FROM token_ledger_entries WHERE job_id=$1 AND entry_type='REFUND'",[id])).rows[0].count).toBe("1");}
 if(scenario==="FAILURE"){await db.query("UPDATE jobs SET status='SUCCEEDED',result='{}'::jsonb WHERE id=$1",[id]);invoke("settle",a.workspaceId,id);expect((await db.query("SELECT count(*) FROM token_ledger_entries WHERE job_id=$1",[id])).rows[0].count).toBe("2");expect((await db.query("SELECT code FROM billing_reconciliation_issues WHERE job_id=$1",[id])).rows[0].code).toBe("LATE_SUCCESS_AFTER_RELEASE");}
 }
 expect((await wallet(a.c,a.workspaceId)).reservedTokens).toBe("0");const report=invoke("report");expect(report.WALLET_LEDGER_MISMATCH).toEqual([]);expect(report.RESERVED_JOB_MISMATCH).toEqual([]);expect(report.PAID_WITHOUT_PURCHASE).toEqual([]);
 const s=await source(a.c,a.workspaceId),r=await submit(a.c,a.workspaceId,s.id,randomUUID()),id=(await r.json()).job.id;expect(r.status()).toBe(201);await a.c.post(`/api/workspaces/${a.workspaceId}/jobs/${id}/cancel`);invoke("settle",a.workspaceId,id);expect((await db.query("SELECT status,token_amount FROM job_billing WHERE job_id=$1",[id])).rows[0]).toMatchObject({status:"RELEASED",token_amount:"700"});
 }finally{await a.c.dispose();await db.end();}});

test("workspace isolation and Viewer/Editor/Admin billing permissions",async()=>{const a=await owner(`p7-role-a-${Date.now()}@example.test`,false),b=await owner(`p7-role-b-${Date.now()}@example.test`,false),db=await connect();try{const p=await product(a.c,a.workspaceId),q=await quote(a.c,a.workspaceId,payload(p.id));for(const suffix of ["","/ledger","/payments","/packages","/usage"])expect((await b.c.get(`/api/workspaces/${a.workspaceId}/billing${suffix}`)).status()).toBe(404);expect((await post(b.c,b.workspaceId,payload(p.id),q)).status()).toBe(404);
 const user=(await (await b.c.get('/api/auth/session')).json()).user.id;await db.query("INSERT INTO workspace_members(workspace_id,user_id,role) VALUES($1,$2,'VIEWER')",[a.workspaceId,user]);await b.c.post(`/api/workspaces/${a.workspaceId}/select`);
 for(const role of ["VIEWER","EDITOR","ADMIN"]){await db.query("UPDATE workspace_members SET role=$1 WHERE workspace_id=$2 AND user_id=$3",[role,a.workspaceId,user]);expect((await b.c.get(`/api/workspaces/${a.workspaceId}/billing`)).status()).toBe(200);expect((await b.c.get(`/api/workspaces/${a.workspaceId}/billing/payments`)).status()).toBe(role==="ADMIN"?200:403);expect((await b.c.post(`/api/workspaces/${a.workspaceId}/billing/quotes`,{data:{...payload(p.id),operation:"AI_VIDEO"}})).status()).toBe(role==="VIEWER"?403:200);expect((await b.c.post(`/api/workspaces/${a.workspaceId}/billing/payments`,{data:{packageVersionId:randomUUID(),idempotencyKey:randomUUID()}})).status()).toBe(role==="ADMIN"?404:403);}
 }finally{await Promise.all([a.c.dispose(),b.c.dispose()]);await db.end();}});
