import {test,expect} from "@playwright/test";
import {writeFile,mkdir} from "node:fs/promises";
import {createHash} from "node:crypto";
import pg from "pg";
import {owner,dispatch} from "../clipper-helpers";
import {product,fields,imageReference,settle,blockPublication,publishJob,fixtureClips,posters,approved,videoJob} from "../content-helpers";

test("Content publication, frozen references, Chrome review, isolation, retention and variants",async({browser})=>{
  test.setTimeout(240000);const stamp=String(Date.now()),email=`p6-owner-${stamp}@example.test`,a=await owner(email),b=await owner(`p6-other-${stamp}@example.test`),db=new pg.Client({connectionString:process.env.TEST_DATABASE_URL});await db.connect();let unblock:(()=>Promise<void>)|undefined;
  const context=await browser.newContext({storageState:await a.c.storageState()}),page=await context.newPage();
  try{
    const p=await product(a.c,a.workspaceId);
    await page.goto("http://127.0.0.1:3200/ai-videos");await page.getByLabel("Saved Product").selectOption(p.id);await page.getByLabel("Video prompt").fill("Show the saved Product on a simple studio table with a slow camera orbit.");await page.getByLabel("Duration").selectOption("5");await page.getByLabel("Aspect ratio").selectOption("1:1");await page.getByRole("button",{name:"Generate video"}).click();await page.waitForURL(/\/ai-videos\/[0-9a-f-]+$/);const aiJobId=page.url().split("/").pop()!;
    unblock=await blockPublication(db,aiJobId,stamp);expect(await settle(db,aiJobId)).toBe("SUCCEEDED");
    expect((await db.query("SELECT status,attempts FROM content_publications WHERE job_id=$1",[aiJobId])).rows[0]).toMatchObject({status:"PENDING"});expect((await db.query("SELECT count(*) FROM content_items WHERE origin_job_id=$1",[aiJobId])).rows[0].count).toBe("0");
    expect((await a.c.patch(`/api/workspaces/${a.workspaceId}/products/${p.id}`,{data:{...fields,name:"Today's Product",description:"Second-version context"}})).status()).toBe(200);const updatedRef=await imageReference(a.c,a.workspaceId,p.id,p.reference.assetId,"#2244bb");
    await unblock();unblock=undefined;const repeated=publishJob(a.workspaceId,aiJobId,10) as string[][];expect(new Set(repeated.flat()).size).toBe(1);const aiId=repeated[0][0];
    expect((await db.query("SELECT count(*) FROM content_versions WHERE job_id=$1",[aiJobId])).rows[0].count).toBe("1");expect((await db.query("SELECT submit_count FROM provider_executions WHERE job_id=$1",[aiJobId])).rows[0].submit_count).toBe(1);
    const detail=(await (await a.c.get(`/api/workspaces/${a.workspaceId}/content/${aiId}`)).json()).content;
    expect(detail.status).toBe("PENDING_REVIEW");expect(detail.product.versionNumber).toBe(1);expect(detail.product.information.name).toBe(fields.name);expect(detail.references.map((r:{assetVersionId:string})=>r.assetVersionId)).toEqual([p.reference.versionId]);
    const apiPath=`/api/workspaces/${a.workspaceId}/content/${aiId}/versions/${detail.version.id}/media`;
    const oldReference=await a.c.get(`${apiPath}?kind=reference&assetVersionId=${p.reference.versionId}`);expect(oldReference.status()).toBe(200);expect(Buffer.from(await (await fetch((await oldReference.json()).url)).arrayBuffer())).toEqual(p.reference.png);expect((await a.c.get(`${apiPath}?kind=reference&assetVersionId=${updatedRef.versionId}`)).status()).toBe(404);
    await page.goto(`http://127.0.0.1:3200/content/${aiId}`);await expect(page.getByText("Saved first-version context",{exact:true})).toBeVisible();await expect(page.getByText("Second-version context",{exact:true})).toHaveCount(0);await expect(page.getByAltText("Saved FRONT reference")).toBeVisible();const preview=page.getByLabel("Content output");await expect(preview).toBeVisible();await expect.poll(()=>preview.evaluate(v=>(v as HTMLVideoElement).readyState)).toBeGreaterThanOrEqual(1);
    await page.getByRole("button",{name:"Approve content",exact:true}).click();await expect(page.getByTestId("content-status")).toHaveText("APPROVED");const [download]=await Promise.all([page.waitForEvent("download"),page.getByRole("link",{name:"Download MP4",exact:true}).click()]);await mkdir("data/phase6",{recursive:true});await download.saveAs("data/phase6/approved-ai-video.mp4");
    await expect.poll(()=>preview.evaluate(v=>(v as HTMLVideoElement).readyState)).toBeGreaterThanOrEqual(2);await page.screenshot({path:"data/phase6/ai-review.png",fullPage:true});
    const clips=await fixtureClips(a.c,a.workspaceId,db),clipRepeated=publishJob(a.workspaceId,clips.jobId,10) as string[][];expect(new Set(clipRepeated.flat()).size).toBe(2);const clipIds=clipRepeated[0];
    expect((await db.query("SELECT type,count(*) FROM content_items WHERE origin_job_id=$1 GROUP BY type",[clips.jobId])).rows).toEqual([{type:"CLIP",count:"2"}]);
    const clipDetails=[];for(const id of clipIds){const d=(await (await a.c.get(`/api/workspaces/${a.workspaceId}/content/${id}`)).json()).content;expect(d.source.id).toBe(clips.source.id);expect(d.source.sha256).toBe(clips.source.sha256);expect(d.version.transcriptArtifactId).toBe(clips.transcriptId);expect(d.version.planArtifactId).toBe(clips.planId);clipDetails.push(d);}
    expect(clipDetails.map(d=>d.clip.start).sort((a,b)=>a-b)).toEqual([0,15]);
    await page.goto(`http://127.0.0.1:3200/content/${clipIds[0]}`);await expect.poll(()=>page.getByLabel("Original source").evaluate(v=>(v as HTMLVideoElement).readyState)).toBeGreaterThanOrEqual(1);await page.getByRole("button",{name:"Approve content"}).click();await expect(page.getByTestId("content-status")).toHaveText("APPROVED");const [clipDownload]=await Promise.all([page.waitForEvent("download"),page.getByRole("link",{name:"Download MP4",exact:true}).click()]);await clipDownload.saveAs("data/phase6/approved-clip.mp4");
    await page.goto(`http://127.0.0.1:3200/content/${clipIds[1]}`);await page.getByLabel("Rejection category").selectOption("BAD_CLIP_SELECTION");await page.getByLabel("Rejection reason").fill("The thought ends before the useful conclusion.");await page.getByRole("button",{name:"Reject content"}).click();await expect(page.getByTestId("content-status")).toHaveText("REJECTED");await page.reload();await expect(page.getByText("BAD CLIP SELECTION · The thought ends before the useful conclusion.")).toBeVisible();await page.screenshot({path:"data/phase6/clip-rejected.png",fullPage:true});
    const contentPath=`/api/workspaces/${a.workspaceId}/content`,counts=await (await a.c.get(`${contentPath}/counts`)).json();expect(counts).toEqual({assets:3,pending:0,approved:2,rejected:1});expect(await (await b.c.get(`/api/workspaces/${b.workspaceId}/content/counts`)).json()).toEqual({assets:0,pending:0,approved:0,rejected:0});
    for(const q of ["type=CLIP","status=REJECTED","search=reviewable","productId="+p.id]){const rows=await (await a.c.get(`${contentPath}?${q}`)).json();expect(rows.items.length).toBe(q.includes("CLIP")||q.includes("reviewable")?2:1);}
    expect((await a.c.get(`${contentPath}?page=501`)).status()).toBe(400);expect((await a.c.get(`${contentPath}?page=2`)).status()).toBe(200);
    await page.goto(`http://127.0.0.1:3200/ai-videos/${aiJobId}`);await expect(page.getByRole("heading",{name:"Published to Content Library · 1 item"})).toBeVisible();await expect(page.locator(`a[href='/content/${aiId}']`)).toBeVisible();await page.goto(`http://127.0.0.1:3200/clipper/${clips.jobId}`);await expect(page.getByRole("heading",{name:"Published to Content Library · 2 items"})).toBeVisible();
    await page.goto("http://127.0.0.1:3200/");await expect(page.locator(".content-counts .stat-card").nth(0).locator("strong")).toHaveText("3");await expect(page.locator(".content-counts .stat-card").nth(1).locator("strong")).toHaveText("0");
    for(const id of [aiId,...clipIds]){
      const version=(await (await a.c.get(`${contentPath}/${id}`)).json()).content.version.id;
      for(const prefix of [contentPath,`/api/workspaces/${b.workspaceId}/content`]){
        expect((await b.c.get(`${prefix}/${id}`)).status()).toBe(404);
        for(const kind of ["preview","download","poster","source","reference"])expect((await b.c.get(`${prefix}/${id}/versions/${version}/media?kind=${kind}&assetVersionId=${p.reference.versionId}`)).status()).toBe(404);
        for(const action of ["review","archive","relations"])expect((await b.c.post(`${prefix}/${id}/${action}`,{data:{}})).status()).toBe(404);
      }
      expect((await a.c.get(`${contentPath}/${id}/versions/${detail.version.id===version?clipDetails[0].version.id:detail.version.id}/media`)).status()).toBe(404);
    }
    const viewerId=(await (await b.c.get("/api/auth/session")).json()).user.id;await db.query("INSERT INTO workspace_members(workspace_id,user_id,role) VALUES($1,$2,'VIEWER')",[a.workspaceId,viewerId]);await b.c.post(`/api/workspaces/${a.workspaceId}/select`);
    expect((await b.c.get(`${contentPath}/${aiId}`)).status()).toBe(200);expect((await b.c.get(`${apiPath}?kind=download`)).status()).toBe(200);for(const action of ["review","archive","relations"])expect((await b.c.post(`${contentPath}/${aiId}/${action}`,{data:{}})).status()).toBe(403);
    expect((await b.c.get(`${contentPath}/${clipIds[1]}/versions/${clipDetails[1].version.id}/media?kind=download`)).status()).toBe(200);expect((await b.c.post(`${contentPath}/${aiId}/versions/${detail.version.id}/poster/retry`)).status()).toBe(403);
    const viewer=await browser.newContext({storageState:await b.c.storageState()});try{const view=await viewer.newPage();await view.goto(`http://127.0.0.1:3200/content/${aiId}`);await expect(view.getByRole("button",{name:"Approve content"})).toHaveCount(0);await expect(view.getByRole("link",{name:"Download MP4"})).toBeVisible();}finally{await viewer.close();}
    const rejected=(await (await a.c.get(`${contentPath}/${clipIds[1]}`)).json()).content,review={versionId:rejected.version.id,decision:"APPROVE",expectedRevision:rejected.reviewRevision,requestKey:`p6-review-${stamp}`};const approvals=await Promise.all([a.c.post(`${contentPath}/${clipIds[1]}/review`,{data:review}),a.c.post(`${contentPath}/${clipIds[1]}/review`,{data:review})]);expect(approvals.map(r=>r.status())).toEqual([200,200]);const approved=(await (await a.c.get(`${contentPath}/${clipIds[1]}`)).json()).content;expect(approved.reviews).toHaveLength(2);
    const conflict=await Promise.all([a.c.post(`${contentPath}/${clipIds[1]}/review`,{data:{...review,expectedRevision:approved.reviewRevision,requestKey:`p6-a-${stamp}`}}),a.c.post(`${contentPath}/${clipIds[1]}/review`,{data:{...review,decision:"REJECT",reasonCategory:"OTHER",expectedRevision:approved.reviewRevision,requestKey:`p6-r-${stamp}`}})]);expect(conflict.map(r=>r.status()).sort()).toEqual([200,409]);
    async function relation(child:string,parent:string){return a.c.post(`${contentPath}/${child}/relations`,{data:{relationType:"VARIANT_OF",parentContentId:parent}});}
    expect((await relation(clipIds[0],aiId)).status()).toBe(200);expect((await relation(clipIds[1],clipIds[0])).status()).toBe(200);expect((await relation(aiId,clipIds[1])).status()).toBe(409);expect((await relation(aiId,aiId)).status()).toBe(400);
    expect((await b.c.post(`/api/workspaces/${b.workspaceId}/content/${aiId}/relations`,{data:{relationType:"VARIANT_OF",parentContentId:clipIds[0]}})).status()).toBe(404);
    for(const sql of ["UPDATE content_versions SET sha256=repeat('0',64) WHERE content_item_id=$1","DELETE FROM content_versions WHERE content_item_id=$1","UPDATE review_decisions SET reason_text='Changed' WHERE content_item_id=$1","DELETE FROM job_artifacts WHERE id=(SELECT artifact_id FROM content_versions WHERE content_item_id=$1)","UPDATE job_artifacts SET status='FAILED' WHERE id=(SELECT artifact_id FROM content_versions WHERE content_item_id=$1)"]){await expect(db.query(sql,[aiId])).rejects.toBeTruthy();}
    await expect(db.query("DELETE FROM source_assets WHERE id=$1",[clips.source.id])).rejects.toBeTruthy();
    expect((await a.c.post(`${contentPath}/${clipIds[0]}/archive`)).status()).toBe(200);expect((await (await a.c.get(contentPath)).json()).total).toBe(2);expect((await a.c.get(`${contentPath}/${clipIds[0]}`)).status()).toBe(200);expect((await db.query("SELECT count(*) FROM content_versions WHERE content_item_id=$1",[clipIds[0]])).rows[0].count).toBe("1");
    // Thumbnail failure remains separate and can be retried without changing content.
    await db.query("UPDATE content_posters SET status='PENDING',attempts=2,available_at=now()-interval '1 day' WHERE content_version_id=$1",[detail.version.id]);posters({FFMPEG_PATH:"missing-phase6-ffmpeg"},detail.version.id);expect((await db.query("SELECT status FROM content_posters WHERE content_version_id=$1",[detail.version.id])).rows[0].status).toBe("FAILED");expect((await a.c.post(`${contentPath}/${aiId}/versions/${detail.version.id}/poster/retry`)).status()).toBe(200);posters({},detail.version.id);expect((await db.query("SELECT status FROM content_posters WHERE content_version_id=$1",[detail.version.id])).rows[0].status).toBe("READY");
    const posterUrl=await a.c.get(`${apiPath}?kind=poster`);expect(posterUrl.status()).toBe(200);const unsigned=new URL((await posterUrl.json()).url);unsigned.search="";expect((await fetch(unsigned)).status).not.toBe(200);
    posters({},clipDetails[1].version.id);await page.goto("http://127.0.0.1:3200/content");await expect(page.getByRole("heading",{name:"Content Library",exact:true})).toBeVisible();await expect.poll(()=>page.locator(".content-card img").evaluateAll(images=>images.length===2&&images.every(image=>(image as HTMLImageElement).complete&&(image as HTMLImageElement).naturalWidth>0))).toBe(true);await page.screenshot({path:"data/phase6/library.png",fullPage:true});await page.goto("http://127.0.0.1:3200/review");await expect(page.getByRole("heading",{name:"No content waiting for review."})).toBeVisible();
    const bytes=await import("node:fs/promises").then(fs=>fs.readFile("data/phase6/approved-ai-video.mp4"));expect(createHash("sha256").update(bytes).digest("hex")).toBe(detail.version.sha256);
    await writeFile("data/phase6/acceptance.json",JSON.stringify({result:"passed",email,workspaceId:a.workspaceId,productId:p.id,aiJobId,clipJobId:clips.jobId,aiContentIds:[aiId],clipContentIds:clipIds,aiVideoItems:1,clipItems:2,initialApprovals:2,initialRejections:1,concurrentPublicationCallsPerJob:10,historicalReferences:true,chromePreviewDownload:true,crossWorkspace:true,viewerReadOnly:true,archive:true,variantCycleRejected:true,realTranscriptionRuns:0,realOpenAICalls:0,realSeedanceGenerations:0},null,2));
  }finally{await unblock?.();await context.close();await a.c.dispose();await b.c.dispose();await db.end();}
});

test("non-successful jobs never publish content",async()=>{
  const a=await owner(`p6-states-${Date.now()}@example.test`),db=new pg.Client({connectionString:process.env.TEST_DATABASE_URL});await db.connect();try{
    const p=await product(a.c,a.workspaceId),ids=[];for(const status of ["FAILED","CANCELLED","RECONCILING"]){const r=await a.c.post(`/api/workspaces/${a.workspaceId}/ai-videos`,{data:{productId:p.id,prompt:"A simple controlled fixture video with the saved Product on a table.",tier:"QUALITY",durationSeconds:5,aspectRatio:"1:1",quantity:1,idempotencyKey:`p6-state-${status}-${Date.now()}`}});expect(r.status()).toBe(201);const id=(await r.json()).job.id;ids.push(id);await db.query("UPDATE jobs SET status=$1 WHERE id=$2",[status,id]);}
    dispatch();expect((await db.query("SELECT count(*) FROM content_publications WHERE job_id=ANY($1::uuid[])",[ids])).rows[0].count).toBe("0");expect((await (await a.c.get(`/api/workspaces/${a.workspaceId}/content`)).json()).total).toBe(0);
  }finally{await a.c.dispose();await db.end();}
});

test("replacement versions require their own approval and unsafe lineage cannot enter Content",async()=>{
  test.setTimeout(150000);
  const stamp=String(Date.now()),a=await owner(`p6-versions-${stamp}@example.test`),b=await owner(`p6-parent-${stamp}@example.test`),db=new pg.Client({connectionString:process.env.TEST_DATABASE_URL});await db.connect();let unblock:(()=>Promise<void>)|undefined;
  try{
    const p=await product(a.c,a.workspaceId),job1=await videoJob(a.c,a.workspaceId,p.id);expect(await settle(db,job1)).toBe("SUCCEEDED");const id=(publishJob(a.workspaceId,job1) as string[][])[0][0],path=`/api/workspaces/${a.workspaceId}/content/${id}`;
    const v1=(await (await a.c.get(path,{maxRetries:2})).json()).content;
    expect((await a.c.post(`${path}/review`,{data:{versionId:v1.version.id,decision:"APPROVE",expectedRevision:v1.reviewRevision,requestKey:`p6-v1-${stamp}`}})).status()).toBe(200);expect(approved(a.workspaceId,id,v1.version.id)).toBe(true);
    const job2=await videoJob(a.c,a.workspaceId,p.id);unblock=await blockPublication(db,job2,`version_${stamp}`);expect(await settle(db,job2)).toBe("SUCCEEDED");await unblock();unblock=undefined;
    const artifact=(await db.query("SELECT a.* FROM job_artifacts a JOIN jobs j ON j.id=a.job_id WHERE a.job_id=$1 AND j.result->'artifactIds' ? a.id::text",[job2])).rows[0];
    const insertVersion=`INSERT INTO content_versions(workspace_id,content_item_id,version_number,artifact_id,job_id,mime_type,byte_size,sha256,duration_seconds,width,height,product_id,product_version_id,product_rule_version_id)
      SELECT $1,$2,$3,a.id,j.id,a.mime_type,a.byte_size,coalesce($5,a.sha256),a.duration_seconds,a.width,a.height,j.product_id,j.product_version_id,j.product_rule_version_id FROM job_artifacts a JOIN jobs j ON j.workspace_id=a.workspace_id AND j.id=a.job_id WHERE a.id=$4 RETURNING id`;
    await db.query("BEGIN");const versionId=(await db.query(insertVersion,[a.workspaceId,id,2,artifact.id,null])).rows[0].id;
    await db.query(`INSERT INTO content_reference_assets(workspace_id,content_item_id,content_version_id,product_id,asset_id,asset_version_id,purpose) SELECT workspace_id,content_item_id,$1,product_id,asset_id,asset_version_id,purpose FROM content_reference_assets WHERE content_version_id=$2`,[versionId,v1.version.id]);
    await db.query("INSERT INTO content_posters(workspace_id,content_item_id,content_version_id) VALUES($1,$2,$3)",[a.workspaceId,id,versionId]);await db.query("UPDATE content_items SET current_version_id=$1 WHERE id=$2",[versionId,id]);await db.query("COMMIT");
    const v2=(await (await a.c.get(path)).json()).content;expect(v2.status).toBe("PENDING_REVIEW");expect(v2.version.number).toBe(2);expect(v2.originJob.id).toBe(job1);expect(v2.job.id).toBe(job2);expect(v2.reviews).toHaveLength(1);expect(v2.reviews[0].versionId).toBe(v1.version.id);expect(approved(a.workspaceId,id,v1.version.id)).toBe(false);expect(approved(a.workspaceId,id,versionId)).toBe(false);
    expect((await a.c.post(`${path}/review`,{data:{versionId:v1.version.id,decision:"APPROVE",expectedRevision:v2.reviewRevision,requestKey:`p6-stale-${stamp}`}})).status()).toBe(409);
    expect((await a.c.get(`${path}/versions/${v1.version.id}/media?kind=preview`)).status()).toBe(200);
    // Non-result READY, PENDING/FAILED and READY/lost-attempt artifacts cannot publish.
    const lost=(await db.query("INSERT INTO job_attempts(workspace_id,job_id,attempt_number,status) VALUES($1,$2,99,'LOST') RETURNING id",[a.workspaceId,job2])).rows[0].id;
    for(const [label,attempt,status] of [["lost",lost,"READY"],["pending",artifact.attempt_id,"PENDING"],["failed",artifact.attempt_id,"FAILED"],["unlisted",artifact.attempt_id,"READY"]]){
      const extra=(await db.query(`INSERT INTO job_artifacts(workspace_id,job_id,attempt_id,slot_name,status,storage_key,mime_type,expected_byte_size,expected_sha256,byte_size,sha256,duration_seconds,width,height) SELECT workspace_id,job_id,$1,$2,$3,$4,mime_type,expected_byte_size,expected_sha256,byte_size,sha256,duration_seconds,width,height FROM job_artifacts WHERE id=$5 RETURNING id`,[attempt,`excluded_${label}`,status,`p6-unwritten/${stamp}/${label}`,artifact.id])).rows[0].id;
      await expect(db.query(insertVersion,[a.workspaceId,id,3,extra,null])).rejects.toBeTruthy();
    }
    expect((publishJob(a.workspaceId,job2,10) as string[][]).every(ids=>ids.length===1&&ids[0]===id)).toBe(true);expect((await db.query("SELECT count(*) FROM content_items WHERE workspace_id=$1",[a.workspaceId])).rows[0].count).toBe("1");expect((await db.query("SELECT count(*) FROM content_versions WHERE job_id=$1",[job2])).rows[0].count).toBe("1");
    await expect(db.query(insertVersion,[a.workspaceId,id,3,artifact.id,"0".repeat(64)])).rejects.toBeTruthy();await expect(db.query(insertVersion,[b.workspaceId,id,3,artifact.id,null])).rejects.toBeTruthy();
    const pb=await product(b.c,b.workspaceId),jb=await videoJob(b.c,b.workspaceId,pb.id);expect(await settle(db,jb)).toBe("SUCCEEDED");const foreign=(publishJob(b.workspaceId,jb) as string[][])[0][0];
    expect((await a.c.post(`${path}/relations`,{data:{relationType:"VARIANT_OF",parentContentId:foreign}})).status()).toBe(404);await expect(db.query("INSERT INTO content_relations(workspace_id,content_item_id,relation_type,parent_content_id) VALUES($1,$2,'VARIANT_OF',$3)",[a.workspaceId,id,foreign])).rejects.toBeTruthy();
    await expect(db.query("UPDATE content_items SET current_version_id=(SELECT current_version_id FROM content_items WHERE id=$1) WHERE id=$2",[foreign,id])).rejects.toBeTruthy();
    expect((await a.c.post(`${path}/review`,{data:{versionId,decision:"APPROVE",expectedRevision:v2.reviewRevision,requestKey:`p6-v2-${stamp}`}})).status()).toBe(200);expect(approved(a.workspaceId,id,versionId)).toBe(true);expect(approved(b.workspaceId,id,versionId)).toBe(false);
    expect((await a.c.post(`${path}/archive`)).status()).toBe(200);expect(approved(a.workspaceId,id,versionId)).toBe(false);expect((await a.c.get(`${path}/versions/${versionId}/media?kind=download`)).status()).toBe(409);expect((await a.c.get(`${path}/versions/${versionId}/media?kind=preview`)).status()).toBe(200);
    await writeFile("data/phase6/version-scope.json",JSON.stringify({result:"passed",workspaceId:a.workspaceId,contentId:id,version1:v1.version.id,version2:versionId,newVersionPending:true,previousApprovalPreserved:true,staleVersionReviewDenied:true,approvalHelperVersionScoped:true,lostAndPendingArtifactsExcluded:true,crossWorkspaceParentDenied:true,databaseLineageGuards:true,realSeedanceGenerations:0},null,2));
  }finally{await db.query("ROLLBACK").catch(()=>{});await unblock?.();await a.c.dispose();await b.c.dispose();await db.end();}
});
