import {test,expect,type APIRequestContext} from '@playwright/test';
import pg from 'pg';
import {randomUUID,createHash} from 'node:crypto';
import {execFileSync,spawn,type ChildProcess} from 'node:child_process';
import {mkdir,writeFile} from 'node:fs/promises';
import {join} from 'node:path';
import {owner,source,dispatch,provision,worker,lease,submit} from '../clipper-helpers';
import {product,settle,videoJob,posters} from '../content-helpers';
import {paidPost} from '../billing-helpers';
import {definition,configuration,start,tick,detail,reviewOutputs,workflowEnv,claimFixtureWorkerProcess,completeFixtureWorkerProcess} from '../workflow-helpers';
const invoke=(command:string,arg='',extra:Record<string,string>={})=>JSON.parse(execFileSync(process.execPath,['--env-file=.env.local','--import','tsx','tests/invoke-phase9.ts',command,arg],{env:{...workflowEnv(),...extra},encoding:'utf8',windowsHide:true}));
async function database(){const db=new pg.Client({connectionString:process.env.TEST_DATABASE_URL});await db.connect();return db;}
async function quota(op:APIRequestContext,ws:string,name:string,value:string){const r=await op.post('/api/operations',{data:{action:'SET_QUOTA',targetId:ws,workspaceId:ws,limitName:name,value,reason:'Controlled isolated quota acceptance'}});expect(r.status(),await r.text()).toBe(200);}
async function running(db:pg.Client,service:string){await expect.poll(async()=>Number((await db.query("SELECT count(*) FROM service_heartbeats WHERE service=$1 AND status='RUNNING' AND last_tick_at>now()-interval '30 seconds'",[service])).rows[0].count)).toBeGreaterThan(0);}
function daemon(script:string,extra:Record<string,string>={}){const child=spawn(process.execPath,['--env-file=.env.local','--import','tsx',script],{env:{...workflowEnv(),DISPATCHER_POLL_MS:'30000',WORKFLOW_POLL_MS:'30000',...extra},windowsHide:true,stdio:['ignore','ignore','pipe','ipc']});child.stderr?.resume();return child;}
async function stop(child:ChildProcess){if(child.exitCode!==null||child.signalCode!==null)return;const closed=new Promise<void>((resolve,reject)=>{const timer=setTimeout(()=>{child.kill();reject(new Error('Graceful dispatcher drain exceeded bound'));},30000);child.once('exit',code=>{clearTimeout(timer);if(code===0)resolve();else reject(new Error('Dispatcher stopped abnormally'));});});child.send({command:'stop'});await closed;}

test('paid-beta quotas, operator separation, persistent throttling, safe mail, headers and restored-data fixture',async({browser,request})=>{
  test.setTimeout(240000);const db=await database(),op=await owner(process.env.PHASE9_OPERATOR_EMAIL!,false),a=await owner(`phase9-owner-${randomUUID()}@example.test`),ws=a.workspaceId;
  let execution:ChildProcess|undefined,orchestration:ChildProcess|undefined;
  try{
    const p=await product(a.c,ws),session=await (await a.c.get('/api/auth/session')).json(),userId=session.user.userId||session.user.id;
    for(const role of ['OWNER','ADMIN','EDITOR','VIEWER']){await db.query('UPDATE workspace_members SET role=$1 WHERE workspace_id=$2',[role,ws]);expect((await a.c.get('/api/operations')).status()).toBe(403);expect((await a.c.post('/api/operations',{data:{action:'SET_QUOTA',targetId:ws,reason:'Ordinary role cannot operate'}})).status()).toBe(403);}await db.query("UPDATE workspace_members SET role='OWNER' WHERE workspace_id=$1",[ws]);
    expect((await op.c.get('/api/operations')).status()).toBe(200);expect((await op.c.get(`/api/operations/workspace/${ws}`)).status()).toBe(200);
    expect((await op.c.post('/api/operations',{data:{action:'FORCE_PAID',targetId:ws,reason:'Forbidden action acceptance'}})).status()).toBe(400);
    await quota(op.c,ws,'active_jobs','1');
    const input={productId:p.id,prompt:'A controlled isolated Product scene on a bright studio table.',tier:'QUALITY',durationSeconds:5,aspectRatio:'1:1',quantity:1};
    const admitted=await Promise.all([paidPost(a.c,ws,'AI_VIDEO',{...input,idempotencyKey:randomUUID()}),paidPost(a.c,ws,'AI_VIDEO',{...input,idempotencyKey:randomUUID()})]);expect(admitted.map(r=>r.status()).sort()).toEqual([201,429]);const blocked=admitted.find(r=>r.status()===429)!;expect((await blocked.json()).code).toBe('WORKSPACE_QUOTA');expect(blocked.headers()['retry-after']).toBeTruthy();
    const queuedId=(await admitted.find(r=>r.status()===201)!.json()).job.id;expect((await db.query('SELECT count(*) FROM job_billing WHERE workspace_id=$1',[ws])).rows[0].count).toBe('1');expect((await a.c.post(`/api/workspaces/${ws}/jobs/${queuedId}/cancel`)).status()).toBe(200);dispatch();await quota(op.c,ws,'active_jobs','20');
    await quota(op.c,ws,'queued_ai_videos','1');const q1=await paidPost(a.c,ws,'AI_VIDEO',{...input,idempotencyKey:randomUUID()}),q2=await paidPost(a.c,ws,'AI_VIDEO',{...input,idempotencyKey:randomUUID()});expect(q1.status()).toBe(201);expect(q2.status()).toBe(429);const qId=(await q1.json()).job.id;await a.c.post(`/api/workspaces/${ws}/jobs/${qId}/cancel`);dispatch();await quota(op.c,ws,'queued_ai_videos','10');
    const assetRoot='/api/workspaces/'+ws+'/products/'+p.id+'/assets';const intentResponse=await a.c.post(assetRoot+'/upload-intents',{data:{purpose:'LEFT_SIDE',mimeType:'image/png',byteSize:p.reference.png.length,filename:'finalization.png',sha256:createHash('sha256').update(p.reference.png).digest('hex'),sourceType:'CUSTOMER_OWNED',permissionConfirmed:true,permissionNote:'Synthetic finalization fixture'}});expect(intentResponse.status()).toBe(201);const intent=(await intentResponse.json()).intent;expect((await fetch(intent.uploadUrl,{method:'PUT',headers:intent.requiredHeaders,body:new Uint8Array(p.reference.png)})).ok).toBe(true);await quota(op.c,ws,'storage_bytes','1');const finalization=await a.c.post(assetRoot+'/'+intent.assetId+'/versions/'+intent.versionId+'/finalize');expect(finalization.status()).toBe(429);expect((await db.query('SELECT status FROM asset_versions WHERE id=$1',[intent.versionId])).rows[0].status).toBe('PENDING_UPLOAD');await quota(op.c,ws,'storage_bytes','21474836480');expect((await a.c.post(assetRoot+'/'+intent.assetId+'/versions/'+intent.versionId+'/finalize')).status()).toBe(200);
    const d=await definition(a.c,ws,configuration(p.id));await quota(op.c,ws,'active_workflows','1');const runId=await start(a.c,ws,d.id),blockedRun=await a.c.post(`/api/workspaces/${ws}/workflows/${d.id}/runs`,{data:{idempotencyKey:randomUUID()}});expect(blockedRun.status()).toBe(429);expect((await db.query('SELECT count(*) FROM jobs WHERE workflow_run_id=$1',[runId])).rows[0].count).toBe('0');await a.c.post(`/api/workspaces/${ws}/workflows/runs/${runId}/cancel`);tick(runId);await quota(op.c,ws,'active_workflows','10');
    const s=await source(a.c,ws);await quota(op.c,ws,'source_uploads_daily','1');const sourceCount=(await db.query('SELECT count(*) FROM source_assets WHERE workspace_id=$1',[ws])).rows[0].count;expect((await a.c.post(`/api/workspaces/${ws}/sources`,{data:{filename:'blocked.mp4',mimeType:'video/mp4',byteSize:s.byteSize}})).status()).toBe(429);expect((await db.query('SELECT count(*) FROM source_assets WHERE workspace_id=$1',[ws])).rows[0].count).toBe(sourceCount);await quota(op.c,ws,'source_uploads_daily','20');
    await quota(op.c,ws,'storage_bytes','1');const paidCount=(await db.query('SELECT count(*) FROM job_billing WHERE workspace_id=$1',[ws])).rows[0].count;const noStorage=await paidPost(a.c,ws,'AI_VIDEO',{...input,idempotencyKey:randomUUID()});expect(noStorage.status()).toBe(429);expect((await db.query('SELECT count(*) FROM job_billing WHERE workspace_id=$1',[ws])).rows[0].count).toBe(paidCount);const uploadsBefore=(await db.query('SELECT count(*) FROM asset_versions WHERE workspace_id=$1',[ws])).rows[0].count;expect((await a.c.post(`/api/workspaces/${ws}/products/${p.id}/assets/upload-intents`,{data:{purpose:'FRONT',mimeType:'image/png',byteSize:p.reference.png.length,filename:'blocked.png',sha256:createHash('sha256').update(p.reference.png).digest('hex'),sourceType:'CUSTOMER_OWNED',permissionConfirmed:true}})).status()).toBe(429);expect((await db.query('SELECT count(*) FROM asset_versions WHERE workspace_id=$1',[ws])).rows[0].count).toBe(uploadsBefore);await quota(op.c,ws,'storage_bytes','21474836480');
    await quota(op.c,ws,'product_assets','1');expect((await a.c.post(`/api/workspaces/${ws}/products/${p.id}/assets/upload-intents`,{data:{purpose:'FRONT',mimeType:'image/png',byteSize:p.reference.png.length,filename:'limited.png',sourceType:'CUSTOMER_OWNED',permissionConfirmed:true}})).status()).toBe(429);await quota(op.c,ws,'product_assets','500');
    for(let i=0;i<2;i++)expect((await a.c.post(`/api/workspaces/${ws}/invitations`,{data:{email:`phase9-invite-${randomUUID()}@example.test`,role:'VIEWER'}})).status()).toBe(201);const before=(await db.query('SELECT count(*) FROM workspace_invitations WHERE workspace_id=$1',[ws])).rows[0].count,r=await a.c.post(`/api/workspaces/${ws}/invitations`,{data:{email:`phase9-invite-${randomUUID()}@example.test`,role:'VIEWER'}});expect(r.status()).toBe(429);expect(r.headers()['retry-after']).toBeTruthy();expect((await db.query('SELECT count(*) FROM workspace_invitations WHERE workspace_id=$1',[ws])).rows[0].count).toBe(before);
    const rateKey=randomUUID();expect(invoke('rate',rateKey).accepted).toBe(true);let persisted=false;try{invoke('rate',rateKey);}catch{persisted=true;}expect(persisted).toBe(true);expect(invoke('mail-failure').status).toBe('SENT');
    const health=await request.get('/api/health');expect(health.status()).toBe(200);expect(Object.keys(await health.json()).sort()).toEqual(['service','status','time']);expect(health.headers()['content-security-policy']).toContain("object-src 'none'");expect(health.headers()['x-frame-options']).toBe('DENY');expect(health.headers()['x-content-type-options']).toBe('nosniff');expect(health.headers()['x-request-id']).toMatch(/^[a-f0-9-]{36}$/);expect((await request.get('/api/readiness')).status()).toBe(401);expect((await op.c.get('/api/readiness')).status()).toBe(200);
    expect(invoke('readiness','',{OBJECT_STORAGE_ENDPOINT:'http://127.0.0.1:1'}).checks.storage).toBe('UNAVAILABLE');expect(invoke('readiness','',{DATABASE_URL:new URL('postgresql://fixture:fixture@127.0.0.1:1/unavailable').toString(),TEST_DATABASE_URL:'postgresql://fixture:fixture@127.0.0.1:1/unavailable'}).checks.database).toBe('UNAVAILABLE');
    expect((await a.c.post('/api/workspaces',{headers:{Origin:'https://untrusted.example.test'},data:{name:'Forbidden'}})).status()).toBe(403);expect((await a.c.post('/api/workspaces',{data:{name:'x'.repeat(17000)}})).status()).toBe(413);
    const login=await request.post('/api/auth/login',{headers:{Origin:'http://127.0.0.1:3200'},data:{email:`phase9-owner-invalid@example.test`,password:'invalid'}});expect(login.status()).toBe(401);
    await quota(op.c,ws,'queued_clipper_jobs','1');const cq=await submit(a.c,ws,s.id,randomUUID()),cqBlocked=await submit(a.c,ws,s.id,randomUUID());expect(cq.status()).toBe(201);expect(cqBlocked.status()).toBe(429);await a.c.post('/api/workspaces/'+ws+'/jobs/'+(await cq.json()).job.id+'/cancel');dispatch();await quota(op.c,ws,'queued_clipper_jobs','5');
    execution=daemon('scripts/dispatcher.ts');await running(db,'execution_dispatcher');await stop(execution);execution=undefined;const delayed=await videoJob(a.c,ws,p.id);expect((await db.query('SELECT status FROM jobs WHERE id=$1',[delayed])).rows[0].status).toBe('QUEUED');expect((await op.c.get('/api/operations')).status()).toBe(200);expect((await (await op.c.get('/api/operations')).json()).services.find((x:{service:string})=>x.service==='execution_dispatcher').status).toBe('OFFLINE');expect(await settle(db,delayed)).toBe('SUCCEEDED');expect((await db.query('SELECT count(*) FROM provider_executions WHERE job_id=$1',[delayed])).rows[0].count).toBe('1');
    const three=await definition(a.c,ws,configuration(p.id,{videosPerScript:3})),workflowId=await start(a.c,ws,three.id);orchestration=daemon('scripts/workflow-dispatcher.ts');await running(db,'workflow_dispatcher');await stop(orchestration);orchestration=undefined;expect((await db.query('SELECT count(*) FROM jobs WHERE workflow_run_id=$1',[workflowId])).rows[0].count).toBe('2');
    const children=(await db.query('SELECT id FROM jobs WHERE workflow_run_id=$1',[workflowId])).rows;for(const j of children)expect(await settle(db,j.id)).toBe('SUCCEEDED');expect((await db.query('SELECT count(*) FROM jobs WHERE workflow_run_id=$1',[workflowId])).rows[0].count).toBe('2');expect((await (await op.c.get('/api/operations')).json()).services.find((x:{service:string})=>x.service==='workflow_dispatcher').status).toBe('OFFLINE');
    orchestration=daemon('scripts/workflow-dispatcher.ts');await running(db,'workflow_dispatcher');await stop(orchestration);orchestration=undefined;const all=(await db.query('SELECT id FROM jobs WHERE workflow_run_id=$1',[workflowId])).rows;expect(all).toHaveLength(3);for(const j of all)expect(await settle(db,j.id)).toBe('SUCCEEDED');tick(workflowId);await reviewOutputs(a.c,ws,workflowId,['APPROVE','REJECT','APPROVE']);tick(workflowId);expect((await detail(a.c,ws,workflowId)).run.status).toBe('SUCCEEDED');expect((await db.query("SELECT count(*) FROM token_ledger_entries WHERE entry_type='RESERVE' AND job_id IN(SELECT id FROM jobs WHERE workflow_run_id=$1)",[workflowId])).rows[0].count).toBe('3');
    const clipD=await definition(a.c,ws,{sourceAssetId:s.id,productId:p.id,language:'en',goal:'Find useful ideas',targetClipCount:2,minClipSeconds:10,maxClipSeconds:30,captions:true,maxTokens:'2000'},'SOURCE_CLIPPER_REVIEW_V1'),clipRun=await start(a.c,ws,clipD.id);tick(clipRun);dispatch();const clipJob=(await db.query('SELECT id,status FROM jobs WHERE workflow_run_id=$1',[clipRun])).rows[0];expect(clipJob.status).toBe('WAITING_FOR_WORKER');
    const w=provision(`phase9-offline-${Date.now()}`),wc=await worker(w.credential),fixture=await claimFixtureWorkerProcess(w.credential);expect(fixture.claim.jobId).toBe(clipJob.id);await quota(op.c,ws,'storage_bytes','1');const slot=await wc.post('/api/worker/jobs/'+clipJob.id+'/outputs',{data:{...lease(fixture.claim),slotName:'transcript',mimeType:'application/json',byteSize:128,sha256:'a'.repeat(64)}});expect(slot.status()).toBe(429);expect((await db.query('SELECT count(*) FROM job_artifacts WHERE job_id=$1',[clipJob.id])).rows[0].count).toBe('0');await quota(op.c,ws,'storage_bytes','21474836480');await fixture.stop();await db.query("UPDATE workers SET last_heartbeat_at=now()-interval '3 minutes' WHERE id=$1",[w.workerId]);expect((await (await op.c.get('/api/operations')).json()).workers.find((x:{id:string})=>x.id===w.workerId).freshness).toBe('OFFLINE');await db.query("UPDATE worker_leases SET expires_at=now()-interval '1 second' WHERE id=$1",[fixture.claim.leaseId]);dispatch();expect((await wc.post(`/api/worker/jobs/${clipJob.id}/progress`,{data:{...lease(fixture.claim),sequence:100,percent:90,stage:'RENDERING',message:'late worker'}})).status()).toBe(409);await db.query("UPDATE workers SET status='DISABLED' WHERE id=$1",[w.workerId]);await new Promise(resolve=>setTimeout(resolve,1100));await completeFixtureWorkerProcess(ws,clipJob.id,s);await wc.dispose();dispatch();tick(clipRun);await reviewOutputs(a.c,ws,clipRun,['APPROVE','REJECT']);tick(clipRun);expect((await detail(a.c,ws,clipRun)).run.status).toBe('SUCCEEDED');expect((await db.query('SELECT count(*) FROM jobs WHERE workflow_run_id=$1',[clipRun])).rows[0].count).toBe('1');
    const packs=await (await a.c.get(`/api/workspaces/${ws}/billing/packages`)).json(),payment=await a.c.post(`/api/workspaces/${ws}/billing/payments`,{data:{packageVersionId:packs.packages[0].id,idempotencyKey:randomUUID()}});expect(payment.status()).toBe(201);const paymentId=(await payment.json()).payment.id;for(let i=0;i<2;i++)expect((await a.c.post(`/api/workspaces/${ws}/billing/payments/${paymentId}/simulate`,{data:{status:'PAID'}})).status()).toBe(200);expect((await db.query("SELECT count(*) FROM token_ledger_entries WHERE payment_id=$1 AND entry_type='PURCHASE'",[paymentId])).rows[0].count).toBe('1');
    posters();const content=(await db.query('SELECT i.id,v.id AS version_id FROM content_items i JOIN content_versions v ON v.id=i.current_version_id WHERE i.workspace_id=$1 ORDER BY i.id LIMIT 1',[ws])).rows[0],media=await a.c.get(`/api/workspaces/${ws}/content/${content.id}/versions/${content.version_id}/media`);expect(media.status()).toBe(200);const mediaUrl=(await media.json()).url;expect((await fetch(mediaUrl)).ok).toBe(true);expect((await fetch(mediaUrl.split('?')[0])).status).toBe(403);
    const audit=invoke('audits');expect(Object.values(audit.billing as Record<string,unknown[]>).every(rows=>rows.length===0)).toBe(true);expect(invoke('storage',ws).findings.every((f:{status:string})=>f.status==='VERIFIED')).toBe(true);
    expect((await db.query("SELECT count(*) FROM audit_events WHERE workspace_id=$1 AND event_type='WORKSPACE_LIMIT_CHANGED'",[ws])).rows[0].count).not.toBe('0');
    const ctx=await browser.newContext({storageState:await a.c.storageState()}),page=await ctx.newPage();await page.goto('/');await expect(page.getByRole('heading',{name:`Welcome to Clipper` ,exact:false})).toBeVisible();await page.goto('/content');await expect(page.getByRole('heading',{name:'Content Library',exact:true})).toBeVisible();await ctx.close();
    const support=await browser.newContext({storageState:await op.c.storageState()}),supportPage=await support.newPage();await supportPage.goto('/operations');await expect(supportPage.getByRole('heading',{name:'Platform operations',exact:true})).toBeVisible();await support.close();
    await mkdir('data/phase9',{recursive:true});const fixtureData={email:(await (await a.c.get('/api/auth/session')).json()).user.email,password:'ValidPassword123!',workspaceId:ws,productId:p.id,sourceId:s.id,workflowId,clipRun,clipJobId:clipJob.id,paymentId,contentId:content.id,versionId:content.version_id,userId};await writeFile(join(process.cwd(),'data/phase9/restore-fixture.json'),JSON.stringify(fixtureData,null,2),{mode:0o600});await writeFile('data/phase9/hardening-acceptance.json',JSON.stringify({operatorIsolation:true,quotasBeforeMutation:true,persistentRateLimit:true,mailRetry:true,headers:true,readinessFailureInjection:true,gracefulDispatcherRecovery:true,gracefulWorkflowRecovery:true,workerOfflineRecovery:true,privateMedia:true,financialReconciliation:true,fixture:ws},null,2));
  }finally{if(execution)await stop(execution);if(orchestration)await stop(orchestration);await a.c.dispose();await op.c.dispose();await db.end();}
});
