import {test,expect,type APIRequestContext} from "@playwright/test";
import pg from "pg";
import {randomUUID} from "node:crypto";
import {mkdir,writeFile} from "node:fs/promises";
import {owner,dispatch,source,provision,worker,lease} from "../clipper-helpers";
import {product,fields,settle,videoJob,blockPublication,approved} from "../content-helpers";
import {fundFixture} from "../billing-helpers";
import {configuration,definition,start,detail,tick,asyncTick,crashTick,reviewOutputs,stressTick,refundChild,claimFixtureWorkerProcess,completeFixtureWorkerProcess} from "../workflow-helpers";
async function connect(){const db=new pg.Client({connectionString:process.env.TEST_DATABASE_URL});await db.connect();return db;}
const root=(ws:string)=>`/api/workspaces/${ws}/workflows`;
async function jobs(db:pg.Client,id:string){return (await db.query("SELECT id,status,input_snapshot,workflow_step_id FROM jobs WHERE workflow_run_id=$1 ORDER BY idempotency_key",[id])).rows;}
async function lifecycle(db:pg.Client,id:string){return (await db.query("SELECT entry_type,count(*)::integer AS count FROM token_ledger_entries WHERE job_id IN (SELECT id FROM jobs WHERE workflow_run_id=$1) GROUP BY entry_type ORDER BY entry_type",[id])).rows;}
async function setup(fund=true){const a=await owner(`p8-${randomUUID()}@example.test`,fund),p=await product(a.c,a.workspaceId);return {...a,p};}
async function decide(c:APIRequestContext,ws:string,id:string,decisions:string[]){tick(id);await reviewOutputs(c,ws,id,decisions);tick(id);return detail(c,ws,id);}

test("AI workflow: four paid children, frozen versions, mixed review, lineage and zero parent charge",async()=>{
  test.setTimeout(150000);const a=await setup(),db=await connect();try{
    const config=configuration(a.p.id,{scripts:["Morning skincare routine with the saved Product and a gentle close-up.","Problem-solution hook showing the saved Product in a bright studio."],videosPerScript:2});
    const estimate=await a.c.post(`${root(a.workspaceId)}/estimate`,{data:{templateKey:"PRODUCT_AI_VIDEO_REVIEW_V1",configuration:config}});expect((await estimate.json()).estimate).toMatchObject({estimatedTokens:"2800",intendedChildren:4});
    const d=await definition(a.c,a.workspaceId,config),request={idempotencyKey:randomUUID(),definitionVersionId:d.versionId};
    const responses=await Promise.all([a.c.post(`${root(a.workspaceId)}/${d.id}/runs`,{data:request}),a.c.post(`${root(a.workspaceId)}/${d.id}/runs`,{data:request})]);expect(responses.map(r=>r.status()).sort()).toEqual([200,201]);const id=(await responses[0].json()).run.id;
    expect((await a.c.post(`${root(a.workspaceId)}/${d.id}/runs`,{data:{...request,maxTokens:"6000"}})).status()).toBe(409);
    const snapshot=(await db.query("SELECT input_snapshot FROM workflow_runs WHERE id=$1",[id])).rows[0].input_snapshot;
    await expect(db.query("UPDATE workflow_runs SET input_snapshot='{}' WHERE id=$1",[id])).rejects.toThrow();await expect(db.query("UPDATE workflow_definition_versions SET configuration='{}' WHERE id=$1",[d.versionId])).rejects.toThrow();
    expect((await a.c.patch(`/api/workspaces/${a.workspaceId}/products/${a.p.id}`,{data:{...fields,name:"Updated Product",description:"New Product version"}})).status()).toBe(200);
    const edit=await a.c.patch(`${root(a.workspaceId)}/${d.id}`,{data:{name:"Updated workflow",templateKey:"PRODUCT_AI_VIDEO_REVIEW_V1",configuration:configuration(a.p.id),expectedVersionId:d.versionId}});expect(edit.status(),await edit.text()).toBe(200);expect((await edit.json()).definition.versionNumber).toBe(2);
    tick(id);tick(id);const child=await jobs(db,id);expect(child).toHaveLength(4);expect(child.every(j=>j.input_snapshot.product.versionId===snapshot.prepared[0].product.versionId)).toBe(true);
    expect((await db.query("SELECT count(*) FROM workflow_steps WHERE workflow_run_id=$1",[id])).rows[0].count).toBe("12");expect((await db.query("SELECT count(DISTINCT quote_id) FROM job_billing WHERE job_id=ANY($1::uuid[])",[child.map(c=>c.id)])).rows[0].count).toBe("4");
    expect(await settle(db,child[0].id)).toBe("SUCCEEDED");tick(id);const waiting=await detail(a.c,a.workspaceId,id);expect(waiting.run.status).toBe("WAITING_FOR_REVIEW");expect(waiting.outputs).toHaveLength(4);expect(JSON.stringify(waiting)).not.toMatch(/storageKey|storage_key|executionProvider|worker_credentials|quoteHash/);
    const before=await lifecycle(db,id),result=await decide(a.c,a.workspaceId,id,["APPROVE","APPROVE","REJECT","REJECT"]);expect(result.run.status).toBe("SUCCEEDED");expect(result.run.result.approvedContentIds).toHaveLength(2);expect(result.run.result.rejectedContentIds).toHaveLength(2);expect(await lifecycle(db,id)).toEqual(before);expect(before).toEqual([{entry_type:"CAPTURE",count:4},{entry_type:"RESERVE",count:4}]);
    const lineage=(await db.query("SELECT v.workflow_run_id,v.workflow_step_id,j.workflow_step_id AS job_step,r.definition_version_id FROM content_versions v JOIN jobs j ON j.id=v.job_id JOIN workflow_runs r ON r.id=v.workflow_run_id WHERE v.workflow_run_id=$1",[id])).rows;expect(lineage).toHaveLength(4);expect(lineage.every(v=>v.workflow_step_id===v.job_step&&v.definition_version_id===d.versionId)).toBe(true);
    const next=await start(a.c,a.workspaceId,d.id);expect((await db.query("SELECT input_snapshot->'prepared'->0->'product'->>'versionId' AS version FROM workflow_runs WHERE id=$1",[next])).rows[0].version).not.toBe(snapshot.prepared[0].product.versionId);
    expect((await a.c.post(`${root(a.workspaceId)}/${d.id}/archive`)).status()).toBe(200);expect((await a.c.post(`${root(a.workspaceId)}/${d.id}/runs`,{data:{idempotencyKey:randomUUID()}})).status()).toBe(409);expect((await detail(a.c,a.workspaceId,id)).run.status).toBe("SUCCEEDED");
    await mkdir("data/phase8",{recursive:true});await writeFile("data/phase8/ai-acceptance.json",JSON.stringify({runId:id,intendedChildren:4,jobs:4,childQuotes:4,reservations:4,captures:4,releases:0,contentItems:4,approved:2,rejected:2,parentLedgerMovements:0,tokensCaptured:result.budget.captured,lineageRows:lineage.length},null,2));
  }finally{await a.c.dispose();await db.end();}
});
test("low funds, expired quote refresh, price change and budget increase retain the same child intent",async()=>{
  const a=await setup(false),db=await connect();let original:string|undefined,catalog:string|undefined;try{
    fundFixture(a.workspaceId,"700");const d=await definition(a.c,a.workspaceId,configuration(a.p.id,{videosPerScript:2,maxTokens:"1400"})),id=await start(a.c,a.workspaceId,d.id);tick(id);
    let data=await detail(a.c,a.workspaceId,id);expect(data.run.status).toBe("WAITING_FOR_FUNDS");expect(data.children).toHaveLength(1);const first=data.children[0].job_id;
    const blocked=(await db.query("SELECT id,output_snapshot FROM workflow_steps WHERE workflow_run_id=$1 AND step_key='video:01:02'",[id])).rows[0];
    const expired=(await db.query("INSERT INTO billing_quotes(workspace_id,created_by,operation,price_version_id,request_hash,input_hash,input_snapshot,token_amount,quote_hash,expires_at) SELECT workspace_id,created_by,operation,price_version_id,request_hash,input_hash,input_snapshot,token_amount,quote_hash,now()-interval '1 second' FROM billing_quotes WHERE id=$1 RETURNING id",[blocked.output_snapshot.pendingQuoteId])).rows[0].id;await db.query("UPDATE workflow_steps SET output_snapshot=$1::jsonb WHERE id=$2",[JSON.stringify({pendingQuoteId:expired}),blocked.id]);tick(id);expect((await db.query("SELECT output_snapshot->>'pendingQuoteId' AS quote FROM workflow_steps WHERE id=$1",[blocked.id])).rows[0].quote).not.toBe(expired);
    const cat=(await db.query("SELECT id,active_version_id FROM price_catalogs WHERE realm='TEST' AND operation='AI_VIDEO'")).rows[0];original=cat.active_version_id;catalog=cat.id;
    const price=(await db.query("INSERT INTO price_versions(catalog_id,version_number,label,rules) SELECT $1,coalesce(max(version_number),0)+1,'TEST Workflow price change',$2::jsonb FROM price_versions WHERE catalog_id=$1 RETURNING id",[catalog,JSON.stringify({tier:"QUALITY",base:"0",perSecond:"180"})])).rows[0].id;await db.query("UPDATE price_catalogs SET active_version_id=$1 WHERE id=$2",[price,catalog]);tick(id);data=await detail(a.c,a.workspaceId,id);expect(data.run.failureCode).toBe("BUDGET_EXCEEDED");expect(data.run.status).toBe("PAUSED");expect(data.children).toHaveLength(1);
    fundFixture(a.workspaceId,"2000");expect((await a.c.post(`${root(a.workspaceId)}/runs/${id}/budget`,{data:{maxTokens:"1600"}})).status()).toBe(200);tick(id);data=await detail(a.c,a.workspaceId,id);expect(data.children).toHaveLength(2);expect(data.children[0].job_id).toBe(first);const billing=(await db.query("SELECT price_version_id,token_amount FROM job_billing WHERE job_id=ANY($1::uuid[]) ORDER BY token_amount",[data.children.map((c:{job_id:string})=>c.job_id)])).rows;expect(billing).toEqual([{price_version_id:original,token_amount:"700"},{price_version_id:price,token_amount:"900"}]);expect((await db.query("SELECT count(*) FROM token_ledger_entries WHERE entry_type='RESERVE' AND job_id IN(SELECT id FROM jobs WHERE workflow_run_id=$1)",[id])).rows[0].count).toBe("2");
    expect((await a.c.post(`${root(a.workspaceId)}/runs/${id}/budget`,{data:{maxTokens:"1500"}})).status()).toBe(400);
    await mkdir("data/phase8",{recursive:true});await writeFile("data/phase8/funds-acceptance.json",JSON.stringify({runId:id,firstChild:first,waitingForFunds:true,expiredQuoteRefreshed:true,budgetExceeded:true,budgetIncreased:true,jobs:2,reservations:2,childAmounts:["700","900"]},null,2));
  }finally{if(original&&catalog)await db.query("UPDATE price_catalogs SET active_version_id=$1 WHERE id=$2",[original,catalog]);await a.c.dispose();await db.end();}
});
test("wallet funding automatically resumes a blocked run without a customer Resume action",async()=>{
  const a=await setup(false),db=await connect();try{fundFixture(a.workspaceId,"700");const d=await definition(a.c,a.workspaceId,configuration(a.p.id,{videosPerScript:2})),id=await start(a.c,a.workspaceId,d.id);tick(id);const first=(await jobs(db,id))[0].id;expect((await detail(a.c,a.workspaceId,id)).run.status).toBe("WAITING_FOR_FUNDS");fundFixture(a.workspaceId,"701");tick(id);expect(await jobs(db,id)).toHaveLength(2);expect((await jobs(db,id))[0].id).toBe(first);expect((await detail(a.c,a.workspaceId,id)).run.status).toBe("RUNNING");}finally{await a.c.dispose();await db.end();}
});
test("a refunded successful child keeps consuming the v1 ceiling and is never automatically rerun",async()=>{
  const a=await setup(),db=await connect();try{const d=await definition(a.c,a.workspaceId,configuration(a.p.id,{videosPerScript:2,maxTokens:"700"})),id=await start(a.c,a.workspaceId,d.id);tick(id,1);const first=(await jobs(db,id))[0].id;await settle(db,first);tick(id);expect((await detail(a.c,a.workspaceId,id)).run.failureCode).toBe("BUDGET_EXCEEDED");const operator=(await db.query("SELECT created_by FROM workspaces WHERE id=$1",[a.workspaceId])).rows[0].created_by;refundChild(a.workspaceId,operator,first);tick(id);const data=await detail(a.c,a.workspaceId,id);expect(data.budget).toMatchObject({captured:"700",refunded:"700",committed:"700",remaining:"0"});expect(data.run.failureCode).toBe("BUDGET_EXCEEDED");expect(await jobs(db,id)).toHaveLength(1);expect(await lifecycle(db,id)).toEqual([{entry_type:"CAPTURE",count:1},{entry_type:"REFUND",count:1},{entry_type:"RESERVE",count:1}]);}finally{await a.c.dispose();await db.end();}
});
test("pause lets admitted children finish, creates no new children, then resumes remaining children once",async()=>{
  test.setTimeout(150000);const a=await setup(),db=await connect();try{const d=await definition(a.c,a.workspaceId,configuration(a.p.id,{scripts:["Show the saved Product in a morning routine with a close-up.","Show the saved Product using a simple problem and solution hook."],videosPerScript:2})),id=await start(a.c,a.workspaceId,d.id);tick(id);const first=await jobs(db,id);expect(first).toHaveLength(2);const ledger=await lifecycle(db,id);await a.c.post(`${root(a.workspaceId)}/runs/${id}/pause`);tick(id,5);expect(await jobs(db,id)).toHaveLength(2);expect(await lifecycle(db,id)).toEqual(ledger);await settle(db,first[0].id);tick(id);expect((await detail(a.c,a.workspaceId,id)).run.status).toBe("PAUSED");expect((await jobs(db,id)).every(j=>j.status==="SUCCEEDED")).toBe(true);await a.c.post(`${root(a.workspaceId)}/runs/${id}/resume`);tick(id);tick(id);expect(await jobs(db,id)).toHaveLength(4);expect((await jobs(db,id)).slice(0,2).map(j=>j.id)).toEqual(first.map(j=>j.id));expect((await lifecycle(db,id)).find(e=>e.entry_type==="RESERVE").count).toBe(4);}finally{await a.c.dispose();await db.end();}
});
test("cancel preserves completed captures, uses child cancellation for running work and never admits the rest",async()=>{
  test.setTimeout(150000);const a=await setup(),db=await connect();try{const d=await definition(a.c,a.workspaceId,configuration(a.p.id,{videosPerScript:3})),id=await start(a.c,a.workspaceId,d.id);tick(id,1);const first=(await jobs(db,id))[0].id;await settle(db,first);tick(id,1);const second=(await jobs(db,id))[1].id;dispatch();expect((await db.query("SELECT status FROM jobs WHERE id=$1",[second])).rows[0].status).toBe("RUNNING");await a.c.post(`${root(a.workspaceId)}/runs/${id}/cancel`);tick(id);await settle(db,second);tick(id);const data=await detail(a.c,a.workspaceId,id);expect(data.run.status).toBe("CANCELLED");expect(data.children).toHaveLength(2);expect((await db.query("SELECT status FROM job_billing WHERE job_id=$1",[first])).rows[0].status).toBe("CAPTURED");expect((await jobs(db,id)).every(j=>["SUCCEEDED","CANCELLED"].includes(j.status))).toBe(true);expect((await lifecycle(db,id)).find(e=>e.entry_type==="RESERVE").count).toBe(2);}finally{await a.c.dispose();await db.end();}
});
test("partial failures release child tokens and successful siblings reach review; all failed skips review",async()=>{
  test.setTimeout(150000);const a=await setup(),db=await connect();try{const d=await definition(a.c,a.workspaceId,configuration(a.p.id,{scripts:["Show the saved Product in a morning routine with a close-up.","Show the saved Product using a simple problem and solution hook."],videosPerScript:2})),id=await start(a.c,a.workspaceId,d.id);tick(id,5);const child=await jobs(db,id);await db.query("UPDATE jobs SET status='FAILED',error_code='FIXTURE_FAILURE',error_message_safe='Controlled fake child failure',finished_at=now() WHERE id=$1",[child[3].id]);await settle(db,child[0].id);tick(id);expect((await detail(a.c,a.workspaceId,id)).outputs).toHaveLength(3);const result=await decide(a.c,a.workspaceId,id,["APPROVE","REJECT","REJECT"]);expect(result.run.status).toBe("SUCCEEDED");expect(result.budget.released).toBe("700");expect(await lifecycle(db,id)).toEqual([{entry_type:"CAPTURE",count:3},{entry_type:"RELEASE",count:1},{entry_type:"RESERVE",count:4}]);
    const all=await start(a.c,a.workspaceId,d.id);tick(all,5);await db.query("UPDATE jobs SET status='FAILED',error_code='FIXTURE_FAILURE',finished_at=now() WHERE workflow_run_id=$1",[all]);dispatch();tick(all);const failed=await detail(a.c,a.workspaceId,all);expect(failed.run.status).toBe("FAILED");expect(failed.run.failureCode).toBe("NO_USABLE_CONTENT");expect(failed.outputs).toHaveLength(0);expect(failed.budget.committed).toBe("0");
    const fastD=await definition(a.c,a.workspaceId,configuration(a.p.id,{videosPerScript:3,failurePolicy:"FAIL_FAST"})),fast=await start(a.c,a.workspaceId,fastD.id);tick(fast,1);await db.query("UPDATE jobs SET status='FAILED',finished_at=now() WHERE workflow_run_id=$1",[fast]);dispatch();tick(fast);expect((await detail(a.c,a.workspaceId,fast)).run.failureCode).toBe("CHILD_FAILED");expect(await jobs(db,fast)).toHaveLength(1);
  }finally{await a.c.dispose();await db.end();}
});
test("all rejected fails without a generation refund",async()=>{
  const a=await setup(),db=await connect();try{const d=await definition(a.c,a.workspaceId,configuration(a.p.id)),id=await start(a.c,a.workspaceId,d.id);tick(id);await settle(db,(await jobs(db,id))[0].id);const data=await decide(a.c,a.workspaceId,id,["REJECT"]);expect(data.run.status).toBe("FAILED");expect(data.run.failureCode).toBe("NO_APPROVED_CONTENT");expect(data.run.result.approvedContentIds).toEqual([]);expect(await lifecycle(db,id)).toEqual([{entry_type:"CAPTURE",count:1},{entry_type:"RESERVE",count:1}]);}finally{await a.c.dispose();await db.end();}
});
test("review binds exact versions and a replacement version cannot inherit an old approval",async()=>{
  test.setTimeout(150000);const a=await setup(),db=await connect();let unblock:(()=>Promise<void>)|undefined;try{const d=await definition(a.c,a.workspaceId,configuration(a.p.id)),id=await start(a.c,a.workspaceId,d.id);tick(id);await settle(db,(await jobs(db,id))[0].id);tick(id);await reviewOutputs(a.c,a.workspaceId,id,["APPROVE"]);const o=(await detail(a.c,a.workspaceId,id)).outputs[0];expect(approved(a.workspaceId,o.contentId,o.versionId)).toBe(true);
    const replacement=await videoJob(a.c,a.workspaceId,a.p.id);unblock=await blockPublication(db,replacement,`p8_${Date.now()}`);await settle(db,replacement);await unblock();unblock=undefined;
    const v=(await db.query(`INSERT INTO content_versions(workspace_id,content_item_id,version_number,artifact_id,job_id,mime_type,byte_size,sha256,duration_seconds,width,height,product_id,product_version_id,product_rule_version_id)
      SELECT $1,$2,2,a.id,j.id,a.mime_type,a.byte_size,a.sha256,a.duration_seconds,a.width,a.height,j.product_id,j.product_version_id,j.product_rule_version_id FROM job_artifacts a JOIN jobs j ON j.workspace_id=a.workspace_id AND j.id=a.job_id WHERE j.id=$3 AND a.status='READY' AND j.result->'artifactIds' ? a.id::text RETURNING id`,[a.workspaceId,o.contentId,replacement])).rows[0].id;await db.query("UPDATE content_items SET current_version_id=$1 WHERE id=$2",[v,o.contentId]);expect(approved(a.workspaceId,o.contentId,o.versionId)).toBe(false);tick(id);const final=await detail(a.c,a.workspaceId,id);expect(final.run.status).toBe("FAILED");expect(final.run.failureCode).toBe("CONTENT_VERSION_UNAVAILABLE");expect(final.outputs[0].versionId).toBe(o.versionId);
  }finally{if(unblock)await unblock();await a.c.dispose();await db.end();}
});
test("two concurrent reconcilers and crashes at both admission boundaries create one job and reservation",async()=>{
  const a=await setup(),db=await connect();try{const d=await definition(a.c,a.workspaceId,configuration(a.p.id));for(const point of ["AFTER_READY","AFTER_ADMISSION"]){const id=await start(a.c,a.workspaceId,d.id);await crashTick(id,point);expect(await jobs(db,id)).toHaveLength(0);expect(await lifecycle(db,id)).toEqual([]);await Promise.all([asyncTick(id),asyncTick(id)]);stressTick(id);expect(await jobs(db,id)).toHaveLength(1);expect(await lifecycle(db,id)).toEqual([{entry_type:"RESERVE",count:1}]);expect((await db.query("SELECT count(*) FROM workflow_child_jobs WHERE workflow_run_id=$1",[id])).rows[0].count).toBe("1");}
    const id=await start(a.c,a.workspaceId,d.id);await Promise.all(Array.from({length:8},()=>asyncTick(id)));expect(await jobs(db,id)).toHaveLength(1);
    await mkdir("data/phase8",{recursive:true});await writeFile("data/phase8/concurrency-acceptance.json",JSON.stringify({runId:id,simultaneousReconcilers:8,children:1,reservations:1,crashPoints:["AFTER_READY","AFTER_ADMISSION"],bothRecovered:true},null,2));
  }finally{await a.c.dispose();await db.end();}
});
test("Clipper workflow uses one paid child, survives a lost worker lease and reviews two deterministic clips",async()=>{
  test.setTimeout(150000);
  const a=await owner(`p8-clips-${randomUUID()}@example.test`),db=await connect();
  let runId:string|undefined,w:ReturnType<typeof provision>|undefined,wc:APIRequestContext|undefined,fixtureWorker:Awaited<ReturnType<typeof claimFixtureWorkerProcess>>|undefined;
  try{
    const s=await source(a.c,a.workspaceId),d=await definition(a.c,a.workspaceId,{sourceAssetId:s.id,language:"en",goal:"Find useful ideas",targetClipCount:2,minClipSeconds:10,maxClipSeconds:30,captions:true,maxTokens:"2000"},"SOURCE_CLIPPER_REVIEW_V1"),id=await start(a.c,a.workspaceId,d.id);runId=id;
    tick(id);const job=(await jobs(db,id))[0];expect(job.input_snapshot.source.storageIdentity).toBe(s.id);
    w=provision(`p8-lost-${Date.now()}`);wc=await worker(w.credential);dispatch();
    fixtureWorker=await claimFixtureWorkerProcess(w.credential);const {claim}=fixtureWorker;expect(claim.jobId).toBe(job.id);
    await fixtureWorker.stop();
    await db.query("UPDATE worker_leases SET expires_at=now()-interval '1 second' WHERE id=$1",[claim.leaseId]);dispatch();
    expect((await wc.post(`/api/worker/jobs/${job.id}/progress`,{data:{...lease(claim),sequence:999,percent:99,stage:"TRANSCRIBING",message:"expired lease"}})).status()).toBe(409);
    await db.query("UPDATE workers SET status='DISABLED' WHERE id=$1",[w.workerId]);await new Promise(r=>setTimeout(r,1100));
    await completeFixtureWorkerProcess(a.workspaceId,job.id,s);dispatch();tick(id);
    expect((await detail(a.c,a.workspaceId,id)).outputs).toHaveLength(2);expect((await jobs(db,id))).toHaveLength(1);
    expect((await db.query("SELECT attempt_count FROM jobs WHERE id=$1",[job.id])).rows[0].attempt_count).toBe(2);
    expect((await wc.post(`/api/worker/jobs/${job.id}/progress`,{data:{...lease(claim),sequence:999,percent:99,stage:"TRANSCRIBING",message:"late worker"}})).status()).toBe(401);
    const result=await decide(a.c,a.workspaceId,id,["APPROVE","REJECT"]);expect(result.run.status).toBe("SUCCEEDED");
    expect(await lifecycle(db,id)).toEqual([{entry_type:"CAPTURE",count:1},{entry_type:"RESERVE",count:1}]);
    await mkdir("data/phase8",{recursive:true});await writeFile("data/phase8/clipper-acceptance.json",JSON.stringify({runId:id,jobs:1,attempts:2,fixtureWorkerProcessRestart:true,reservations:1,captures:1,clips:2,approved:1,rejected:1,parentLedgerMovements:0,realTranscriptions:0,realAnalyzerCalls:0},null,2));
  }finally{
    await fixtureWorker?.stop();if(w)await db.query("UPDATE workers SET status='DISABLED' WHERE id=$1",[w.workerId]);
    if(runId&&!['SUCCEEDED','FAILED','CANCELLED'].includes((await detail(a.c,a.workspaceId,runId)).run.status)){
      await a.c.post(`${root(a.workspaceId)}/runs/${runId}/cancel`);tick(runId);
      await db.query("UPDATE worker_leases SET expires_at=now()-interval '1 second' WHERE job_id IN(SELECT id FROM jobs WHERE workflow_run_id=$1) AND status='ACTIVE'",[runId]);
      dispatch();tick(runId);
    }
    if(wc)await wc.dispose();await a.c.dispose();await db.end();
  }
});
test("workspace substitution is denied, Viewer is read-only and composite lineage constraints reject foreign jobs",async()=>{
  test.setTimeout(150000);
  const a=await setup(),b=await setup(),viewer=await owner(`p8-viewer-${randomUUID()}@example.test`),db=await connect();try{const d=await definition(a.c,a.workspaceId,configuration(a.p.id)),id=await start(a.c,a.workspaceId,d.id);tick(id);const foreignD=await definition(b.c,b.workspaceId,configuration(b.p.id)),foreign=await start(b.c,b.workspaceId,foreignD.id);tick(foreign);const foreignJob=(await jobs(db,foreign))[0];
    await settle(db,(await jobs(db,id))[0].id);tick(id);const output=(await detail(a.c,a.workspaceId,id)).outputs[0];
    for(const ws of [a.workspaceId,b.workspaceId]){
      const path=`/api/workspaces/${ws}/content/${output.contentId}`;
      expect((await b.c.get(path)).status()).toBe(404);
      expect((await b.c.get(`${path}/versions/${output.versionId}/media?kind=preview`)).status()).toBe(404);
      expect((await b.c.post(`${path}/review`,{data:{versionId:output.versionId,expectedRevision:output.reviewRevision,requestKey:randomUUID(),decision:"APPROVE"}})).status()).toBe(404);
    }
    for(const ws of [a.workspaceId,b.workspaceId]){expect((await b.c.get(`${root(ws)}/${d.id}`)).status()).toBe(404);expect((await b.c.get(`${root(ws)}/runs/${id}`)).status()).toBe(404);for(const action of ["pause","resume","cancel","budget"])expect((await b.c.post(`${root(ws)}/runs/${id}/${action}`,{data:{maxTokens:"7000"}})).status()).toBe(404);}
    const uid=(await db.query("SELECT created_by FROM workspaces WHERE id=$1",[viewer.workspaceId])).rows[0].created_by;await db.query("INSERT INTO workspace_members(workspace_id,user_id,role,status) VALUES($1,$2,'VIEWER','ACTIVE')",[a.workspaceId,uid]);await viewer.c.post(`/api/workspaces/${a.workspaceId}/select`);expect((await viewer.c.get(root(a.workspaceId))).status()).toBe(200);expect((await viewer.c.get(`${root(a.workspaceId)}/${d.id}`)).status()).toBe(200);expect((await viewer.c.get(`${root(a.workspaceId)}/runs/${id}`)).status()).toBe(200);
    expect((await viewer.c.post(root(a.workspaceId),{data:{}})).status()).toBe(403);expect((await viewer.c.post(`${root(a.workspaceId)}/estimate`,{data:{}})).status()).toBe(403);expect((await viewer.c.patch(`${root(a.workspaceId)}/${d.id}`,{data:{}})).status()).toBe(403);expect((await viewer.c.post(`${root(a.workspaceId)}/${d.id}/runs`,{data:{idempotencyKey:randomUUID()}})).status()).toBe(403);expect((await viewer.c.post(`${root(a.workspaceId)}/${d.id}/archive`)).status()).toBe(403);for(const action of ["pause","resume","cancel","budget"])expect((await viewer.c.post(`${root(a.workspaceId)}/runs/${id}/${action}`,{data:{maxTokens:"7000"}})).status()).toBe(403);
    const own=(await jobs(db,id))[0];await expect(db.query("INSERT INTO workflow_child_jobs(workspace_id,workflow_run_id,workflow_step_id,job_id,child_key) VALUES($1,$2,$3,$4,'foreign')",[a.workspaceId,id,own.workflow_step_id,foreignJob.id])).rejects.toThrow();await expect(db.query("UPDATE jobs SET workflow_run_id=$1 WHERE id=$2",[id,foreignJob.id])).rejects.toThrow();await expect(db.query("UPDATE workflow_events SET safe_data='{}' WHERE workflow_run_id=$1",[id])).rejects.toThrow();
  }finally{await a.c.dispose();await b.c.dispose();await viewer.c.dispose();await db.end();}
});
