import {readFile} from "node:fs/promises";
import {transaction,pool} from "../src/lib/db";
import {integer,canonicalHash} from "../src/lib/billing-core";
import {audit,isUuid} from "../src/lib/core";
import {allowlistedOperator} from '../src/lib/platform-access';
// Operator-only catalog configuration. Customer roles have no route to this command.
async function main(){const [file,operatorId,reason,key]=process.argv.slice(2);if(process.env.ENABLE_BILLING_SUPPORT_CLI!=="1"||!file||!isUuid(operatorId||"")||!reason||reason.length<5||! /^[A-Za-z0-9:_-]{8,160}$/.test(key||""))throw new Error('Usage: billing-catalog.ts config.json operatorUserId "reason" stableKey (requires support CLI flag)');
 const raw=await readFile(file,'utf8');if(raw.length>32768)throw new Error('Catalog input exceeds limit');const cfg=JSON.parse(raw) as {realm:string;prices:{operation:string;version:number;label:string;rules:Record<string,unknown>}[];packages:{code:string;version:number;label:string;tokenAmount:string;fiatMinor:string;currency:string}[]};if(!['TEST','PRODUCTION'].includes(cfg.realm)||cfg.realm==='TEST'&&process.env.APP_ENV!=='local'||!Array.isArray(cfg.prices)||!Array.isArray(cfg.packages)||cfg.prices.length>3||cfg.packages.length>30)throw new Error('Invalid catalog config');
 await transaction(async db=>{const actor=(await db.query<{id:string;email:string}>("SELECT id,email FROM users WHERE id=$1 AND status='ACTIVE'",[operatorId])).rows[0];if(!actor||!allowlistedOperator(actor))throw new Error('Allowlisted active operator required');for(const price of cfg.prices){if(!['AI_VIDEO','CLIPPER','CLIPPER_VARIATION'].includes(price.operation)||!Number.isInteger(price.version)||price.version<1||!price.label||price.label.length>160||cfg.realm==='TEST'&&!price.label.startsWith('TEST'))throw new Error('Invalid immutable price version');if(price.operation!=='CLIPPER_VARIATION')integer(price.rules.base);if(price.operation==='AI_VIDEO'){if(price.rules.tier!=='QUALITY')throw new Error('Unsupported tier');integer(price.rules.perSecond,true);}else if(price.operation==='CLIPPER_VARIATION'){if(price.rules.policyVersion!=='clipper-visual-variation-v1'||price.rules.approval!=='INTERNAL_BETA'||!price.label.includes('INTERNAL BETA')||typeof price.rules.maxDurationSeconds!=='number'||!Number.isFinite(price.rules.maxDurationSeconds)||price.rules.maxDurationSeconds<1||price.rules.maxDurationSeconds>90)throw new Error('Internal-beta variation rules required');integer(price.rules.perRender,true);}else{integer(price.rules.perClip);integer(price.rules.captions);if(BigInt(String(price.rules.base))<=BigInt(0))throw new Error('Clipper base must be positive');}
 const c=(await db.query<{id:string}>("INSERT INTO price_catalogs(operation,realm) VALUES($1,$2) ON CONFLICT(operation,realm) DO UPDATE SET operation=excluded.operation RETURNING id",[price.operation,cfg.realm])).rows[0];const previous=(await db.query<{id:string;label:string;rules:Record<string,unknown>}>("SELECT id,label,rules FROM price_versions WHERE catalog_id=$1 AND version_number=$2",[c.id,price.version])).rows[0];if(previous&&(previous.label!==price.label||canonicalHash(previous.rules)!==canonicalHash(price.rules)))throw new Error('Existing price version differs; use a new version');const v=previous||(await db.query<{id:string}>("INSERT INTO price_versions(catalog_id,version_number,label,rules) VALUES($1,$2,$3,$4::jsonb) RETURNING id",[c.id,price.version,price.label,JSON.stringify(price.rules)])).rows[0];await db.query("UPDATE price_catalogs SET active_version_id=$1 WHERE id=$2",[v.id,c.id]);}
 for(const pack of cfg.packages){if(! /^[a-z0-9-]{1,64}$/.test(pack.code)||!Number.isInteger(pack.version)||pack.version<1||!pack.label||pack.label.length>160||!['IDR','PHP','VND','THB','SGD','MYR','USD'].includes(pack.currency)||cfg.realm==='TEST'&&!pack.label.startsWith('TEST'))throw new Error('Invalid package version');integer(pack.tokenAmount,true);integer(pack.fiatMinor,true);const c=(await db.query<{id:string}>("INSERT INTO token_packages(code,realm) VALUES($1,$2) ON CONFLICT(code,realm) DO UPDATE SET code=excluded.code RETURNING id",[pack.code,cfg.realm])).rows[0];const previous=(await db.query<{id:string;label:string;token_amount:string;fiat_minor:string;currency:string}>("SELECT * FROM token_package_versions WHERE package_id=$1 AND version_number=$2",[c.id,pack.version])).rows[0];if(previous&&(previous.label!==pack.label||previous.token_amount!==pack.tokenAmount||previous.fiat_minor!==pack.fiatMinor||previous.currency!==pack.currency))throw new Error('Existing package differs; use a new version');const v=previous||(await db.query<{id:string}>("INSERT INTO token_package_versions(package_id,version_number,label,token_amount,fiat_minor,currency) VALUES($1,$2,$3,$4,$5,$6) RETURNING id",[c.id,pack.version,pack.label,pack.tokenAmount,pack.fiatMinor,pack.currency])).rows[0];await db.query("UPDATE token_packages SET active_version_id=$1 WHERE id=$2",[v.id,c.id]);}
 await audit(db,{actorUserId:operatorId,type:'BILLING_CATALOG_CONFIGURED',targetType:'catalog',metadata:{realm:cfg.realm,reason,requestKey:key,configHash:canonicalHash(cfg)}});});console.log('Catalog versions configured and activated.');}
main().catch(()=>{console.error(JSON.stringify({code:'CATALOG_CONFIGURATION_REJECTED',detail:'Check operator authorization, input bounds, and immutable version identity.'}));process.exitCode=1;}).finally(()=>pool().end());
