import "server-only";
import type {Session} from "./auth";
import {query,transaction} from "./db";
import {AppError,isUuid} from "./core";
import {requireActiveWorkspace} from "./products";
import {requireRole} from "./workspaces";
import {billingRealm} from "./billing-core";
import {createPaymentRecord,safePayment,type PaymentRow,processPaymentEvent} from "./payments-core";
import {fakePaymentsEnabled,paymentProvider} from "./payment-providers";
export async function billingSummary(session:Session,workspaceId:string){await requireActiveWorkspace(session,workspaceId,"workspace:read");const wallet=(await query<{available_tokens:string;reserved_tokens:string}>("SELECT available_tokens,reserved_tokens FROM workspace_wallets WHERE workspace_id=$1",[workspaceId])).rows[0];return {availableTokens:wallet.available_tokens,reservedTokens:wallet.reserved_tokens,test:billingRealm()==="TEST"};}
export async function packages(session:Session,workspaceId:string){await requireActiveWorkspace(session,workspaceId,"billing:manage");return (await query<{id:string;label:string;token_amount:string;fiat_minor:string;currency:string}>("SELECT v.id,v.label,v.token_amount,v.fiat_minor,v.currency FROM token_packages p JOIN token_package_versions v ON v.id=p.active_version_id AND v.package_id=p.id WHERE p.realm=$1 ORDER BY v.token_amount,v.id",[billingRealm()])).rows;}
export async function history(session:Session,workspaceId:string,cursor?:string){await requireActiveWorkspace(session,workspaceId,"workspace:read");let date:string|null=null,id:string|null=null;if(cursor){try{const parsed=JSON.parse(Buffer.from(cursor,"base64url").toString("utf8"));date=parsed.date;id=parsed.id;if(typeof date!=="string"||!isUuid(String(id))||!Number.isFinite(Date.parse(date)))throw new Error();}catch{throw new AppError(400,"Invalid history cursor.");}}
 const rows=(await query<{id:string;entry_type:string;available_delta:string;reserved_delta:string;job_id:string|null;created_at:Date;cursor_time:string}>("SELECT id,entry_type,available_delta,reserved_delta,job_id,created_at,to_char(created_at AT TIME ZONE 'UTC','YYYY-MM-DD\"T\"HH24:MI:SS.US\"Z\"') AS cursor_time FROM token_ledger_entries WHERE workspace_id=$1 AND ($2::timestamptz IS NULL OR (created_at,id)<($2::timestamptz,$3::uuid)) ORDER BY created_at DESC,id DESC LIMIT 51",[workspaceId,date,id])).rows;const visible=rows.slice(0,50),last=visible.at(-1);return {entries:visible,nextCursor:rows.length>50&&last?Buffer.from(JSON.stringify({date:last.cursor_time,id:last.id})).toString("base64url"):null};}
export async function usage(session:Session,workspaceId:string){await requireActiveWorkspace(session,workspaceId,"workspace:read");return (await query<{job_id:string;type:string;token_amount:string;status:string;created_at:Date}>("SELECT b.job_id,j.type,b.token_amount,b.status,b.created_at FROM job_billing b JOIN jobs j ON j.id=b.job_id AND j.workspace_id=b.workspace_id WHERE b.workspace_id=$1 ORDER BY b.created_at DESC,b.job_id DESC LIMIT 50",[workspaceId])).rows;}
export async function paymentHistory(session:Session,workspaceId:string,cursor?:string){await requireActiveWorkspace(session,workspaceId,"billing:manage");let date:string|null=null,id:string|null=null;if(cursor){try{const parsed=JSON.parse(Buffer.from(cursor,"base64url").toString("utf8"));date=parsed.date;id=parsed.id;if(typeof date!=="string"||!isUuid(String(id))||!Number.isFinite(Date.parse(date)))throw new Error();}catch{throw new AppError(400,"Invalid payment cursor.");}}const rows=(await query<PaymentRow&{cursor_time:string}>("SELECT *,to_char(created_at AT TIME ZONE 'UTC','YYYY-MM-DD\"T\"HH24:MI:SS.US\"Z\"') AS cursor_time FROM payments WHERE workspace_id=$1 AND ($2::timestamptz IS NULL OR (created_at,id)<($2::timestamptz,$3::uuid)) ORDER BY created_at DESC,id DESC LIMIT 51",[workspaceId,date,id])).rows,visible=rows.slice(0,50),last=visible.at(-1);return {payments:visible.map(safePayment),nextCursor:rows.length>50&&last?Buffer.from(JSON.stringify({date:last.cursor_time,id:last.id})).toString("base64url"):null};}
export async function customerCreatePayment(session:Session,workspaceId:string,raw:Record<string,unknown>){await requireActiveWorkspace(session,workspaceId,"billing:manage");return createPaymentRecord({workspaceId,userId:session.userId,email:session.email,packageVersionId:String(raw.packageVersionId||""),key:String(raw.idempotencyKey||"")},db=>requireRole(session.userId,workspaceId,"billing:manage",db));}
export async function simulatePayment(session:Session,workspaceId:string,id:string,raw:Record<string,unknown>){if(!fakePaymentsEnabled())throw new AppError(404,"Not found.");await requireActiveWorkspace(session,workspaceId,"billing:manage");if(!isUuid(id)||!['PENDING','PAID','FAILED','EXPIRED','REFUNDED'].includes(String(raw.status)))throw new AppError(400,"Invalid simulation.");const p=await transaction(async db=>{await requireRole(session.userId,workspaceId,"billing:manage",db);const p=(await db.query<PaymentRow>("SELECT * FROM payments WHERE workspace_id=$1 AND id=$2 AND provider='fake' FOR UPDATE",[workspaceId,id])).rows[0];if(!p?.external_id)throw new AppError(404,"Simulation payment not found.");await db.query("UPDATE fake_payment_states SET status=$1,updated_at=now() WHERE external_id=$2",[raw.status,p.external_id]);return p;});
 if(raw.deliverWebhook!==false)await processPaymentEvent("fake",await paymentProvider("fake").getPayment(p.external_id!));return {simulation:true};}
