import {query,transaction} from "./db";
import {issue,settlementBatch} from "./billing-core";
import {paymentReconcileBatch} from "./payments-core";
export async function reconciliationReport(repair=false,recordIssues=repair){if(repair){await settlementBatch(100);await paymentReconcileBatch(50);}const checks:Record<string,string>={
 WALLET_LEDGER_MISMATCH:`SELECT w.billing_account_id FROM billing_account_wallets w LEFT JOIN token_ledger_entries l ON l.billing_account_id=w.billing_account_id GROUP BY w.billing_account_id,w.available_tokens,w.reserved_tokens HAVING w.available_tokens<>coalesce(sum(l.available_delta),0) OR w.reserved_tokens<>coalesce(sum(l.reserved_delta),0)`,
 RESERVED_JOB_MISMATCH:`SELECT w.billing_account_id FROM billing_account_wallets w WHERE w.reserved_tokens<>coalesce((SELECT sum(b.token_amount) FROM job_billing b WHERE b.billing_account_id=w.billing_account_id AND b.status='RESERVED'),0)+coalesce((SELECT sum(o.token_amount) FROM outreach_campaign_billing o WHERE o.billing_account_id=w.billing_account_id AND o.status='RESERVED'),0)`,
 OUTREACH_TERMINAL_MISSING_SETTLEMENT:`SELECT b.workspace_id,b.billing_account_id,b.campaign_id FROM outreach_campaign_billing b JOIN outreach_campaigns c ON c.id=b.campaign_id WHERE b.status='RESERVED' AND c.state IN('COMPLETED','COMPLETED_WITH_ERRORS','FAILED','CANCELLED')`,
 OUTREACH_SETTLEMENT_MISMATCH:`SELECT b.workspace_id,b.billing_account_id,b.campaign_id FROM outreach_campaign_billing b JOIN workspaces w ON w.id=b.workspace_id WHERE b.billing_account_id<>w.billing_account_id OR (b.status='SETTLED' AND (b.captured_tokens<>(SELECT count(*)*b.per_send FROM outreach_deliveries d WHERE d.campaign_id=b.campaign_id AND d.state='SENT') OR b.captured_tokens+b.released_tokens<>b.token_amount OR EXISTS(SELECT 1 FROM outreach_deliveries d WHERE d.campaign_id=b.campaign_id AND d.state IN('PENDING','DISPATCHING','RETRYABLE','DELIVERY_UNKNOWN'))))`,
 TERMINAL_MISSING_SETTLEMENT:`SELECT b.workspace_id,b.job_id FROM job_billing b JOIN jobs j ON j.id=b.job_id WHERE b.status='RESERVED' AND j.status IN('SUCCEEDED','FAILED','CANCELLED')`,
 CAPTURE_WITHOUT_SUCCESS:`SELECT b.workspace_id,b.job_id FROM job_billing b JOIN jobs j ON j.id=b.job_id WHERE b.capture_ledger_id IS NOT NULL AND j.status<>'SUCCEEDED'`,
 PURCHASE_WITHOUT_PAID:`SELECT p.workspace_id,p.id AS payment_id FROM payments p JOIN token_ledger_entries l ON l.payment_id=p.id AND l.entry_type='PURCHASE' WHERE p.status NOT IN('PAID','REFUNDED')`,
 PAID_WITHOUT_PURCHASE:`SELECT p.workspace_id,p.id AS payment_id FROM payments p WHERE p.status IN('PAID','REFUNDED') AND NOT EXISTS(SELECT 1 FROM token_ledger_entries l WHERE l.payment_id=p.id AND l.entry_type='PURCHASE')`,
 PACKAGE_PAYMENT_MISMATCH:`SELECT p.workspace_id,p.id AS payment_id FROM payments p JOIN token_package_versions v ON v.id=p.package_version_id WHERE (p.token_amount,p.fiat_minor,p.currency) IS DISTINCT FROM(v.token_amount,v.fiat_minor,v.currency)`,
 LEDGER_ACCOUNT_MISMATCH:`SELECT l.workspace_id,l.billing_account_id,l.job_id,l.payment_id FROM token_ledger_entries l JOIN workspaces w ON w.id=l.workspace_id LEFT JOIN job_billing b ON b.job_id=l.job_id LEFT JOIN payments p ON p.id=l.payment_id WHERE l.billing_account_id<>w.billing_account_id OR (b.job_id IS NOT NULL AND (b.workspace_id,b.billing_account_id) IS DISTINCT FROM(l.workspace_id,l.billing_account_id)) OR (p.id IS NOT NULL AND (p.workspace_id,p.billing_account_id) IS DISTINCT FROM(l.workspace_id,l.billing_account_id))`,
 QUOTE_ACCOUNT_MISMATCH:`SELECT b.workspace_id,b.billing_account_id,b.job_id FROM job_billing b JOIN billing_quotes q ON q.id=b.quote_id JOIN workspaces w ON w.id=b.workspace_id JOIN jobs j ON j.id=b.job_id WHERE (b.workspace_id,b.billing_account_id,b.price_version_id,b.token_amount) IS DISTINCT FROM(q.workspace_id,q.billing_account_id,q.price_version_id,q.token_amount) OR b.billing_account_id<>w.billing_account_id OR j.workspace_id<>b.workspace_id OR (q.input_hash,q.request_hash) IS DISTINCT FROM(j.input_hash,j.client_request_hash)`,
 PAYMENT_ACCOUNT_MISMATCH:`SELECT p.workspace_id,p.billing_account_id,p.id AS payment_id FROM payments p JOIN workspaces w ON w.id=p.workspace_id WHERE p.billing_account_id<>w.billing_account_id`,
 REFUND_MISMATCH:`SELECT b.workspace_id,b.billing_account_id,b.job_id FROM job_billing b LEFT JOIN token_ledger_entries l ON l.id=b.refund_ledger_id WHERE b.status='REFUNDED' AND (l.id IS NULL OR l.entry_type<>'REFUND' OR l.available_delta<>b.token_amount OR l.reserved_delta<>0 OR l.billing_account_id<>b.billing_account_id OR l.workspace_id<>b.workspace_id OR l.job_id<>b.job_id) UNION SELECT l.workspace_id,l.billing_account_id,l.job_id FROM token_ledger_entries l LEFT JOIN job_billing b ON b.job_id=l.job_id WHERE l.entry_type='REFUND' AND (b.job_id IS NULL OR b.status<>'REFUNDED' OR b.refund_ledger_id IS DISTINCT FROM l.id OR l.available_delta<>b.token_amount OR l.reserved_delta<>0 OR l.billing_account_id<>b.billing_account_id OR l.workspace_id<>b.workspace_id)`,
 LATE_SUCCESS_AFTER_RELEASE:`SELECT b.workspace_id,b.job_id FROM job_billing b JOIN jobs j ON j.id=b.job_id WHERE b.status='RELEASED' AND j.status='SUCCEEDED'`,
 };
 const result:Record<string,unknown[]>={};for(const [code,sql] of Object.entries(checks)){const rows=(await query<{workspace_id?:string;billing_account_id?:string;job_id?:string;payment_id?:string}>(sql+' LIMIT 100')).rows;result[code]=rows;if(recordIssues)for(const r of rows)await transaction(db=>issue(db,code,r.workspace_id||null,r.job_id||null,r.payment_id||null,"",r.billing_account_id||null));}return result;
}
