import "server-only";
import {query,transaction,type DbClient} from "./db";
import {AppError,audit,isUuid} from "./core";
import {requireActiveWorkspace} from "./products";
import {requireRole} from "./workspaces";
import {objectStorage} from "./storage";
import {contentFilename,contentFilters,reviewRequest,type ContentListOptions} from "./content-core";
import type {Session} from "./auth";
import type {FrozenProduct} from "./job-core";

type Item={id:string;workspace_id:string;type:string;status:string;title:string;product_name:string|null;source_filename:string|null;current_version_id:string;product_id:string|null;source_asset_id:string|null;origin_job_id:string;review_revision:number;created_at:Date;archived_at:Date|null};
type Version={id:string;workspace_id:string;content_item_id:string;version_number:number;artifact_id:string;job_id:string;mime_type:string;byte_size:string;sha256:string;duration_seconds:number|null;width:number|null;height:number|null;product_id:string|null;product_version_id:string|null;product_rule_version_id:string|null;source_asset_id:string|null;transcript_artifact_id:string|null;plan_artifact_id:string|null;metadata:Record<string,unknown>;created_at:Date};
export async function scopedContent(db:DbClient,workspaceId:string,id:string,lock=false){if(!isUuid(id))throw new AppError(404,"Content not found.");const r=await db.query<Item>(`SELECT * FROM content_items WHERE workspace_id=$1 AND id=$2 ${lock?"FOR UPDATE":""}`,[workspaceId,id]);if(!r.rows[0])throw new AppError(404,"Content not found.");return r.rows[0];}
async function scopedVersion(db:DbClient,workspaceId:string,id:string,versionId:string){if(!isUuid(versionId))throw new AppError(404,"Content version not found.");const r=await db.query<Version>("SELECT * FROM content_versions WHERE workspace_id=$1 AND content_item_id=$2 AND id=$3",[workspaceId,id,versionId]);if(!r.rows[0])throw new AppError(404,"Content version not found.");return r.rows[0];}
export async function contentList(session:Session,workspaceId:string,options:ContentListOptions={}){
  await requireActiveWorkspace(session,workspaceId,"workspace:read");const f=contentFilters(options),values=[workspaceId,f.type,f.status,f.productId,f.search,f.pattern];
  const where=`i.workspace_id=$1 AND ($2='ALL' OR i.type=$2) AND (($3='ACTIVE' AND i.status<>'ARCHIVED') OR $3='ALL' OR i.status=$3) AND ($4='' OR i.product_id::text=$4)
    AND ($5='' OR i.title ILIKE $6 ESCAPE '\\' OR coalesce(i.product_name,'') ILIKE $6 ESCAPE '\\' OR coalesce(i.source_filename,'') ILIKE $6 ESCAPE '\\' OR i.type ILIKE $6 ESCAPE '\\')`;
  const [rows,total]=await Promise.all([
    query<{id:string;type:string;status:string;title:string;productName:string|null;sourceFilename:string|null;versionId:string;durationSeconds:number|null;createdAt:Date;posterReady:boolean}>(`SELECT i.id,i.type,i.status,i.title,i.product_name AS "productName",i.source_filename AS "sourceFilename",v.id AS "versionId",v.duration_seconds AS "durationSeconds",i.created_at AS "createdAt",coalesce(p.status='READY',false) AS "posterReady" FROM content_items i
      JOIN content_versions v ON v.workspace_id=i.workspace_id AND v.content_item_id=i.id AND v.id=i.current_version_id LEFT JOIN content_posters p ON p.content_version_id=v.id WHERE ${where} ORDER BY i.created_at DESC,i.id DESC LIMIT $7 OFFSET $8`,[...values,f.pageSize,(f.page-1)*f.pageSize]),
    query<{count:string}>(`SELECT count(*) FROM content_items i WHERE ${where}`,values)
  ]);return {items:rows.rows,total:Number(total.rows[0].count),page:f.page,pageSize:f.pageSize};
}
export async function contentCounts(session:Session,workspaceId:string){await requireActiveWorkspace(session,workspaceId,"workspace:read");const r=await query<{assets:string;pending:string;approved:string;rejected:string}>(`SELECT count(*) FILTER(WHERE status<>'ARCHIVED') AS assets,count(*) FILTER(WHERE status='PENDING_REVIEW') AS pending,count(*) FILTER(WHERE status='APPROVED') AS approved,count(*) FILTER(WHERE status='REJECTED') AS rejected FROM content_items WHERE workspace_id=$1`,[workspaceId]);return Object.fromEntries(Object.entries(r.rows[0]).map(([k,v])=>[k,Number(v)])) as {assets:number;pending:number;approved:number;rejected:number};}
export async function contentDetail(session:Session,workspaceId:string,id:string){
  await requireActiveWorkspace(session,workspaceId,"workspace:read");const item=await scopedContent({query},workspaceId,id),v=await scopedVersion({query},workspaceId,id,item.current_version_id);
  const job=(await query<{type:string;input_snapshot:{product?:FrozenProduct;goal?:string}}>("SELECT type,input_snapshot FROM jobs WHERE workspace_id=$1 AND id=$2",[workspaceId,v.job_id])).rows[0];
  const [reviews,relations,refs,versions,poster]=await Promise.all([
    query<{id:string;versionId:string;decision:string;reasonCategory:string|null;reasonText:string|null;reviewer:string;createdAt:Date;revision:number}>(`SELECT d.id,d.content_version_id AS "versionId",d.decision,d.reason_category AS "reasonCategory",d.reason_text AS "reasonText",u.display_name AS reviewer,d.created_at AS "createdAt",d.review_revision AS revision FROM review_decisions d JOIN users u ON u.id=d.reviewer_user_id WHERE d.workspace_id=$1 AND d.content_item_id=$2 ORDER BY d.review_revision DESC LIMIT 100`,[workspaceId,id]),
    query<{id:string;relationType:string;contentId:string|null;title:string|null;direction:string}>(`SELECT r.id,r.relation_type AS "relationType",CASE WHEN r.content_item_id=$2 THEN r.parent_content_id ELSE r.content_item_id END AS "contentId",c.title,CASE WHEN r.content_item_id=$2 THEN 'PARENT' ELSE 'VARIANT' END AS direction FROM content_relations r LEFT JOIN content_items c ON c.workspace_id=r.workspace_id AND c.id=CASE WHEN r.content_item_id=$2 THEN r.parent_content_id ELSE r.content_item_id END WHERE r.workspace_id=$1 AND (r.content_item_id=$2 OR r.parent_content_id=$2) ORDER BY r.created_at,r.id LIMIT 100`,[workspaceId,id]),
    query<{assetVersionId:string;purpose:string;mimeType:string}>(`SELECT r.asset_version_id AS "assetVersionId",r.purpose,a.mime_type AS "mimeType" FROM content_reference_assets r JOIN asset_versions a ON a.workspace_id=r.workspace_id AND a.product_id=r.product_id AND a.asset_id=r.asset_id AND a.id=r.asset_version_id WHERE r.workspace_id=$1 AND r.content_item_id=$2 AND r.content_version_id=$3 ORDER BY r.purpose,r.asset_version_id`,[workspaceId,id,v.id]),
    query<{id:string;versionNumber:number;createdAt:Date}>("SELECT id,version_number AS \"versionNumber\",created_at AS \"createdAt\" FROM content_versions WHERE workspace_id=$1 AND content_item_id=$2 ORDER BY version_number DESC LIMIT 100",[workspaceId,id]),
    query<{status:string}>("SELECT status FROM content_posters WHERE workspace_id=$1 AND content_item_id=$2 AND content_version_id=$3",[workspaceId,id,v.id])
  ]);
  const product=job.input_snapshot.product,clip=item.type==="CLIP"?{start:Number(v.metadata.start),end:Number(v.metadata.end),hook:String(v.metadata.hook),reason:String(v.metadata.reason),score:Number(v.metadata.score),tags:v.metadata.tags as string[]}:null;
  return {id:item.id,type:item.type,status:item.status,title:item.title,reviewRevision:item.review_revision,createdAt:item.created_at,archivedAt:item.archived_at,
    version:{id:v.id,number:v.version_number,artifactId:v.artifact_id,byteSize:Number(v.byte_size),sha256:v.sha256,durationSeconds:v.duration_seconds,width:v.width,height:v.height,transcriptArtifactId:v.transcript_artifact_id,planArtifactId:v.plan_artifact_id},
    originJob:{id:item.origin_job_id,type:item.type==="AI_VIDEO"?"AI_VIDEO":"CLIPPER"},job:{id:v.job_id,type:job.type},product:product?{id:product.id,versionId:product.versionId,versionNumber:product.versionNumber,ruleVersionId:product.ruleVersionId,ruleVersionNumber:product.ruleVersionNumber,information:product.information,rules:product.rules}:null,
    source:item.source_asset_id?{id:item.source_asset_id,filename:item.source_filename,sha256:String(v.metadata.sourceSha256)}:null,clip,references:refs.rows,reviews:reviews.rows,relations:relations.rows,versions:versions.rows,posterStatus:poster.rows[0]?.status||"PENDING"};
}
export type ContentDetail=Awaited<ReturnType<typeof contentDetail>>;
export async function contentMedia(session:Session,workspaceId:string,id:string,versionId:string,kind:"preview"|"download"|"poster"|"source"|"reference",assetVersionId?:string){
  await requireActiveWorkspace(session,workspaceId,"workspace:read");const item=await scopedContent({query},workspaceId,id),v=await scopedVersion({query},workspaceId,id,versionId),storage=objectStorage();
  let key:string,filename=contentFilename(item.title,item.type);
  if(kind==="poster"){const p=(await query<{storage_key:string}>("SELECT storage_key FROM content_posters WHERE workspace_id=$1 AND content_item_id=$2 AND content_version_id=$3 AND status='READY'",[workspaceId,id,versionId])).rows[0];if(!p)throw new AppError(404,"Poster is not ready.");key=p.storage_key;filename="preview.jpg";}
  else if(kind==="source"){const s=(await query<{storage_key:string;original_filename:string;sha256:string}>("SELECT storage_key,original_filename,sha256 FROM source_assets WHERE workspace_id=$1 AND id=$2 AND status IN ('VERIFIED','ARCHIVED')",[workspaceId,v.source_asset_id])).rows[0];if(!s||s.sha256!==v.metadata.sourceSha256)throw new AppError(404,"Source is unavailable.");key=s.storage_key;filename=s.original_filename;}
  else if(kind==="reference"){
    if(!assetVersionId||!isUuid(assetVersionId))throw new AppError(404,"Reference not found.");
    const r=(await query<{storage_key:string}>(`SELECT a.storage_key FROM content_reference_assets r JOIN asset_versions a ON a.workspace_id=r.workspace_id AND a.product_id=r.product_id AND a.asset_id=r.asset_id AND a.id=r.asset_version_id WHERE r.workspace_id=$1 AND r.content_item_id=$2 AND r.content_version_id=$3 AND r.asset_version_id=$4 AND a.status='READY'`,[workspaceId,id,versionId,assetVersionId])).rows[0];if(!r)throw new AppError(404,"Reference not found.");key=r.storage_key;filename="product-reference";
  }else{
    if(kind==="download"&&item.status==="ARCHIVED")throw new AppError(409,"Archived Content can be previewed; download it from its historical job if needed.");
    const a=(await query<{storage_key:string;sha256:string;byte_size:string}>(`SELECT a.storage_key,a.sha256,a.byte_size FROM job_artifacts a JOIN jobs j ON j.workspace_id=a.workspace_id AND j.id=a.job_id WHERE a.workspace_id=$1 AND a.job_id=$2 AND a.id=$3 AND a.status='READY' AND j.status='SUCCEEDED' AND j.result->'artifactIds' ? a.id::text`,[workspaceId,v.job_id,v.artifact_id])).rows[0];if(!a||a.sha256!==v.sha256||a.byte_size!==v.byte_size)throw new AppError(404,"Content media is unavailable.");key=a.storage_key;
  }
  if(!await storage.head(key))throw new AppError(404,"Content media is unavailable.");return {url:await storage.issueDownload(key,filename,300,kind==="download"),expiresInSeconds:300};
}
export async function reviewContent(session:Session,workspaceId:string,id:string,raw:Record<string,unknown>){await requireActiveWorkspace(session,workspaceId,"future:edit");return transaction(async db=>{
  await requireRole(session.userId,workspaceId,"future:edit",db);const item=await scopedContent(db,workspaceId,id,true),request=reviewRequest(raw,!!item.product_id);
  const prior=(await db.query<{id:string;request_hash:string}>("SELECT id,request_hash FROM review_decisions WHERE workspace_id=$1 AND content_item_id=$2 AND request_key=$3",[workspaceId,id,request.requestKey])).rows[0];
  if(prior){if(prior.request_hash!==request.requestHash)throw new AppError(409,"Review request key was already used differently.");return {decisionId:prior.id,status:item.status,revision:item.review_revision,duplicate:true};}
  if(item.status==="ARCHIVED")throw new AppError(409,"Archived Content cannot be reviewed.");
  if(item.current_version_id!==request.versionId||item.review_revision!==request.expectedRevision)throw new AppError(409,"Content changed. Refresh before reviewing.");
  const revision=item.review_revision+1,status=request.decision==="APPROVE"?"APPROVED":"REJECTED";
  const d=await db.query<{id:string}>("INSERT INTO review_decisions(workspace_id,content_item_id,content_version_id,reviewer_user_id,decision,reason_category,reason_text,request_key,request_hash,review_revision) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10) RETURNING id",[workspaceId,id,request.versionId,session.userId,request.decision,request.reasonCategory,request.reasonText,request.requestKey,request.requestHash,revision]);
  await db.query("UPDATE content_items SET status=$1,review_revision=$2,updated_at=now() WHERE id=$3",[status,revision,id]);
  await audit(db,{workspaceId,actorUserId:session.userId,type:request.decision==="APPROVE"?"CONTENT_APPROVED":"CONTENT_REJECTED",targetType:"content",targetId:id,metadata:{versionId:request.versionId,decisionId:d.rows[0].id,category:request.reasonCategory}});return {decisionId:d.rows[0].id,status,revision,duplicate:false};
});}
export async function archiveContent(session:Session,workspaceId:string,id:string){await requireActiveWorkspace(session,workspaceId,"future:edit");return transaction(async db=>{await requireRole(session.userId,workspaceId,"future:edit",db);const item=await scopedContent(db,workspaceId,id,true);if(item.status==="ARCHIVED")return {status:"ARCHIVED"};await db.query("UPDATE content_items SET status='ARCHIVED',archived_at=now(),updated_at=now() WHERE id=$1",[id]);await audit(db,{workspaceId,actorUserId:session.userId,type:"CONTENT_ARCHIVED",targetType:"content",targetId:id});return {status:"ARCHIVED"};});}
export async function createVariantRelation(session:Session,workspaceId:string,id:string,raw:Record<string,unknown>){await requireActiveWorkspace(session,workspaceId,"future:edit");await scopedContent({query},workspaceId,id);if(raw.relationType!=="VARIANT_OF"||typeof raw.parentContentId!=="string"||!isUuid(raw.parentContentId)||id===raw.parentContentId)throw new AppError(400,"Choose another Content item as parent.");
  try{return await transaction(async db=>{await requireRole(session.userId,workspaceId,"future:edit",db);await db.query("SELECT pg_advisory_xact_lock(hashtextextended($1,6))",[workspaceId]);const item=await scopedContent(db,workspaceId,id),parent=await scopedContent(db,workspaceId,raw.parentContentId as string);if(item.status==="ARCHIVED"||parent.status==="ARCHIVED")throw new AppError(409,"Register variants using active Content.");const existing=(await db.query<{parent_content_id:string}>("SELECT parent_content_id FROM content_relations WHERE workspace_id=$1 AND content_item_id=$2 AND relation_type='VARIANT_OF'",[workspaceId,id])).rows[0];if(existing&&existing.parent_content_id!==parent.id)throw new AppError(409,"This item already has a variant parent.");const r=await db.query<{id:string}>("INSERT INTO content_relations(workspace_id,content_item_id,relation_type,parent_content_id,created_by) VALUES($1,$2,'VARIANT_OF',$3,$4) ON CONFLICT DO NOTHING RETURNING id",[workspaceId,id,parent.id,session.userId]);if(r.rows[0])await audit(db,{workspaceId,actorUserId:session.userId,type:"CONTENT_RELATION_CREATED",targetType:"content",targetId:id,metadata:{parentContentId:parent.id}});return {created:!!r.rowCount};});}catch(error){if(error&&typeof error==="object"&&"code"in error&&error.code==="23514")throw new AppError(409,"Variant would create a cycle or exceed the lineage depth limit.");throw error;}}
export async function retryContentPoster(session:Session,workspaceId:string,id:string,versionId:string){await requireActiveWorkspace(session,workspaceId,"future:edit");return transaction(async db=>{await requireRole(session.userId,workspaceId,"future:edit",db);await scopedContent(db,workspaceId,id);await scopedVersion(db,workspaceId,id,versionId);await db.query("UPDATE content_posters SET status='PENDING',attempts=0,available_at=now(),last_error_code=NULL WHERE workspace_id=$1 AND content_item_id=$2 AND content_version_id=$3 AND status='FAILED'",[workspaceId,id,versionId]);return {queued:true};});}
export {isContentApproved} from "./content-eligibility";
export async function jobPublishedContent(workspaceId:string,jobId:string){const r=await query<{id:string;title:string}>("SELECT DISTINCT i.id,i.title FROM content_items i JOIN content_versions v ON v.workspace_id=i.workspace_id AND v.content_item_id=i.id WHERE i.workspace_id=$1 AND v.job_id=$2 ORDER BY i.id",[workspaceId,jobId]);return r.rows;}
export async function contentProductOptions(session:Session,workspaceId:string){await requireActiveWorkspace(session,workspaceId,"workspace:read");return (await query<{id:string;name:string}>(`SELECT id,name FROM (SELECT DISTINCT ON (product_id) product_id AS id,product_name AS name FROM content_items WHERE workspace_id=$1 AND product_id IS NOT NULL ORDER BY product_id,created_at DESC,id DESC) p ORDER BY name,id LIMIT 200`,[workspaceId])).rows;}
