export const GENERIC_REJECTION_CATEGORIES=["BAD_CLIP_SELECTION","CAPTION_ISSUE","QUALITY_ISSUE","OTHER"] as const;
export const PRODUCT_REJECTION_CATEGORIES=["LOGO_WRONG","PACKAGING_TEXT_WRONG","PRODUCT_SHAPE_WRONG","CAP_PUMP_WRONG","COLOR_MATERIAL_WRONG","APPLICATION_METHOD_WRONG",...GENERIC_REJECTION_CATEGORIES] as const;
