import {createHash,timingSafeEqual} from 'node:crypto';
import {readFile,readdir} from 'node:fs/promises';
import {join} from 'node:path';
import {query,transaction} from './db';
import {AppError,audit,isUuid} from './core';
import type {Session} from './auth';
import {configurationChecks,externalConfiguration,featureEnabled,boundedSetting} from './operational-config';
import {serviceFreshness} from './service-state';
import {storageReachable,objectStorage,storageClient,storageBucket} from './storage';
import {ListMultipartUploadsCommand} from '@aws-sdk/client-s3';
import {workspaceLimits,workspaceStorageUsage,workspaceQuotaLock,LIMIT_DEFAULTS} from './operational-limits';
import {reconciliationReport} from './billing-reconciliation';
import {settleJob} from './billing-core';
import {publishJobContent} from './content-publication';
import {paymentProvider} from './payment-providers';
import {processPaymentEvent} from './payments-core';

export function isOperator(session:Pick<Session,'userId'|'email'>){return (process.env.PLATFORM_OPERATOR_USER_IDS||'').split(',').map(s=>s.trim()).includes(session.userId)||(process.env.PLATFORM_OPERATOR_EMAILS||'').split(',').map(s=>s.trim().toLowerCase()).includes(session.email.toLowerCase());}
export function requireOperator(session:Session){if(!isOperator(session))throw new AppError(403,'Platform operator access required.');}
export function readinessToken(authorization:string|null){const expected=process.env.OPS_READINESS_TOKEN,actual=(authorization||'').replace(/^Bearer /,'');return !!expected&&expected.length>=32&&actual.length===expected.length&&timingSafeEqual(Buffer.from(actual),Buffer.from(expected));}
export async function migrationReadiness(){const dir=join(process.cwd(),'migrations'),files=(await readdir(dir)).filter(f=>/^\d{4}_[a-z0-9_]+\.sql$/.test(f)).sort(),rows=(await query<{name:string;sha256:string}>('SELECT name,sha256 FROM schema_migrations')).rows;for(const file of files)if(rows.find(r=>r.name===file)?.sha256!==createHash('sha256').update(await readFile(join(dir,file))).digest('hex'))return {status:'NOT_READY',version:files.at(-1)||null};return {status:rows.length===files.length?'READY':'NOT_READY',version:files.at(-1)||null};}
export async function readiness(){const checks:Record<string,string>={configuration:configurationChecks().every(c=>!c.required||c.status==='configured')?'READY':'NOT_READY'};try{await query('SELECT 1');checks.database='READY';try{checks.migrations=(await migrationReadiness()).status;}catch{checks.migrations='UNAVAILABLE';}}catch{checks.database='UNAVAILABLE';checks.migrations='UNAVAILABLE';}try{await storageReachable();checks.storage='READY';}catch{checks.storage='UNAVAILABLE';}return {ready:Object.values(checks).every(s=>s==='READY'),checks};}
export async function customerServiceStatus(){try{const s=await serviceFreshness();return {execution:s.find(s=>s.service==='execution_dispatcher')?.status==='HEALTHY'?'AVAILABLE':'DELAYED',workflows:s.find(s=>s.service==='workflow_dispatcher')?.status==='HEALTHY'?'AVAILABLE':'DELAYED'};}catch{return {execution:'DEGRADED',workflows:'DEGRADED'};}}
export async function operationStatus(){
  const checks=await readiness(),features=Object.fromEntries(['AI_VIDEO','CLIPPER','WORKFLOWS','PAYMENTS'].map(n=>[n,featureEnabled(n as Parameters<typeof featureEnabled>[0])])),external=externalConfiguration();
  const appVersion=String(JSON.parse(await readFile(join(process.cwd(),'package.json'),'utf8')).version),buildId=/^[a-zA-Z0-9._-]{1,80}$/.test(process.env.APP_BUILD_ID||'')?process.env.APP_BUILD_ID:null;
  if(checks.checks.database!=='READY'||checks.checks.migrations!=='READY')return {appVersion,buildId,readiness:checks,services:[],workers:[],counters:{},backup:null,lastRestoreVerifiedAt:null,alerts:Object.entries(checks.checks).filter(([,s])=>s!=='READY').map(([name])=>({code:`${name.toUpperCase()}_UNAVAILABLE`,count:1})),storage:[],nearLimit:[],workspaceStoragePartial:true,billingMismatchCount:null,features,external};
  const services=await serviceFreshness();
  const workers=(await query<{id:string;name:string;status:string;capabilities:string[];max_concurrency:number;available_slots:number;last_heartbeat_at:Date|null;clipper_health:Record<string,unknown>}>('SELECT id,name,status,capabilities,max_concurrency,available_slots,last_heartbeat_at,clipper_health FROM workers ORDER BY last_heartbeat_at DESC NULLS LAST,id LIMIT 100')).rows.map(w=>({...w,freshness:!w.last_heartbeat_at||Date.now()-w.last_heartbeat_at.getTime()>90000?'OFFLINE':'ONLINE',diskPressure:typeof w.clipper_health.freeDiskBytes==='number'&&w.clipper_health.freeDiskBytes<5*1024**3}));
  const counters:Record<string,unknown>={};for(const [name,table,col] of [['jobs','jobs','status'],['workflows','workflow_runs','status'],['providers','provider_executions','state'],['mail','mail_deliveries','status'],['publications','content_publications','status'],['posters','content_posters','status'],['payments','payments','status']])counters[name]=(await query(`SELECT ${col} AS status,count(*)::text AS count FROM ${table} GROUP BY ${col}`)).rows;
  const backup=(await query('SELECT id,completed_at,migration_version,object_count,object_bytes::text,restore_verified_at FROM backup_records ORDER BY completed_at DESC LIMIT 1')).rows[0]||null;
  const lastRestoreVerifiedAt=(await query('SELECT max(restore_verified_at) AS verified_at FROM backup_records')).rows[0].verified_at as Date|null;
  const reports=await operationalAudits(),storage=(await query('SELECT category,coalesce(sum(byte_size),0)::text AS bytes,count(*)::text AS objects FROM workspace_storage_objects GROUP BY category')).rows,nearLimit=[];
  const scope=(await query<{id:string}>('SELECT id FROM workspaces ORDER BY id LIMIT 101')).rows;for(const w of scope.slice(0,100)){const usage=await workspaceStorageUsage(w.id),limit=(await workspaceLimits(w.id)).find(l=>l.name==='storage_bytes')!;if(BigInt(usage.quotaBytes)*100n>=BigInt(limit.value)*90n)nearLimit.push({workspaceId:w.id,bytes:usage.quotaBytes,limit:limit.value});}
  const alerts:{code:string;count:number}[]=[];for(const [name,status] of Object.entries(checks.checks))if(status!=='READY')alerts.push({code:`${name.toUpperCase()}_UNAVAILABLE`,count:1});for(const s of services)if(s.status!=='HEALTHY')alerts.push({code:`${s.service.toUpperCase()}_${s.status}`,count:1});const offline=workers.filter(w=>w.status==='ACTIVE'&&w.freshness==='OFFLINE').length;if(offline)alerts.push({code:'WORKER_OFFLINE',count:offline});if(nearLimit.length)alerts.push({code:'STORAGE_QUOTA_NEAR_LIMIT',count:nearLimit.length});
  const mismatches=Object.values(reports.billing as Record<string,unknown[]>).reduce((n,rows)=>n+rows.length,0);if(mismatches)alerts.push({code:'BILLING_MISMATCH',count:mismatches});for(const [name,code] of [['submissionUnknown','PROVIDER_UNCERTAIN_BACKLOG'],['publicationBacklog','PUBLICATION_BACKLOG'],['reconciliationIssues','PAYMENT_RECONCILIATION_ISSUES']] as const){const n=Number((reports[name] as {count:string}).count);if(n)alerts.push({code,count:n});}
  if(!backup||Date.now()-new Date(backup.completed_at).getTime()>boundedSetting('BACKUP_STALE_HOURS',24,1,720)*3600000)alerts.push({code:'BACKUP_STALE',count:1});
  return {appVersion,buildId,readiness:checks,services,workers,counters,backup,lastRestoreVerifiedAt,alerts,storage,nearLimit,workspaceStoragePartial:scope.length>100,billingMismatchCount:mismatches,features,external};
}
export async function supportLookup(term:string){if(term.length<3||term.length>254)throw new AppError(400,'Enter a complete identifier, workspace name or email.');if(isUuid(term)){const hits:Record<string,unknown>={};for(const [kind,table] of Object.entries({workspace:'workspaces',user:'users',job:'jobs',workflow:'workflow_runs',payment:'payments',content:'content_items',worker:'workers'}))hits[kind]=(await query(`SELECT id FROM ${table} WHERE id=$1`,[term])).rows;return hits;}return {users:(await query('SELECT id,email,status FROM users WHERE email=$1 LIMIT 20',[term.trim().toLowerCase()])).rows,workspaces:(await query('SELECT id,name FROM workspaces WHERE lower(name)=lower($1) ORDER BY id LIMIT 20',[term.trim()])).rows};}
export async function supportDetail(kind:string,id:string){
  if(!isUuid(id))throw new AppError(404,'Record not found.');
  const sql:Record<string,string>={user:'SELECT id,email,display_name,status,email_verified_at,created_at FROM users WHERE id=$1',workspace:'SELECT id,name,slug,status,created_at FROM workspaces WHERE id=$1',job:'SELECT j.id,j.workspace_id,j.type,j.status,j.progress_stage,j.error_code,j.attempt_count,j.workflow_run_id,b.status AS billing_status,b.token_amount::text FROM jobs j LEFT JOIN job_billing b ON b.job_id=j.id WHERE j.id=$1',workflow:'SELECT id,workspace_id,status,template_key,max_tokens::text,tokens_committed::text,failure_code,created_at,next_reconcile_at FROM workflow_runs WHERE id=$1',payment:'SELECT id,workspace_id,provider,provider_mode,status,reference_id,external_id,creation_unknown,token_amount::text,fiat_minor::text,currency,purchase_ledger_id FROM payments WHERE id=$1',content:'SELECT id,workspace_id,type,status,current_version_id,origin_job_id,product_id,source_asset_id,review_revision FROM content_items WHERE id=$1'};
  sql.worker='SELECT id,name,status,capabilities,max_concurrency,available_slots,last_heartbeat_at,agent_version,clipper_health FROM workers WHERE id=$1';
  sql.job='SELECT j.id,j.workspace_id,j.type,j.status,j.progress_stage,j.error_code,j.attempt_count,j.workflow_run_id,j.workflow_step_id,j.product_id,j.product_version_id,j.created_at,j.updated_at,b.status AS billing_status,b.token_amount::text FROM jobs j LEFT JOIN job_billing b ON b.job_id=j.id WHERE j.id=$1';
  sql.workflow='SELECT id,workspace_id,status,definition_id,definition_version_id,template_key,max_tokens::text,tokens_committed::text,failure_code,created_at,updated_at,next_reconcile_at,cancel_requested_at FROM workflow_runs WHERE id=$1';
  sql.payment='SELECT p.id,p.workspace_id,p.provider,p.provider_mode,p.status,p.reference_id,p.external_id,p.creation_unknown,p.token_amount::text,p.fiat_minor::text,p.currency,p.purchase_ledger_id,p.package_version_id,v.label AS package_label,p.created_at,p.updated_at FROM payments p JOIN token_package_versions v ON v.id=p.package_version_id WHERE p.id=$1';
  if(!sql[kind])throw new AppError(404,'Record not found.');const row=(await query(sql[kind],[id])).rows[0];if(!row)throw new AppError(404,'Record not found.');const result:Record<string,unknown>={record:row};
  const related:Record<string,Record<string,string>>={
    user:{memberships:'SELECT workspace_id,role,status FROM workspace_members WHERE user_id=$1 ORDER BY workspace_id LIMIT 100'},
    workspace:{members:'SELECT user_id,role,status FROM workspace_members WHERE workspace_id=$1 ORDER BY user_id LIMIT 100',wallet:'SELECT available_tokens::text,reserved_tokens::text FROM workspace_wallets WHERE workspace_id=$1',ledger:'SELECT id,entry_type,available_delta::text,reserved_delta::text,job_id,payment_id,created_at FROM token_ledger_entries WHERE workspace_id=$1 ORDER BY created_at DESC,id DESC LIMIT 100',jobs:'SELECT id,type,status,created_at FROM jobs WHERE workspace_id=$1 ORDER BY created_at DESC,id DESC LIMIT 100',workflows:'SELECT id,status,created_at FROM workflow_runs WHERE workspace_id=$1 ORDER BY created_at DESC,id DESC LIMIT 100',payments:'SELECT id,status,provider,created_at FROM payments WHERE workspace_id=$1 ORDER BY created_at DESC,id DESC LIMIT 100'},
    job:{attempts:'SELECT id,status,attempt_number,worker_id,error_code FROM job_attempts WHERE job_id=$1 ORDER BY attempt_number LIMIT 10',leases:'SELECT id,worker_id,status,expires_at FROM worker_leases WHERE job_id=$1 ORDER BY created_at DESC LIMIT 20',provider:'SELECT id,state,external_task_id,submit_count,poll_count,ingest_count,provider_error_code FROM provider_executions WHERE job_id=$1 ORDER BY created_at DESC LIMIT 10',events:'SELECT event_type,safe_data,created_at FROM job_events WHERE job_id=$1 ORDER BY created_at DESC LIMIT 100',publication:'SELECT status,attempts,last_error_code FROM content_publications WHERE job_id=$1'},
    workflow:{steps:'SELECT id,step_key,step_type,state FROM workflow_steps WHERE workflow_run_id=$1 ORDER BY ordinal LIMIT 100',children:'SELECT job_id,workflow_step_id,child_key FROM workflow_child_jobs WHERE workflow_run_id=$1 LIMIT 100',reviewBindings:'SELECT content_item_id,content_version_id FROM workflow_review_bindings WHERE workflow_run_id=$1 LIMIT 100',events:'SELECT event_type,safe_data,created_at FROM workflow_events WHERE workflow_run_id=$1 ORDER BY created_at DESC LIMIT 100'},
    payment:{events:'SELECT event_key,disposition,created_at FROM payment_events WHERE payment_id=$1 ORDER BY created_at DESC LIMIT 100',issues:'SELECT id,code,created_at FROM billing_reconciliation_issues WHERE payment_id=$1 ORDER BY created_at DESC LIMIT 100'},
    content:{versions:'SELECT id,version_number,artifact_id,job_id,workflow_run_id,product_version_id,source_asset_id,sha256,byte_size::text FROM content_versions WHERE content_item_id=$1 ORDER BY version_number DESC LIMIT 100',reviews:'SELECT id,content_version_id,decision,reviewer_user_id,review_revision FROM review_decisions WHERE content_item_id=$1 ORDER BY created_at DESC LIMIT 100'},
  };
  related.workspace.accounting='SELECT w.available_tokens::text,w.reserved_tokens::text,coalesce(sum(e.available_delta),0)::text AS ledger_available,coalesce(sum(e.reserved_delta),0)::text AS ledger_reserved,(w.available_tokens<>coalesce(sum(e.available_delta),0) OR w.reserved_tokens<>coalesce(sum(e.reserved_delta),0)) AS mismatch FROM workspace_wallets w LEFT JOIN token_ledger_entries e ON e.workspace_id=w.workspace_id WHERE w.workspace_id=$1 GROUP BY w.workspace_id,w.available_tokens,w.reserved_tokens';
  related.workspace.reservations="SELECT job_id,status,token_amount::text FROM job_billing WHERE workspace_id=$1 AND status='RESERVED' ORDER BY job_id LIMIT 100";
  related.workflow.billing="SELECT b.status,count(*)::text AS jobs,sum(b.token_amount)::text AS tokens FROM job_billing b JOIN jobs j ON j.id=b.job_id WHERE j.workflow_run_id=$1 GROUP BY b.status";
  related.worker={leases:"SELECT id,job_id,workspace_id,status,expires_at FROM worker_leases WHERE worker_id=$1 ORDER BY created_at DESC LIMIT 100"};
  for(const [name,q] of Object.entries(related[kind]||{}))result[name]=(await query(q,[id])).rows;if(kind==='workspace'){result.limits=await workspaceLimits(id);result.storage=await workspaceStorageUsage(id);}return result;
}
export async function operationalAudits(){
  const report:Record<string,unknown>={billing:await reconciliationReport()};const checks={
    staleRuns:"SELECT id,workspace_id,status FROM workflow_runs WHERE status IN('QUEUED','RUNNING') AND next_reconcile_at<now()-interval '5 minutes'",waitingRuns:"SELECT id,workspace_id,status,failure_code FROM workflow_runs WHERE status IN('WAITING_FOR_FUNDS','WAITING_FOR_REVIEW','PAUSED')",
    missingChildren:"SELECT j.id,j.workspace_id,j.workflow_run_id FROM jobs j WHERE j.workflow_run_id IS NOT NULL AND NOT EXISTS(SELECT 1 FROM workflow_child_jobs c WHERE c.job_id=j.id)",staleLeases:"SELECT id,workspace_id,job_id FROM worker_leases WHERE status='ACTIVE' AND expires_at<now()",
    submissionUnknown:"SELECT id,workspace_id,job_id FROM provider_executions WHERE state='SUBMISSION_UNKNOWN'",waitingWorkers:"SELECT id,workspace_id,required_capability FROM jobs WHERE status='WAITING_FOR_WORKER' AND type<>'AI_VIDEO'",
    publicationBacklog:"SELECT workspace_id,job_id,last_error_code FROM content_publications WHERE status='PENDING' AND created_at<now()-interval '2 minutes'",posterFailures:"SELECT workspace_id,content_item_id,content_version_id,last_error_code FROM content_posters WHERE status='FAILED'",
    brokenContent:"SELECT v.id,v.workspace_id,v.job_id FROM content_versions v JOIN job_artifacts a ON a.id=v.artifact_id WHERE a.status<>'READY' OR a.sha256 IS DISTINCT FROM v.sha256 OR a.byte_size IS DISTINCT FROM v.byte_size",pendingMail:"SELECT id,status,attempts,last_error_code FROM mail_deliveries WHERE status<>'SENT'",paymentUnknown:"SELECT id,workspace_id,status FROM payments WHERE creation_unknown",
    cancelOverdue:"SELECT id,workspace_id,status FROM workflow_runs WHERE cancel_requested_at<now()-interval '5 minutes' AND status NOT IN('SUCCEEDED','FAILED','CANCELLED')",
    waitingOverdue:"SELECT id,workspace_id,status FROM workflow_runs WHERE status IN('WAITING_FOR_FUNDS','WAITING_FOR_REVIEW') AND updated_at<now()-interval '24 hours'",
    stepsWithoutChild:"SELECT id,workspace_id,workflow_run_id FROM workflow_steps s WHERE step_type IN('AI_VIDEO','CLIPPER') AND state IN('RUNNING','SUCCEEDED') AND NOT EXISTS(SELECT 1 FROM workflow_child_jobs c WHERE c.workflow_step_id=s.id)",
    reconcilingOverdue:"SELECT id,workspace_id FROM jobs WHERE status='RECONCILING' AND updated_at<now()-interval '15 minutes'",
    noCompatibleWorker:"SELECT j.id,j.workspace_id FROM jobs j WHERE j.status='WAITING_FOR_WORKER' AND j.type<>'AI_VIDEO' AND NOT EXISTS(SELECT 1 FROM workers w WHERE w.status='ACTIVE' AND w.last_heartbeat_at>now()-interval '90 seconds' AND w.capabilities ? j.required_capability)",
    offlineWithLeases:"SELECT l.id,l.workspace_id,l.job_id FROM worker_leases l JOIN workers w ON w.id=l.worker_id WHERE l.status='ACTIVE' AND (w.last_heartbeat_at IS NULL OR w.last_heartbeat_at<now()-interval '90 seconds')",
    publishedWithoutContent:"SELECT p.workspace_id,p.job_id FROM content_publications p WHERE p.status='PUBLISHED' AND NOT EXISTS(SELECT 1 FROM content_versions v WHERE v.workspace_id=p.workspace_id AND v.job_id=p.job_id)",
    historicalReferenceUnavailable:"SELECT r.workspace_id,r.content_item_id,r.asset_version_id FROM content_reference_assets r JOIN asset_versions a ON a.id=r.asset_version_id WHERE a.status<>'READY'",
    contentLineageMismatch:"SELECT v.id,v.workspace_id FROM content_versions v JOIN jobs j ON j.id=v.job_id WHERE v.workspace_id<>j.workspace_id OR v.workflow_run_id IS DISTINCT FROM j.workflow_run_id OR v.workflow_step_id IS DISTINCT FROM j.workflow_step_id",
    reconciliationIssues:"SELECT id,workspace_id,job_id,payment_id,code FROM billing_reconciliation_issues WHERE created_at>now()-interval '24 hours'",
  };for(const [name,sql] of Object.entries(checks))report[name]={count:(await query<{count:string}>(`SELECT count(*)::text FROM (${sql}) findings`)).rows[0].count,examples:(await query(`${sql} LIMIT 100`)).rows};return report;
}
export async function storageAudit(workspaceId:string,limit=100,observe=false){
  if(!isUuid(workspaceId)||!Number.isInteger(limit)||limit<1||limit>1000)throw new AppError(400,'Invalid audit scope.');const rows=(await query<{object_id:string;category:string;storage_key:string;byte_size:string|null}>('SELECT object_id,category,storage_key,byte_size::text FROM workspace_storage_objects WHERE workspace_id=$1 ORDER BY storage_key LIMIT $2',[workspaceId,limit+1])).rows,findings=[];
  for(const row of rows.slice(0,limit)){let status='VERIFIED',bytes:number|null=null;if(!row.storage_key.startsWith(`workspaces/${workspaceId}/`))status='INVALID_REFERENCE';else try{const h=await objectStorage().head(row.storage_key);bytes=h?.byteSize??null;status=!h?'MISSING':row.byte_size!==null&&BigInt(row.byte_size)!==BigInt(h.byteSize)?'SIZE_MISMATCH':'VERIFIED';if(observe&&h)await query('INSERT INTO storage_object_observations(workspace_id,storage_key,byte_size) VALUES($1,$2,$3) ON CONFLICT(workspace_id,storage_key) DO UPDATE SET byte_size=$3,last_checked_at=now()',[workspaceId,row.storage_key,h.byteSize]);}catch{status='STORAGE_UNAVAILABLE';}findings.push({objectId:row.object_id,category:row.category,status,bytes});}
  const retention=boundedSetting('PENDING_UPLOAD_RETENTION_HOURS',24,1,720);
  const abandoned=(await query<{id:string;category:string;upload_key:string;storage_key:string}>("SELECT id,'asset_upload' AS category,upload_key,storage_key FROM asset_versions WHERE workspace_id=$1 AND status IN('PENDING_UPLOAD','FAILED') AND created_at<now()-make_interval(hours=>$2) UNION ALL SELECT id,'source_upload',upload_key,storage_key FROM source_assets WHERE workspace_id=$1 AND status IN('PENDING_UPLOAD','FAILED') AND created_at<now()-make_interval(hours=>$2) LIMIT $3",[workspaceId,retention,limit+1])).rows;
  const orphanCandidates=[];
  for(const row of abandoned.slice(0,limit))for(const [kind,key] of [['staging',row.upload_key],['unsealed_copy',row.storage_key]]){
    if(!key.startsWith(`pending/workspaces/${workspaceId}/`)&&!key.startsWith(`workspaces/${workspaceId}/`)){orphanCandidates.push({objectId:row.id,category:kind,status:'INVALID_REFERENCE'});continue;}
    try{const h=await objectStorage().head(key);if(h)orphanCandidates.push({objectId:row.id,category:kind,status:'ABANDONED_OBJECT',bytes:h.byteSize});}catch{orphanCandidates.push({objectId:row.id,category:kind,status:'STORAGE_UNAVAILABLE'});}
  }
  const failedPosters=(await query<{content_item_id:string;content_version_id:string;attempts:number}>("SELECT content_item_id,content_version_id,attempts FROM content_posters WHERE workspace_id=$1 AND status='FAILED' AND created_at<now()-make_interval(hours=>$2) ORDER BY content_version_id LIMIT $3",[workspaceId,retention,limit])).rows;
  for(const p of failedPosters)for(let attempt=1;attempt<=Math.min(p.attempts,3);attempt++){try{const h=await objectStorage().head(`workspaces/${workspaceId}/content/${p.content_item_id}/versions/${p.content_version_id}/poster-${attempt}.jpg`);if(h)orphanCandidates.push({objectId:p.content_version_id,category:'failed_poster',status:'ABANDONED_OBJECT',bytes:h.byteSize});}catch{orphanCandidates.push({objectId:p.content_version_id,category:'failed_poster',status:'STORAGE_UNAVAILABLE'});}}
  const s3=storageClient();let multipart:{status:string;abandonedKnownUploads:number;unmappedUploads:number;partial:boolean};
  try{const listing=await s3.send(new ListMultipartUploadsCommand({Bucket:storageBucket(),Prefix:`pending/workspaces/${workspaceId}/sources/`,MaxUploads:limit}),{abortSignal:AbortSignal.timeout(5000)});const known=new Set(abandoned.filter(r=>r.category==='source_upload').map(r=>r.upload_key)),uploads=listing.Uploads||[];multipart={status:'CHECKED',abandonedKnownUploads:uploads.filter(u=>u.Key&&known.has(u.Key)&&u.Initiated&&Date.now()-u.Initiated.getTime()>retention*3600000).length,unmappedUploads:uploads.filter(u=>u.Key&&!known.has(u.Key)).length,partial:!!listing.IsTruncated};}catch{multipart={status:'LISTING_UNAVAILABLE',abandonedKnownUploads:0,unmappedUploads:0,partial:true};}finally{s3.destroy();}
  return {workspaceId,usage:await workspaceStorageUsage(workspaceId),findings,abandoned:abandoned.slice(0,limit).map(r=>({objectId:r.id,category:r.category})),orphanCandidates,multipart,retentionHours:retention,partial:rows.length>limit||abandoned.length>limit||multipart.partial,mode:observe?'observe':'report_only',deletedObjects:0};
}
export async function operatorAction(session:Session,raw:Record<string,unknown>){
  requireOperator(session);const {action,targetId,workspaceId,reason}=raw;if(typeof action!=='string'||typeof targetId!=='string'||!isUuid(targetId)||typeof reason!=='string'||reason.trim().length<8||reason.length>240)throw new AppError(400,'Select an action, target identifier, and reason of 8–240 characters.');
  if(!['SET_QUOTA','SETTLE_JOB','RETRY_PUBLICATION','RETRY_POSTER','RECONCILE_PAYMENT','WAKE_WORKFLOW','RETRY_MAIL','RECORD_RESTORE_VERIFICATION'].includes(action))throw new AppError(400,'Unsupported support action.');const ws=['RETRY_MAIL','RECORD_RESTORE_VERIFICATION'].includes(action)?null:String(workspaceId||targetId);if(ws&&!isUuid(ws))throw new AppError(400,'Workspace is required.');
  const record=(type:string,metadata:Record<string,string|number|boolean|null>={})=>transaction(db=>audit(db,{workspaceId:ws,actorUserId:session.userId,type,targetType:'operator_action',targetId,metadata:{action,reason:reason.trim(),...metadata}}));await record('OPERATOR_ACTION_REQUESTED');
  try{
    if(action==='RECORD_RESTORE_VERIFICATION'){
      const checks=raw.checks as Record<string,unknown>|undefined;
      if(typeof raw.dumpSha256!=='string'||! /^[a-f0-9]{64}$/.test(raw.dumpSha256)||typeof raw.evidenceSha256!=='string'||! /^[a-f0-9]{64}$/.test(raw.evidenceSha256)||!checks||!['isolatedTargets','database','objectChecksums','privateMedia','signIn','pages','lineage','financialReconciliation','noCompensation'].every(c=>checks[c]===true))throw new AppError(400,'A complete independently verified restore receipt is required.');
      await transaction(async db=>{const result=await db.query('UPDATE backup_records SET restore_verified_at=now() WHERE id=$1 AND dump_sha256=$2 RETURNING id',[targetId,raw.dumpSha256]);if(!result.rowCount)throw new AppError(404,'Matching completed backup record not found.');await audit(db,{actorUserId:session.userId,type:'BACKUP_RESTORE_VERIFIED',targetType:'backup',targetId,metadata:{reason:reason.trim(),evidenceSha256:raw.evidenceSha256 as string,dumpSha256:raw.dumpSha256 as string,operatorAttestation:true}});});
    }
    else if(action==='SET_QUOTA'){if(ws!==targetId||typeof raw.limitName!=='string'||!Object.hasOwn(LIMIT_DEFAULTS,raw.limitName)||typeof raw.value!=='string'||!/^\d+$/.test(raw.value)||BigInt(raw.value)<1n||BigInt(raw.value)>9007199254740991n)throw new AppError(400,'Invalid workspace limit.');await transaction(async db=>{await workspaceQuotaLock(db,ws!);await db.query('INSERT INTO workspace_limits(workspace_id,limit_name,limit_value,updated_by) VALUES($1,$2,$3,$4) ON CONFLICT(workspace_id,limit_name) DO UPDATE SET limit_value=$3,updated_by=$4,updated_at=now()',[ws,raw.limitName,raw.value,session.userId]);await audit(db,{workspaceId:ws,actorUserId:session.userId,type:'WORKSPACE_LIMIT_CHANGED',targetType:'workspace',targetId,metadata:{reason:reason.trim(),limitName:raw.limitName as string,value:raw.value as string}});});}
    else if(action==='SETTLE_JOB')await settleJob(ws!,targetId);
    else if(action==='RETRY_PUBLICATION')await publishJobContent(ws!,targetId);
    else if(action==='RETRY_POSTER'){const r=await query("UPDATE content_posters SET status='PENDING',attempts=0,available_at=now(),last_error_code=NULL WHERE workspace_id=$1 AND content_version_id=$2 AND status='FAILED' RETURNING content_version_id",[ws,targetId]);if(!r.rowCount)throw new AppError(409,'Only a failed poster can be retried.');}
    else if(action==='RECONCILE_PAYMENT'){const p=(await query<{provider:'fake'|'xendit';external_id:string|null}>('SELECT provider,external_id FROM payments WHERE workspace_id=$1 AND id=$2',[ws,targetId])).rows[0];if(!p?.external_id)throw new AppError(409,'Provider identity is unavailable. Preserve this payment for investigation.');await processPaymentEvent(p.provider,await paymentProvider(p.provider).getPayment(p.external_id));}
    else if(action==='WAKE_WORKFLOW'){const r=await query("UPDATE workflow_runs SET next_reconcile_at=now() WHERE workspace_id=$1 AND id=$2 AND status NOT IN('SUCCEEDED','FAILED','CANCELLED') RETURNING id",[ws,targetId]);if(!r.rowCount)throw new AppError(409,'Run is terminal or unavailable.');}
    else if(action==='RETRY_MAIL'){const r=await query("UPDATE mail_deliveries SET status='PENDING',attempts=0,available_at=now(),last_error_code=NULL WHERE id=$1 AND status='FAILED' RETURNING id",[targetId]);if(!r.rowCount)throw new AppError(409,'Only failed mail can be retried.');}
    await record('OPERATOR_ACTION_COMPLETED');return {accepted:true,action,targetId};
  }catch(error){await record('OPERATOR_ACTION_FAILED',{code:error instanceof AppError?error.safeCode||`HTTP_${error.status}`:'ACTION_UNAVAILABLE'});throw error;}
}
