import {createHmac,timingSafeEqual} from "node:crypto";
import {query} from "./db";
import {AppError} from "./core";
export type PaymentState="PENDING"|"PAID"|"FAILED"|"EXPIRED"|"REFUNDED";
export type PaymentEvent={eventKey:string;referenceId:string;externalId:string;status:PaymentState;fiatMinor:string;currency:string;businessId?:string;providerPaymentId?:string;providerRequestId?:string;kind?:"REFUND";refundId?:string;refundOutcome?:"SUCCEEDED"|"FAILED"};
export type PaymentRequest={id:string;workspaceId:string;referenceId:string;fiatMinor:string;currency:string;email:string};
export interface PaymentProvider {name:"fake"|"xendit";mode:"TEST"|"SANDBOX";createPayment(input:PaymentRequest):Promise<{event:PaymentEvent;checkoutUrl:string;expiresAt:string}>;getPayment(externalId:string):Promise<PaymentEvent>;verifyWebhook(raw:Buffer,headers:Headers):void;parseWebhook(raw:Buffer):PaymentEvent;refundPayment?: (requestId:string,referenceId:string,fiatMinor:string,currency:string)=>Promise<unknown>;}
function secretEqual(actual:string,expected:string){const a=Buffer.from(actual),b=Buffer.from(expected);return a.length===b.length&&timingSafeEqual(a,b);}
export function fakePaymentsEnabled(){return process.env.APP_ENV==="local"&&process.env.ENABLE_TEST_BILLING==="1"&&process.env.ENABLE_FAKE_PAYMENT_PROVIDER==="1";}
export function fakeWebhookSignature(raw:Buffer){const secret=process.env.FAKE_PAYMENT_WEBHOOK_SECRET;if(!secret||secret.length<32)throw new AppError(503,"Simulation webhook secret is not configured.");return createHmac("sha256",secret).update(raw).digest("hex");}
function normalizedFake(v:Record<string,unknown>):PaymentEvent {if(typeof v.externalId!=="string"||!/^fake_[a-f0-9-]{36}$/.test(v.externalId)||typeof v.referenceId!=="string"||v.referenceId.length>64||typeof v.eventKey!=="string"||v.eventKey.length>200||!["PENDING","PAID","FAILED","EXPIRED","REFUNDED"].includes(String(v.status))||typeof v.fiatMinor!=="string"||! /^[1-9][0-9]{0,15}$/.test(v.fiatMinor)||typeof v.currency!=="string"||! /^[A-Z]{3}$/.test(v.currency))throw new AppError(400,"Invalid simulation event.");return {eventKey:v.eventKey,referenceId:v.referenceId,externalId:v.externalId,status:v.status as PaymentState,fiatMinor:v.fiatMinor,currency:v.currency};}
class FakePaymentProvider implements PaymentProvider {
 name="fake" as const;mode="TEST" as const;
 async createPayment(input:PaymentRequest){const externalId=`fake_${input.id}`;await query("INSERT INTO fake_payment_states(external_id,reference_id,fiat_minor,currency,status) VALUES($1,$2,$3,$4,'PENDING') ON CONFLICT(reference_id) DO NOTHING",[externalId,input.referenceId,input.fiatMinor,input.currency]);return {event:await this.getPayment(externalId),checkoutUrl:`/billing?simulation=${input.id}`,expiresAt:new Date(Date.now()+1800000).toISOString()};}
 async getPayment(id:string){const r=(await query<{external_id:string;reference_id:string;fiat_minor:string;currency:string;status:PaymentState}>("SELECT * FROM fake_payment_states WHERE external_id=$1",[id])).rows[0];if(!r)throw new AppError(404,"Simulation payment not found.");return {eventKey:`${id}:${r.status}`,referenceId:r.reference_id,externalId:id,status:r.status,fiatMinor:r.fiat_minor,currency:r.currency};}
 verifyWebhook(raw:Buffer,headers:Headers){if(!secretEqual(headers.get("x-fake-signature")||"",fakeWebhookSignature(raw)))throw new AppError(401,"Webhook authentication failed.");}
 parseWebhook(raw:Buffer){return normalizedFake(JSON.parse(raw.toString("utf8")));}
 async refundPayment(id:string){await query("UPDATE fake_payment_states SET status='REFUNDED',updated_at=now() WHERE external_id=$1",[id]);return this.getPayment(id);}
}
function xenditConfig(){const key=process.env.XENDIT_SECRET_KEY,callback=process.env.XENDIT_CALLBACK_TOKEN,business=process.env.XENDIT_BUSINESS_ID;
 if(process.env.XENDIT_MODE!=="test"||!key?.startsWith("xnd_development_")||!callback||!business)throw new AppError(503,"Xendit sandbox credentials and business identity are required.");return {key,callback,business};}
async function xenditRequest(path:string,method="GET",payload?:unknown){const {key}=xenditConfig();const response=await fetch(`https://api.xendit.co${path}`,{method,headers:{Authorization:`Basic ${Buffer.from(`${key}:`).toString("base64")}`,"Content-Type":"application/json"},...(payload?{body:JSON.stringify(payload)}:{}),signal:AbortSignal.timeout(15000)});if(!response.ok)throw new AppError(response.status>=500?503:502,"Xendit sandbox request was not accepted.");const raw=await response.text();if(raw.length>131072)throw new AppError(502,"Provider response exceeds limit.");return JSON.parse(raw) as Record<string,unknown>;}
function xenditEvent(data:Record<string,unknown>,businessId?:string):PaymentEvent{
 if(data.session_type!=="PAY"||typeof data.payment_session_id!=="string"||typeof data.reference_id!=="string"||data.currency!=="IDR"||typeof data.amount!=="number"||!Number.isSafeInteger(data.amount)||data.amount<=0)throw new AppError(400,"Unsupported payment session payload.");
 if(data.business_id!==undefined&&String(data.business_id)!==businessId)throw new AppError(400,"Payment business identity differs.");
 const statuses:Record<string,PaymentState>={ACTIVE:"PENDING",COMPLETED:"PAID",EXPIRED:"EXPIRED",CANCELED:"FAILED"},status=statuses[String(data.status)];if(!status)throw new AppError(400,"Unsupported session status.");
 const providerPaymentId=typeof data.payment_id==="string"?data.payment_id:undefined,providerRequestId=typeof data.payment_request_id==="string"?data.payment_request_id:undefined;
 return {eventKey:`session:${data.payment_session_id}:${status}:${providerPaymentId||''}`,referenceId:data.reference_id,externalId:data.payment_session_id,status,fiatMinor:String(data.amount),currency:"IDR",businessId:businessId||String(data.business_id||""),providerPaymentId,providerRequestId};
}
class XenditPaymentProvider implements PaymentProvider {
 name="xendit" as const;mode="SANDBOX" as const;
 async createPayment(input:PaymentRequest){xenditConfig();const base=process.env.XENDIT_RETURN_BASE_URL;if(!base?.startsWith("https://"))throw new AppError(503,"A configured HTTPS sandbox return URL is required.");if(input.currency!=="IDR")throw new AppError(400,"This adapter currently supports IDR sandbox packages.");const amount=Number(input.fiatMinor);if(!Number.isSafeInteger(amount)||amount<=0)throw new AppError(400,"Invalid payment amount.");
 const d=await xenditRequest("/sessions","POST",{reference_id:input.referenceId,session_type:"PAY",mode:"PAYMENT_LINK",capture_method:"AUTOMATIC",amount,currency:"IDR",country:"ID",customer:{reference_id:input.workspaceId.replaceAll("-",""),type:"INDIVIDUAL",email:input.email,individual_detail:{given_names:"Workspace customer"}},expires_at:new Date(Date.now()+1800000).toISOString(),success_return_url:`${base}/billing?payment=${input.id}`,cancel_return_url:`${base}/billing?payment=${input.id}`});
 const url=String(d.payment_link_url||"");if(!/^https:\/\/dev\.xen\.to\//.test(url))throw new AppError(502,"Provider did not return a sandbox checkout URL.");return {event:xenditEvent(d,xenditConfig().business),checkoutUrl:url,expiresAt:String(d.expires_at)};
 }
 async getPayment(id:string){if(!/^ps-[A-Za-z0-9-]+$/.test(id))throw new AppError(400,"Invalid session identity.");return xenditEvent(await xenditRequest(`/sessions/${encodeURIComponent(id)}`),xenditConfig().business);}
 verifyWebhook(_raw:Buffer,headers:Headers){if(!secretEqual(headers.get("x-callback-token")||"",xenditConfig().callback))throw new AppError(401,"Webhook authentication failed.");}
 parseWebhook(raw:Buffer){const v=JSON.parse(raw.toString("utf8")) as Record<string,unknown>;
 if(["refund.succeeded","refund.failed"].includes(String(v.event))){const d=v.data as Record<string,unknown>|undefined;if(v.business_id!==xenditConfig().business||!d||typeof d.id!=="string"||!/^rfd-[A-Za-z0-9-]+$/.test(d.id)||typeof d.payment_request_id!=="string"||!/^pr-[A-Za-z0-9-]+$/.test(d.payment_request_id)||d.currency!=="IDR"||typeof d.amount!=="number"||!Number.isSafeInteger(d.amount)||d.amount<=0||d.status!==(v.event==="refund.succeeded"?"SUCCEEDED":"FAILED"))throw new AppError(400,"Invalid refund event.");return {eventKey:`refund:${d.id}:${d.status}`,referenceId:"",externalId:"",status:"REFUNDED",fiatMinor:String(d.amount),currency:"IDR",businessId:String(v.business_id),providerRequestId:d.payment_request_id,kind:"REFUND",refundId:d.id,refundOutcome:d.status as "SUCCEEDED"|"FAILED"} as PaymentEvent;}
 if(!["payment_session.completed","payment_session.expired"].includes(String(v.event)))throw new AppError(400,"Unsupported payment event.");if(!v.data||typeof v.data!=="object"||String(v.business_id)!==xenditConfig().business)throw new AppError(400,"Payment business identity differs.");const data=v.data as Record<string,unknown>;if(v.event==="payment_session.completed"&&data.status!=="COMPLETED"||v.event==="payment_session.expired"&&data.status!=="EXPIRED")throw new AppError(400,"Event status differs.");return xenditEvent(data,String(v.business_id));}
 async refundPayment(requestId:string,referenceId:string,fiatMinor:string,currency:string){if(currency!=="IDR"||!/^pr-[A-Za-z0-9-]+$/.test(requestId))throw new AppError(400,"Unsupported refund request.");const amount=Number(fiatMinor);if(!/^[1-9][0-9]{0,15}$/.test(fiatMinor)||!Number.isSafeInteger(amount)||amount<=0)throw new AppError(400,"Invalid refund amount.");return xenditRequest("/refunds","POST",{reference_id:referenceId,payment_request_id:requestId,amount,currency,reason:"REQUESTED_BY_CUSTOMER"});}
}
export function paymentProvider(name?:string):PaymentProvider{const selected=name||process.env.PAYMENT_PROVIDER;if(selected==="fake"){if(!fakePaymentsEnabled())throw new AppError(503,"Fake payments require explicit local test mode.");return new FakePaymentProvider();}if(selected==="xendit"){xenditConfig();return new XenditPaymentProvider();}throw new AppError(503,"Payment provider is not configured.");}
