import {test,expect} from "@playwright/test";
import {mkdir,writeFile} from "node:fs/promises";
import pg from "pg";
import {owner,dispatch} from "../clipper-helpers";
import {product} from "../content-helpers";
test("Chrome purchase, quote, paid job, close/reopen, capture, Content, failed job release and isolation",async({browser})=>{test.setTimeout(180000);const email=`p7-chrome-${Date.now()}@example.test`,a=await owner(email,false),b=await owner(`p7-chrome-b-${Date.now()}@example.test`,false),db=new pg.Client({connectionString:process.env.TEST_DATABASE_URL});await db.connect();const context=await browser.newContext();let page=await context.newPage();try{
 await page.goto('/login');await page.getByLabel('Email address').fill(email);await page.getByLabel('Password',{exact:true}).fill('ValidPassword123!');await page.getByRole('button',{name:'Sign in',exact:true}).click();await page.waitForURL((process.env.SAAS_TEST_BASE_URL||"http://127.0.0.1:3200")+"/");await page.goto('/billing');await expect(page.getByText('SIMULATION / TEST PAYMENT · Prices and packages are test data.')).toBeVisible();await expect(page.locator('.stat-card').filter({hasText:'Available tokens'}).locator('strong')).toHaveText('0');
 await page.getByRole('button',{name:'Choose package'}).click();await expect(page.getByRole('button',{name:'Simulate paid',exact:true})).toBeVisible();await page.getByRole('button',{name:'Simulate paid',exact:true}).click();await expect(page.locator('.stat-card').filter({hasText:'Available tokens'}).locator('strong')).toHaveText('10,000');await expect(page.getByRole('cell',{name:'PURCHASE',exact:true})).toHaveCount(1);
 const p=await product(a.c,a.workspaceId);await page.goto('/ai-videos');await page.getByLabel('Saved Product').selectOption(p.id);await page.getByLabel('Video prompt').fill('Show the saved Product on a studio table with a slow camera orbit.');await page.getByLabel('Duration').selectOption('5');await page.getByLabel('Aspect ratio').selectOption('1:1');await expect(page.getByText('Required: 700 Tokens',{exact:true})).toBeVisible();await page.getByRole('button',{name:'Generate video'}).click();await page.waitForURL(/\/ai-videos\/[a-f0-9-]+$/);const url=page.url(),id=url.split('/').pop()!;expect((await db.query('SELECT available_tokens,reserved_tokens FROM workspace_wallets WHERE workspace_id=$1',[a.workspaceId])).rows[0]).toMatchObject({available_tokens:'9300',reserved_tokens:'700'});await page.close();
 for(let n=0;n<30;n++){dispatch();const r=(await db.query('SELECT status FROM job_billing WHERE job_id=$1',[id])).rows[0];if(r.status==='CAPTURED')break;await new Promise(r=>setTimeout(r,200));}expect((await db.query('SELECT status FROM job_billing WHERE job_id=$1',[id])).rows[0].status).toBe('CAPTURED');page=await context.newPage();await page.goto(url);await expect(page.getByText('Token cost: 700 · CAPTURED')).toBeVisible();await expect(page.getByRole('heading',{name:'Preview and download'})).toBeVisible();await page.goto('/content');await expect(page.locator('a[href^="/content/"]').filter({hasText:'Historical Product'}).first()).toBeVisible();
 const raw={productId:p.id,prompt:'A controlled failure fixture for a saved Product with a valid request.',tier:'QUALITY',durationSeconds:5,aspectRatio:'1:1',quantity:1,idempotencyKey:crypto.randomUUID(),testScenario:'FAILURE'};const q=(await (await a.c.post(`/api/workspaces/${a.workspaceId}/billing/quotes`,{data:{...raw,operation:'AI_VIDEO'}})).json()).quote;const failure=await a.c.post(`/api/workspaces/${a.workspaceId}/ai-videos`,{data:{...raw,quoteId:q.id,quoteHash:q.quoteHash}});expect(failure.status()).toBe(201);const failedId=(await failure.json()).job.id;for(let n=0;n<30;n++){dispatch();if((await db.query('SELECT status FROM job_billing WHERE job_id=$1',[failedId])).rows[0].status==='RELEASED')break;await new Promise(r=>setTimeout(r,200));}expect((await db.query('SELECT status FROM job_billing WHERE job_id=$1',[failedId])).rows[0].status).toBe('RELEASED');await page.goto('/billing');await expect(page.locator('.stat-card').filter({hasText:'Available tokens'}).locator('strong')).toHaveText('9,300');await expect(page.locator('.stat-card').filter({hasText:'Reserved tokens'}).locator('strong')).toHaveText('0');
 for(const route of ['billing','billing/ledger','billing/payments'])expect((await b.c.get(`/api/workspaces/${a.workspaceId}/${route}`)).status()).toBe(404);const user=(await (await b.c.get('/api/auth/session')).json()).user.id;await db.query("INSERT INTO workspace_members(workspace_id,user_id,role) VALUES($1,$2,'VIEWER')",[a.workspaceId,user]);await b.c.post(`/api/workspaces/${a.workspaceId}/select`);const viewer=await browser.newContext({storageState:await b.c.storageState()});try{const v=await viewer.newPage();await v.goto('/billing');await expect(v.getByRole('heading',{name:'Buy Tokens'})).toHaveCount(0);await v.goto('/ai-videos');await expect(v.getByRole('button',{name:'Generate video'})).toBeDisabled();}finally{await viewer.close();}
 await mkdir('data/phase7',{recursive:true});await page.screenshot({path:'data/phase7/billing-chrome.png',fullPage:true});await writeFile('data/phase7/browser-acceptance.json',JSON.stringify({result:'passed',browser:'Chrome',testTokensPurchased:10000,paidFakeAiVideoJob:id,capturedTokens:700,failedJob:failedId,releasedTokens:700,availableTokens:9300,reservedTokens:0,browserClosedAndReopened:true,contentPublished:true,brandIsolation:true,viewerCannotPurchaseOrSpend:true,realSeedanceGenerations:0,realOpenAiAnalyzerCalls:0,productionPayments:0},null,2));
 }finally{await context.close();await Promise.all([a.c.dispose(),b.c.dispose()]);await db.end();}});
