"use client";
import { useEffect,useState } from "react";
import Link from "next/link";
import type { Campaign,OutreachOverview } from "@/lib/integrations/outreach";
import type { OutreachSystemStatus } from "@/lib/integrations/outreach/status";
import { displayHistoricalLabel } from "@/lib/display";
import { Icon } from "@/components/icon";
import { PageHeader,StatusBadge,EmptyState,MetricCard } from "@/components/ui";
const tabs=["All","Active","Completed","Draft / queued"] as const;
function included(c:Campaign,tab:typeof tabs[number]){if(tab==="All")return true;if(tab==="Completed")return ["COMPLETED","COMPLETED_WITH_ERRORS","CANCELLED"].includes(c.state);if(tab==="Draft / queued")return ["DRAFT","PREVIEW_READY","PREVIEW_EXPIRED","FROZEN","QUEUED","DISCOVERING"].includes(c.state);return ["RUNNING","PAUSE_REQUESTED","PAUSED","SAFETY_PAUSED"].includes(c.state);}
function tone(state:string){return /COMPLETED/.test(state)?"success" as const:/FAILED|RESTRICTED|SAFETY/.test(state)?"danger" as const:/RUNNING|QUEUED|FROZEN/.test(state)?"warning" as const:"neutral" as const;}
export default function OutreachPage(){
  const [data,setData]=useState<OutreachOverview|null>(null);const [sender,setSender]=useState<OutreachSystemStatus|null>(null);const [tab,setTab]=useState<typeof tabs[number]>("All");const [query,setQuery]=useState("");const [pageIndex,setPageIndex]=useState(0);const [failed,setFailed]=useState(false);
  useEffect(()=>{const c=new AbortController();fetch("/api/outreach/overview",{cache:"no-store",signal:c.signal}).then(r=>{if(!r.ok)throw new Error();return r.json();}).then(setData).catch(()=>{if(!c.signal.aborted)setFailed(true);});fetch("/api/outreach/status",{cache:"no-store",signal:c.signal}).then(r=>r.json()).then(setSender).catch(()=>undefined);return ()=>c.abort();},[]);
  const all=data?.campaigns??[];const connected=data?.state==="connected";const campaigns=all.filter(c=>included(c,tab)&&displayHistoricalLabel(c.name).toLowerCase().includes(query.toLowerCase()));
  const pageCount=Math.max(1,Math.ceil(campaigns.length/6));const currentPage=Math.min(pageIndex,pageCount-1);const visibleCampaigns=campaigns.slice(currentPage*6,currentPage*6+6);
  const totals=all.reduce((a,c)=>({sending:a.sending+c.sending,sent:a.sent+c.sent,queued:a.queued+c.queued}),{sending:0,sent:0,queued:0});
  const queueEnabled=sender?.message.includes("queueing is enabled");
  return <><PageHeader title="Outreach" description="Manage campaigns, review recipients, and follow sending progress." action={<Link className="button" href="/outreach/new"><Icon name="plus" size={17} />New Campaign</Link>} />
    <div className="summary-grid"><MetricCard label="Active Campaigns" icon="send" value={connected?all.filter(c=>included(c,"Active")).length:"—"} detail="Across recent campaigns" /><MetricCard label="Sending Now" icon="activity" tone="green" value={connected?totals.sending:"—"} detail="Recipients currently processing" /><MetricCard label="Messages Sent" icon="check" tone="blue" value={connected?totals.sent.toLocaleString():"—"} detail="Across recent campaigns" /><MetricCard label="Worker Status" icon="layers" tone="purple" value={sender?.state==="connected"?sender.worker:"—"} detail={sender?.state==="connected"?"Sending service":"Worker status unavailable"} /></div>
    <section className="card panel"><div className="table-toolbar"><h2>Campaigns {connected?`(${all.length})`:""}</h2><label className="table-search"><Icon name="search" size={17} /><input className="input" aria-label="Search campaign name" placeholder="Search campaign name…" value={query} onChange={e=>{setQuery(e.target.value);setPageIndex(0);}} /></label></div><div className="tab-row" role="tablist" aria-label="Campaign status">{tabs.map(t=><button key={t} role="tab" aria-selected={tab===t} className={`tab ${tab===t?"active":""}`} onClick={()=>{setTab(t);setPageIndex(0);}}>{t}</button>)}</div>
    {campaigns.length?<div className="table-scroll"><table className="data-table"><thead><tr><th>Campaign Name</th><th>Status</th><th>Recipients</th><th>Sent</th><th>Remaining</th><th>Created</th><th>Actions</th></tr></thead><tbody>{visibleCampaigns.map(c=><tr key={c.id}><td><strong>{displayHistoricalLabel(c.name)}</strong><small>{c.frozen?"Frozen recipient list":`Target ${c.targetCount}`}</small></td><td><StatusBadge tone={tone(c.state)}>{c.state.toLowerCase().replaceAll("_"," ")}</StatusBadge></td><td>{c.frozen.toLocaleString()}</td><td>{c.sent.toLocaleString()}<progress value={c.sent} max={c.frozen||1} aria-label={`${c.name} sent progress`} /></td><td>{c.frozen?c.remaining.toLocaleString():"—"}</td><td>{new Date(c.createdAt).toLocaleDateString()}</td><td><Link className="button-outline" href={`/outreach/${c.id}`}>View<Icon name="arrow" size={14} /></Link></td></tr>)}</tbody></table></div>:<EmptyState title={connected?query?"No matching campaigns":"No campaigns in this view":data||failed?"Campaign data unavailable":"Loading campaigns…"} detail={connected?"Choose another status or create a campaign to get started.":"Campaigns appear when the Outreach connection is available."} icon="send" />}{campaigns.length>0&&<div className="table-pagination"><span>{currentPage*6+1}–{Math.min(currentPage*6+6,campaigns.length)} of {campaigns.length} campaigns</span><div><button className="button-outline" disabled={currentPage===0} onClick={()=>setPageIndex(currentPage-1)}>Previous</button><span>Page {currentPage+1} of {pageCount}</span><button className="button-outline" disabled={currentPage>=pageCount-1} onClick={()=>setPageIndex(currentPage+1)}>Next</button></div></div>}{all.some(c=>displayHistoricalLabel(c.name)!==c.name)&&<p className="field-note">Historical brand labels are displayed neutrally. Original campaign records are unchanged.</p>}</section>
    <section className="card panel workflow-panel"><h2>Campaign steps</h2><p className="page-description">Four steps, with a final review before anything is queued.</p><div className="workflow">{[["Campaign","Set your audience and message."],["Preview","Review eligibility and selected recipients."],["Freeze","Lock the audience and rendered messages."],["Confirm","Review the frozen campaign before queueing."]].map(([title,description],i)=><div key={title}><b>{i+1}</b><strong>{title}</strong><p>{description}</p></div>)}</div></section>
    <div className="notice"><Icon name="shield" size={21} /><div><strong>{!sender?"Checking sending availability…":!queueEnabled?"Campaign sending is currently disabled":sender.sender!=="available"?"Campaign sending is currently unavailable":"Sending is available"}</strong><p>Preview and freeze do not send messages. Sending requires final confirmation.</p></div></div>
  </>;
}
