import {expect,request,type APIRequestContext} from "@playwright/test";
import {execFileSync} from "node:child_process";
import {readdir,readFile} from "node:fs/promises";
import {join} from "node:path";
import {createHash} from "node:crypto";
export const base="http://127.0.0.1:3200";
export async function owner(email:string){const c=await request.newContext({baseURL:base,extraHTTPHeaders:{Origin:base}});expect((await c.post("/api/auth/register",{data:{email,displayName:"Clipper Owner",password:"ValidPassword123!"}})).status()).toBe(201);const dir=join(process.cwd(),"data","mailbox");let url="";for(let i=0;i<50&&!url;i++){for(const f of (await readdir(dir)).filter(x=>x.endsWith(".json")).sort().reverse()){const m=JSON.parse(await readFile(join(dir,f),"utf8"));if(m.to===email&&m.subject.includes("Verify")){url=m.url;break;}}if(!url)await new Promise(r=>setTimeout(r,100));}expect(url).toBeTruthy();expect((await c.post("/api/auth/verify",{data:{token:new URL(url).searchParams.get("token")}})).status()).toBe(200);const r=await c.post("/api/workspaces",{data:{name:`Clipper ${email}`}});expect(r.status()).toBe(201);return {c,workspaceId:(await r.json()).workspace.id as string};}
export function provision(name:string,max=1){return JSON.parse(execFileSync(process.execPath,["--env-file=.env.local","scripts/worker-admin.mjs","create",name,"CLIPPER_TEST_V1",String(max),"--test"],{cwd:process.cwd(),encoding:"utf8"})) as {workerId:string;credential:string};}
export async function worker(token:string,slots=1){const c=await request.newContext({baseURL:base,extraHTTPHeaders:{Authorization:`Bearer ${token}`}});expect((await c.post("/api/worker/heartbeat",{data:{agentVersion:"phase5-test",pipelineVersion:"clipper-v1",availableSlots:slots,activeLeaseIds:[]}})).status()).toBe(200);return c;}
export function dispatch(){execFileSync(process.execPath,["--env-file=.env.local","--import","tsx","scripts/dispatcher.ts","--once"],{cwd:process.cwd(),env:{...process.env,DATABASE_URL:process.env.TEST_DATABASE_URL,OBJECT_STORAGE_BUCKET:process.env.TEST_OBJECT_STORAGE_BUCKET,JOB_RETRY_BASE_MS:"1000"},stdio:"pipe"});}
export async function source(c:APIRequestContext,workspaceId:string){const bytes=await readFile("tests/fixtures/clipper-speech.mp4");const r=await c.post(`/api/workspaces/${workspaceId}/sources`,{data:{filename:"clipper-speech.mp4",mimeType:"video/mp4",byteSize:bytes.length}});expect(r.status(),await r.text()).toBe(201);const intent=await r.json();expect((await fetch(intent.uploadUrl,{method:"PUT",headers:intent.requiredHeaders,body:bytes})).ok).toBe(true);const done=await c.post(`/api/workspaces/${workspaceId}/sources/${intent.source.id}/finalize`);expect(done.status(),await done.text()).toBe(200);expect((await done.json()).status).toBe("UPLOADED");return {id:intent.source.id as string,sha256:createHash("sha256").update(bytes).digest("hex"),byteSize:bytes.length};}
export function submit(c:APIRequestContext,workspaceId:string,sourceAssetId:string,key:string,extra:Record<string,unknown>={}){return c.post(`/api/workspaces/${workspaceId}/clipper`,{data:{sourceAssetId,idempotencyKey:key,language:"en",goal:"Find useful ideas",targetClipCount:2,minClipSeconds:10,maxClipSeconds:30,captions:true,...extra}});}
export type Claim={jobId:string;attemptId:string;leaseId:string;fencingToken:string;inputSnapshot:Record<string,unknown>};
export const lease=(c:Claim)=>({attemptId:c.attemptId,leaseId:c.leaseId,fencingToken:c.fencingToken});
export async function publish(c:APIRequestContext,claim:Claim,slotName:string,bytes:Buffer,mimeType="application/json"){const sha256=createHash("sha256").update(bytes).digest("hex");const r=await c.post(`/api/worker/jobs/${claim.jobId}/outputs`,{data:{...lease(claim),slotName,mimeType,byteSize:bytes.length,sha256}});expect(r.status(),await r.text()).toBe(200);const a=await r.json();expect((await fetch(a.uploadUrl,{method:"PUT",headers:a.requiredHeaders,body:new Uint8Array(bytes)})).ok).toBe(true);const done=await c.post(`/api/worker/jobs/${claim.jobId}/outputs/finalize`,{data:{...lease(claim),artifactId:a.artifactId}});expect(done.status(),await done.text()).toBe(200);return {id:a.artifactId as string,sha256,uploadUrl:a.uploadUrl as string};}
