"use client";
import { useEffect,useState } from "react";
import type { ClipperOverview } from "@/lib/integrations/clipper";
import { Icon } from "@/components/icon";
import { PageHeader,StatusBadge,EmptyState } from "@/components/ui";
export default function ClipperPage(){
  const [data,setData]=useState<ClipperOverview|null>(null);const [failed,setFailed]=useState(false);
  useEffect(()=>{const c=new AbortController();fetch("/api/clipper/overview",{cache:"no-store",signal:c.signal}).then(r=>{if(!r.ok)throw new Error();return r.json();}).then(setData).catch(()=>{if(!c.signal.aborted)setFailed(true);});return ()=>c.abort();},[]);
  const connected=data?.state==="connected";const checking=!data&&!failed;
  return <><PageHeader title="Clipper" icon="scissors" description="Follow source videos, clipping jobs, and AI-selected moments." action={<><StatusBadge tone={connected?"success":checking?"neutral":"danger"}>{connected?"Clipper Connected":checking?"Checking connection":"Clipper Offline"}</StatusBadge><a className="button" href="http://127.0.0.1:5173" target="_blank" rel="noopener noreferrer">Open Clipper<Icon name="external" size={17} /></a></>} />
    <div className="clip-layout"><section className="card panel"><div className="section-top"><h2><Icon name="file" />Recent Source Videos</h2><span className="field-note">Watched sources</span></div>{data?.sources.length?<div className="record-list">{data.sources.map((s,i)=><div className="record-row" key={`${s.name}-${i}`}><div style={{display:"flex",alignItems:"center",gap:12}}><span className="avatar"><Icon name="video" /></span><strong>{s.name}</strong></div><span>{(s.size/1048576).toFixed(1)} MB</span></div>)}</div>:<EmptyState title={checking?"Checking sources…":connected?"No source videos yet":"Source videos unavailable"} detail={connected?"Add a video through Clipper to get started.":"Sources appear when the Clipper service is connected."} icon="video" />}</section>
    <section className="card panel"><div className="section-top"><h2><Icon name="layers" />Clipping Jobs</h2><span className="field-note">Latest 25</span></div>{data?.jobs.length?<div className="table-scroll"><table className="data-table" style={{minWidth:480}}><thead><tr><th>Source / job</th><th>Status</th><th>Progress</th><th>Clips</th></tr></thead><tbody>{data.jobs.map(j=><tr key={j.id}><td><strong>{j.name||"Clipping job"}</strong><small>{j.step||"—"}</small></td><td><StatusBadge tone={/completed/i.test(j.status)?"success":/failed/i.test(j.status)?"danger":"warning"}>{j.status}</StatusBadge></td><td>{j.progress}%<progress value={j.progress} max={100} aria-label={`${j.name} progress`} /></td><td>{j.clips}</td></tr>)}</tbody></table></div>:<EmptyState title={checking?"Checking jobs…":connected?"No recent clipping jobs":"Clipper is offline"} detail={connected?"Start processing in Clipper. Job updates will appear here.":"Open the native application to check its processing service."} icon="scissors" />}</section></div>
    <div className="notice"><Icon name="alert" size={21} /><div><strong>Editing and publishing stay in Clipper</strong><p>AI Site monitors sources, jobs, and scores. Open Clipper to edit, fine-tune, submit, or publish your clips.</p></div></div>
    <section className="card panel"><div className="section-top"><h2><Icon name="sparkles" />Scored Clips</h2><span className="field-note">Latest 25 score records</span></div>{data?.results.length?<div className="clip-grid">{data.results.map(r=><article className="clip-tile" key={r.id}><div className="clip-placeholder"><Icon name="video" size={33} /><span className="clip-score">{r.score===null?"—":r.score.toFixed(1)}</span></div><div className="clip-tile-body"><strong>{r.source||"Scored clip"}</strong><p>{r.product||"Unassigned product"}</p><StatusBadge>{r.status}</StatusBadge></div></article>)}</div>:<EmptyState title={checking?"Checking scored clips…":connected?"No scored clips yet":"Scored clips unavailable"} detail="Clip scores will appear here when available. Media previews remain in the native application." icon="sparkles" />}</section>
  </>;
}
