// No raw customer rows or secrets leave the process. --apply checks history
// in the same transaction as the additive migration and aborts on drift.
import {readFile,writeFile,mkdir} from 'node:fs/promises';
import {createHash,randomBytes} from 'node:crypto';
import pg from 'pg';
import {parseEnv} from 'node:util';
process.loadEnvFile('.env.local');
const mode=process.argv[2]||'--verify',root='.next-tests/phase-f',migration='0016_outreach_provider_onboarding.sql';
if(!['--verify','--apply','--isolated'].includes(mode))throw new Error('Use --verify|--apply|--isolated');
const before=JSON.parse(await readFile(`${root}/live-before.json`,'utf8')),docs=JSON.parse(await readFile(`${root}/evidence-before.json`,'utf8')),native=JSON.parse(await readFile(`${root}/native-before.json`,'utf8'));
const hash=v=>createHash('sha256').update(Buffer.isBuffer(v)||typeof v==='string'?v:JSON.stringify(v)).digest('hex');
const sql=await readFile(`migrations/${migration}`,'utf8'),sha256=hash(sql),assert=(condition,code)=>{if(!condition)throw new Error(code);};
const d=new pg.Client({connectionString:process.env.DATABASE_URL});let stage='connect',isolatedName,isolated;
async function fingerprint(db){const result={};for(const t of Object.keys(before.history)){const rows=(await db.query(`SELECT to_jsonb(t) AS r FROM ${t} t ORDER BY to_jsonb(t)::text`)).rows.map(r=>r.r);result[t]={rows:rows.length,sha256:hash(rows)};}return result;}
async function wallet(db){return (await db.query('SELECT coalesce(sum(available_tokens),0)::text available,coalesce(sum(reserved_tokens),0)::text reserved FROM billing_account_wallets')).rows[0];}
async function unchangedFiles(){for(const f of [...docs,...native, ...JSON.parse(await readFile(`${root}/private-before.json`,'utf8'))])assert(hash(await readFile(f.path))===f.sha256,'PRESERVED_REFERENCE_OR_EVIDENCE_CHANGED');}
async function migrations(db){for(const m of before.migrations)assert(hash(await readFile(`migrations/${m.name}`,'utf8'))===m.sha256,'PREVIOUS_MIGRATION_CHANGED');const rows=(await db.query('SELECT name,sha256 FROM schema_migrations ORDER BY name')).rows;assert(JSON.stringify(rows.filter(r=>r.name!==migration))===JSON.stringify(before.migrations),'MIGRATION_HISTORY_CHANGED');return rows;}
async function schema(db){const queries={columns:"SELECT table_name,column_name,ordinal_position,data_type,udt_name,is_nullable,column_default FROM information_schema.columns WHERE table_schema='public' ORDER BY table_name,ordinal_position",constraints:"SELECT c.relname AS table_name,p.conname,pg_get_constraintdef(p.oid) AS definition FROM pg_constraint p JOIN pg_class c ON c.oid=p.conrelid JOIN pg_namespace n ON n.oid=c.relnamespace WHERE n.nspname='public' ORDER BY c.relname,p.conname",triggers:"SELECT c.relname AS table_name,t.tgname,pg_get_triggerdef(t.oid) AS definition,t.tgenabled FROM pg_trigger t JOIN pg_class c ON c.oid=t.tgrelid JOIN pg_namespace n ON n.oid=c.relnamespace WHERE n.nspname='public' AND NOT t.tgisinternal ORDER BY c.relname,t.tgname",functions:"SELECT p.proname,pg_get_function_identity_arguments(p.oid) AS arguments,pg_get_functiondef(p.oid) AS definition FROM pg_proc p JOIN pg_namespace n ON n.oid=p.pronamespace WHERE n.nspname='public' AND p.prokind='f' ORDER BY p.proname,pg_get_function_identity_arguments(p.oid)",indexes:"SELECT tablename,indexname,indexdef FROM pg_indexes WHERE schemaname='public' ORDER BY tablename,indexname"};const result={};for(const [k,q] of Object.entries(queries))result[k]=(await db.query(q)).rows;return result;}
async function unchangedNativeSchema(){
 const original=JSON.parse(await readFile('.next-tests/phase-e/native-schema-before.json','utf8'));
 const configuration=parseEnv(await readFile('../app/.env.local','utf8')),url=new URL(configuration.OUTREACH_DATABASE_URL);
 assert(['localhost','127.0.0.1'].includes(url.hostname),'NATIVE_DATABASE_NOT_LOOPBACK');
 const n=new pg.Client({connectionString:url.href,connectionTimeoutMillis:5000});try{
  await n.connect();await n.query('BEGIN READ ONLY');
  const columns=(await n.query("SELECT table_name,column_name,data_type,is_nullable FROM information_schema.columns WHERE table_schema='public' ORDER BY table_name,ordinal_position")).rows;
  const constraints=(await n.query("SELECT c.relname,p.conname,pg_get_constraintdef(p.oid) definition FROM pg_constraint p JOIN pg_class c ON c.oid=p.conrelid JOIN pg_namespace s ON s.oid=c.relnamespace WHERE s.nspname='public' ORDER BY c.relname,p.conname")).rows;
  const schemaHash=hash({columns,constraints});assert(schemaHash===original.sha256,'NATIVE_SCHEMA_CHANGED');
  await n.query('COMMIT');return {unchanged:true,tables:new Set(columns.map(c=>c.table_name)).size,sha256:schemaHash,readOnly:true};
 }finally{await n.end().catch(()=>{});}
}
const result={status:'FAIL',mode,migration,migrationSha256:sha256,paid:{realVideo:0,realLLM:0,outreach:0,payments:0}};
try{await d.connect();stage='references';await unchangedFiles();stage='native-schema';result.nativeSchema=await unchangedNativeSchema();stage='migration-history';await migrations(d);stage='historical-fingerprints';const history=await fingerprint(d);assert(JSON.stringify(history)===JSON.stringify(before.history),'LIVE_HISTORY_CHANGED');stage='wallet-totals';assert(JSON.stringify(await wallet(d))===JSON.stringify(before.wallet),'LIVE_WALLET_CHANGED');
 if(mode==='--isolated'||mode==='--apply'){
  stage='canonical-schema';isolatedName=`phase_e_schema_${Date.now()}_${randomBytes(3).toString('hex')}`;await d.query(`CREATE DATABASE "${isolatedName}"`);const u=new URL(process.env.DATABASE_URL);u.pathname='/'+isolatedName;isolated=new pg.Client({connectionString:u.href});await isolated.connect();await isolated.query('CREATE TABLE schema_migrations (name text PRIMARY KEY,sha256 text NOT NULL,applied_at timestamptz NOT NULL DEFAULT now())');for(const m of before.migrations)await isolated.query(await readFile(`migrations/${m.name}`,'utf8'));const liveSchema=await schema(d),existing=(await d.query('SELECT 1 FROM schema_migrations WHERE name=$1',[migration])).rowCount;if(!existing)assert(JSON.stringify(liveSchema)===JSON.stringify(await schema(isolated)),'LIVE_SCHEMA_DIFFERS_FROM_CERTIFIED_BASELINE');
  await isolated.query('BEGIN');await isolated.query(sql);await isolated.query('INSERT INTO schema_migrations(name,sha256) VALUES($1,$2)',[migration,sha256]);await isolated.query('COMMIT');
  const prices=(await isolated.query("SELECT c.realm,v.rules FROM price_catalogs c JOIN price_versions v ON v.id=c.active_version_id WHERE c.operation='OUTREACH' ORDER BY realm")).rows;assert(prices.length===2&&prices.every(p=>p.rules.perSuccessfulSend==='10'&&p.rules.approval==='INTERNAL_BETA'&&p.rules.maxRecipients===500),'OUTREACH_PRICE_INVALID');result.internalBetaPrice=10;result.realms=['PRODUCTION','TEST'];
  if(mode==='--apply'){
   stage='test-gate';for(const s of ['provider','provider-browser','canary-browser','outreach','outreach-browser','outreach-restart','variations','restart-variation','editor','integration','browser','shared','focused','restart','phase-b','isolation']){const r=JSON.parse(await readFile(`docs/phase-f-evidence/${s}-run.json`,'utf8'));assert(r.exitCode===0,'ISOLATED_SUITE_NOT_PASS');assert(r.cleanup.database==='deleted'&&r.cleanup.bucket==='deleted'&&r.cleanup.gateway==='deleted','ISOLATED_CLEANUP_INCOMPLETE');}
   stage='live-migration';await d.query('BEGIN');try{await d.query('SELECT pg_advisory_xact_lock(731052133)');await d.query('SET LOCAL lock_timeout=\'10s\'');for(const table of Object.keys(before.history))await d.query(`LOCK TABLE ${table} IN SHARE ROW EXCLUSIVE MODE`);assert(JSON.stringify(await fingerprint(d))===JSON.stringify(before.history),'HISTORY_CHANGED_BEFORE_MIGRATION');if(!existing){await d.query(sql);await d.query('INSERT INTO schema_migrations(name,sha256) VALUES($1,$2)',[migration,sha256]);}assert(JSON.stringify(await fingerprint(d))===JSON.stringify(before.history),'HISTORY_CHANGED_BY_MIGRATION');assert(JSON.stringify(await schema(d))===JSON.stringify(await schema(isolated)),'MIGRATED_SCHEMA_DIFFERS_FROM_TESTED_SCHEMA');assert(JSON.stringify(await wallet(d))===JSON.stringify(before.wallet),'WALLET_CHANGED_BY_MIGRATION');for(const table of ['outreach_channels','outreach_creators','outreach_campaigns','outreach_recipients','outreach_deliveries','outreach_test_receipts','outreach_oauth_states','outreach_canary_approvals','outreach_directory_authorizations','outreach_provider_proofs','outreach_credential_versions','outreach_provider_fixtures'])assert(Number((await d.query(`SELECT count(*) n FROM ${table}`)).rows[0].n)===0,'FAKE_OUTREACH_CREATED_IN_LIVE');await d.query('COMMIT');result.applied=true;}catch(e){await d.query('ROLLBACK');throw e;}
  }
  result.schemaMatchesTestedBaseline=true;
 }
 result.status='PASS';result.historicalFingerprints=history;result.wallet=await wallet(d);result.nativeFilesUnchanged=native.length;result.oldEvidenceFilesUnchanged=docs.length;result.historicalLedgerEntriesAdded=0;result.historicalContentVersionsChanged=0;
}catch(e){result.failedCheck=stage;result.failureCode=/^[A-Z_]+$/.test(e?.message||'')?e.message:'PRESERVATION_CHECK_FAILED';process.exitCode=1;}finally{await isolated?.end().catch(()=>{});if(isolatedName)await d.query(`DROP DATABASE "${isolatedName}" WITH (FORCE)`).catch(()=>{result.status='FAIL';result.cleanup='FAILED';process.exitCode=1;});await d.end().catch(()=>{});}
await mkdir('docs/phase-f-evidence',{recursive:true});await writeFile(`docs/phase-f-evidence/${mode==='--apply'?'live-migration':mode==='--isolated'?'schema-migration':'preservation'}.json`,JSON.stringify(result,null,2));console.log(JSON.stringify(result));
