-- New SaaS-owned Outreach only. No native DB, sender, campaigns or credentials are imported.
ALTER TABLE price_catalogs DROP CONSTRAINT price_catalogs_operation_check;
ALTER TABLE price_catalogs ADD CHECK(operation IN('AI_VIDEO','CLIPPER','CLIPPER_VARIATION','OUTREACH'));
ALTER TABLE billing_quotes DROP CONSTRAINT billing_quotes_operation_check;
ALTER TABLE billing_quotes ADD CHECK(operation IN('AI_VIDEO','CLIPPER','CLIPPER_VARIATION','OUTREACH'));
CREATE TABLE outreach_channel_credentials(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),workspace_id uuid NOT NULL REFERENCES workspaces(id),ciphertext bytea NOT NULL CHECK(octet_length(ciphertext) BETWEEN 32 AND 65536),key_version integer NOT NULL CHECK(key_version>0),created_at timestamptz NOT NULL DEFAULT now(),UNIQUE(workspace_id,id));
CREATE TRIGGER outreach_credentials_immutable BEFORE UPDATE OR DELETE ON outreach_channel_credentials FOR EACH ROW EXECUTE FUNCTION billing_immutable();
CREATE TABLE outreach_channels(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),workspace_id uuid NOT NULL REFERENCES workspaces(id),provider text NOT NULL CHECK(provider IN('TEST','TIKTOK_SHOP')),label text NOT NULL CHECK(length(label) BETWEEN 1 AND 80),status text NOT NULL CHECK(status IN('NOT_CONNECTED','CONNECTED','NEEDS_ATTENTION','DISCONNECTED')),outbound_capable boolean NOT NULL DEFAULT false,account_scope uuid NOT NULL UNIQUE DEFAULT gen_random_uuid(),credential_reference uuid,created_by uuid NOT NULL REFERENCES users(id),send_interval_ms integer NOT NULL DEFAULT 1000 CHECK(send_interval_ms BETWEEN 1000 AND 60000),next_send_at timestamptz NOT NULL DEFAULT now(),created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now(),UNIQUE(workspace_id,id),FOREIGN KEY(workspace_id,credential_reference) REFERENCES outreach_channel_credentials(workspace_id,id),CHECK(NOT outbound_capable OR (provider='TEST' AND status='CONNECTED' AND credential_reference IS NULL)),CHECK(provider<>'TIKTOK_SHOP' OR (status='NOT_CONNECTED' AND NOT outbound_capable AND credential_reference IS NULL)));
CREATE TABLE outreach_creators(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),workspace_id uuid NOT NULL,channel_id uuid NOT NULL,creator_key text NOT NULL CHECK(length(creator_key) BETWEEN 1 AND 100),display_name text NOT NULL CHECK(length(display_name) BETWEEN 1 AND 120),username text NOT NULL CHECK(length(username)<=100),category_ids jsonb NOT NULL DEFAULT '[]',followers bigint,gmv numeric,gmv_currency text,units_sold bigint,video_views bigint,live_viewers bigint,engagement numeric,ordinal integer NOT NULL CHECK(ordinal>0),test_outcome text NOT NULL DEFAULT 'SENT' CHECK(test_outcome IN('SENT','RESTRICTED','FAILED','RETRY_ONCE','RETRY_ALWAYS','UNKNOWN_SENT','UNKNOWN_PENDING','RATE_LIMIT')),updated_at timestamptz NOT NULL DEFAULT now(),UNIQUE(workspace_id,id),UNIQUE(channel_id,creator_key),FOREIGN KEY(workspace_id,channel_id) REFERENCES outreach_channels(workspace_id,id));
CREATE TABLE outreach_campaigns(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),workspace_id uuid NOT NULL REFERENCES workspaces(id),billing_account_id uuid NOT NULL REFERENCES billing_accounts(id),channel_id uuid NOT NULL,name text NOT NULL CHECK(length(name) BETWEEN 1 AND 120),operation_key text NOT NULL,request_hash text NOT NULL CHECK(length(request_hash)=64),config_snapshot jsonb NOT NULL,config_hash text NOT NULL CHECK(length(config_hash)=64),recipient_hash text NOT NULL CHECK(length(recipient_hash)=64),selected_count integer NOT NULL CHECK(selected_count BETWEEN 1 AND 500),state text NOT NULL CHECK(state IN('QUEUED','SENDING','PAUSE_REQUESTED','PAUSED','CANCEL_REQUESTED','CANCELLED','COMPLETED','COMPLETED_WITH_ERRORS','FAILED','DELIVERY_UNKNOWN')),created_by uuid NOT NULL REFERENCES users(id),created_at timestamptz NOT NULL DEFAULT now(),frozen_at timestamptz NOT NULL DEFAULT now(),started_at timestamptz,completed_at timestamptz,paused_at timestamptz,cancel_requested_at timestamptz,updated_at timestamptz NOT NULL DEFAULT now(),UNIQUE(workspace_id,id),UNIQUE(workspace_id,operation_key),FOREIGN KEY(workspace_id,channel_id) REFERENCES outreach_channels(workspace_id,id));
CREATE TRIGGER outreach_campaign_account BEFORE INSERT OR UPDATE ON outreach_campaigns FOR EACH ROW EXECUTE FUNCTION bind_billing_account();
CREATE TABLE outreach_campaign_versions(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),workspace_id uuid NOT NULL,campaign_id uuid NOT NULL,version_number integer NOT NULL DEFAULT 1 CHECK(version_number=1),config_snapshot jsonb NOT NULL,config_hash text NOT NULL,created_by uuid NOT NULL REFERENCES users(id),created_at timestamptz NOT NULL DEFAULT now(),UNIQUE(workspace_id,id),UNIQUE(campaign_id,version_number),FOREIGN KEY(workspace_id,campaign_id) REFERENCES outreach_campaigns(workspace_id,id));
CREATE TRIGGER outreach_versions_immutable BEFORE UPDATE OR DELETE ON outreach_campaign_versions FOR EACH ROW EXECUTE FUNCTION billing_immutable();
CREATE TABLE outreach_recipients(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),workspace_id uuid NOT NULL,campaign_id uuid NOT NULL,channel_id uuid NOT NULL,version_id uuid NOT NULL,creator_key text NOT NULL,safe_snapshot jsonb NOT NULL,frozen_message text NOT NULL CHECK(length(frozen_message) BETWEEN 1 AND 2000),message_hash text NOT NULL CHECK(length(message_hash)=64),rank integer NOT NULL CHECK(rank BETWEEN 1 AND 500),created_at timestamptz NOT NULL DEFAULT now(),UNIQUE(workspace_id,id),UNIQUE(campaign_id,creator_key),FOREIGN KEY(workspace_id,campaign_id) REFERENCES outreach_campaigns(workspace_id,id),FOREIGN KEY(workspace_id,channel_id) REFERENCES outreach_channels(workspace_id,id),FOREIGN KEY(workspace_id,version_id) REFERENCES outreach_campaign_versions(workspace_id,id));
CREATE TRIGGER outreach_recipients_immutable BEFORE UPDATE OR DELETE ON outreach_recipients FOR EACH ROW EXECUTE FUNCTION billing_immutable();
CREATE TABLE outreach_deliveries(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),workspace_id uuid NOT NULL,campaign_id uuid NOT NULL,channel_id uuid NOT NULL,recipient_id uuid NOT NULL,creator_key text NOT NULL,state text NOT NULL DEFAULT 'PENDING' CHECK(state IN('PENDING','DISPATCHING','RETRYABLE','SENT','RESTRICTED','FAILED','DELIVERY_UNKNOWN','CANCELLED')),attempt_count integer NOT NULL DEFAULT 0 CHECK(attempt_count BETWEEN 0 AND 3),lease_id uuid,lease_expires_at timestamptz,available_at timestamptz NOT NULL DEFAULT now(),last_code text,started_at timestamptz,finished_at timestamptz,updated_at timestamptz NOT NULL DEFAULT now(),UNIQUE(workspace_id,id),UNIQUE(recipient_id),FOREIGN KEY(workspace_id,campaign_id) REFERENCES outreach_campaigns(workspace_id,id),FOREIGN KEY(workspace_id,channel_id) REFERENCES outreach_channels(workspace_id,id),FOREIGN KEY(workspace_id,recipient_id) REFERENCES outreach_recipients(workspace_id,id),CHECK((state='DISPATCHING')=(lease_id IS NOT NULL AND lease_expires_at IS NOT NULL)));
CREATE TABLE outreach_delivery_attempts(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),workspace_id uuid NOT NULL,delivery_id uuid NOT NULL,attempt_number integer NOT NULL CHECK(attempt_number BETWEEN 1 AND 3),lease_id uuid NOT NULL,state text NOT NULL DEFAULT 'STARTED' CHECK(state IN('STARTED','SENT','RESTRICTED','FAILED','RETRYABLE','DELIVERY_UNKNOWN')),safe_code text,started_at timestamptz NOT NULL DEFAULT now(),finished_at timestamptz,UNIQUE(workspace_id,id),UNIQUE(delivery_id,attempt_number),FOREIGN KEY(workspace_id,delivery_id) REFERENCES outreach_deliveries(workspace_id,id));
CREATE TABLE outreach_outbox(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),workspace_id uuid NOT NULL,campaign_id uuid NOT NULL,delivery_id uuid NOT NULL UNIQUE,state text NOT NULL DEFAULT 'PENDING' CHECK(state IN('PENDING','CLAIMED','COMPLETED')),available_at timestamptz NOT NULL DEFAULT now(),created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now(),UNIQUE(workspace_id,id),FOREIGN KEY(workspace_id,campaign_id) REFERENCES outreach_campaigns(workspace_id,id),FOREIGN KEY(workspace_id,delivery_id) REFERENCES outreach_deliveries(workspace_id,id));
CREATE INDEX outreach_outbox_ready ON outreach_outbox(available_at,id) WHERE state='PENDING';
CREATE TABLE outreach_contact_state(workspace_id uuid NOT NULL,channel_id uuid NOT NULL,creator_key text NOT NULL,do_not_contact boolean NOT NULL DEFAULT false,last_contacted_at timestamptz,last_delivery_id uuid,unknown_delivery_id uuid,contact_count integer NOT NULL DEFAULT 0 CHECK(contact_count>=0),updated_at timestamptz NOT NULL DEFAULT now(),PRIMARY KEY(channel_id,creator_key),FOREIGN KEY(workspace_id,channel_id) REFERENCES outreach_channels(workspace_id,id),FOREIGN KEY(workspace_id,last_delivery_id) REFERENCES outreach_deliveries(workspace_id,id),FOREIGN KEY(workspace_id,unknown_delivery_id) REFERENCES outreach_deliveries(workspace_id,id));
CREATE TABLE outreach_reservations(workspace_id uuid NOT NULL,channel_id uuid NOT NULL,creator_key text NOT NULL,delivery_id uuid NOT NULL UNIQUE,created_at timestamptz NOT NULL DEFAULT now(),PRIMARY KEY(channel_id,creator_key),FOREIGN KEY(workspace_id,channel_id) REFERENCES outreach_channels(workspace_id,id),FOREIGN KEY(workspace_id,delivery_id) REFERENCES outreach_deliveries(workspace_id,id));
CREATE TABLE outreach_channel_health(workspace_id uuid NOT NULL,channel_id uuid PRIMARY KEY,worker_id uuid NOT NULL,last_seen_at timestamptz NOT NULL DEFAULT now(),FOREIGN KEY(workspace_id,channel_id) REFERENCES outreach_channels(workspace_id,id));
-- Isolated fake-provider evidence, private server-only; never contains real contact/session credentials.
CREATE TABLE outreach_test_receipts(workspace_id uuid NOT NULL,channel_id uuid NOT NULL,delivery_id uuid PRIMARY KEY,status text NOT NULL CHECK(status IN('SENT','NOT_SENT','PENDING')),call_count integer NOT NULL DEFAULT 1 CHECK(call_count>0),simulated_sends integer NOT NULL DEFAULT 0 CHECK(simulated_sends BETWEEN 0 AND 1),updated_at timestamptz NOT NULL DEFAULT now(),FOREIGN KEY(workspace_id,channel_id) REFERENCES outreach_channels(workspace_id,id),FOREIGN KEY(workspace_id,delivery_id) REFERENCES outreach_deliveries(workspace_id,id));
CREATE TABLE outreach_campaign_billing(campaign_id uuid PRIMARY KEY,workspace_id uuid NOT NULL,billing_account_id uuid NOT NULL REFERENCES billing_accounts(id),quote_id uuid NOT NULL UNIQUE,price_version_id uuid NOT NULL REFERENCES price_versions(id),token_amount bigint NOT NULL CHECK(token_amount>0),per_send bigint NOT NULL CHECK(per_send>0),status text NOT NULL DEFAULT 'RESERVED' CHECK(status IN('RESERVED','SETTLED')),captured_tokens bigint NOT NULL DEFAULT 0 CHECK(captured_tokens>=0),released_tokens bigint NOT NULL DEFAULT 0 CHECK(released_tokens>=0),reserve_ledger_id uuid,capture_ledger_id uuid,release_ledger_id uuid,created_at timestamptz NOT NULL DEFAULT now(),settled_at timestamptz,UNIQUE(workspace_id,campaign_id),FOREIGN KEY(workspace_id,campaign_id) REFERENCES outreach_campaigns(workspace_id,id),FOREIGN KEY(workspace_id,quote_id) REFERENCES billing_quotes(workspace_id,id),FOREIGN KEY(workspace_id,reserve_ledger_id) REFERENCES token_ledger_entries(workspace_id,id),FOREIGN KEY(workspace_id,capture_ledger_id) REFERENCES token_ledger_entries(workspace_id,id),FOREIGN KEY(workspace_id,release_ledger_id) REFERENCES token_ledger_entries(workspace_id,id),CHECK((status='RESERVED' AND captured_tokens=0 AND released_tokens=0 AND settled_at IS NULL) OR (status='SETTLED' AND captured_tokens+released_tokens=token_amount AND settled_at IS NOT NULL)));
CREATE TRIGGER outreach_billing_account BEFORE INSERT OR UPDATE ON outreach_campaign_billing FOR EACH ROW EXECUTE FUNCTION bind_billing_account();
CREATE TABLE outreach_reconciliation_proofs(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),workspace_id uuid NOT NULL,delivery_id uuid NOT NULL,attempt_number integer NOT NULL CHECK(attempt_number BETWEEN 1 AND 3),provider_status text NOT NULL CHECK(provider_status IN('SENT','NOT_SENT')),proof_kind text NOT NULL CHECK(proof_kind='ISOLATED_ATOMIC_TEST_PROVIDER'),proof_hash text NOT NULL CHECK(length(proof_hash)=64),created_by uuid NOT NULL REFERENCES users(id),created_at timestamptz NOT NULL DEFAULT now(),UNIQUE(delivery_id,attempt_number),FOREIGN KEY(workspace_id,delivery_id) REFERENCES outreach_deliveries(workspace_id,id));
CREATE TRIGGER outreach_proof_immutable BEFORE UPDATE OR DELETE ON outreach_reconciliation_proofs FOR EACH ROW EXECUTE FUNCTION billing_immutable();
CREATE FUNCTION outreach_identity_guard() RETURNS trigger LANGUAGE plpgsql AS $$ DECLARE pending_count integer;active_count integer;unknown_count integer;sent_count integer;failed_count integer;total_count integer;expected text; BEGIN
 IF TG_OP='DELETE' THEN RAISE EXCEPTION 'Outreach history cannot be deleted';END IF;
 IF TG_TABLE_NAME='outreach_channels' THEN IF (NEW.id,NEW.workspace_id,NEW.provider,NEW.account_scope,NEW.created_by,NEW.created_at) IS DISTINCT FROM(OLD.id,OLD.workspace_id,OLD.provider,OLD.account_scope,OLD.created_by,OLD.created_at) THEN RAISE EXCEPTION 'Channel ownership cannot change';END IF;END IF;
 IF TG_TABLE_NAME='outreach_campaigns' THEN
  IF to_jsonb(NEW)-ARRAY['state','started_at','completed_at','paused_at','cancel_requested_at','updated_at'] IS DISTINCT FROM to_jsonb(OLD)-ARRAY['state','started_at','completed_at','paused_at','cancel_requested_at','updated_at'] OR (OLD.started_at IS NOT NULL AND NEW.started_at IS DISTINCT FROM OLD.started_at) OR (OLD.completed_at IS NOT NULL AND NEW.completed_at IS DISTINCT FROM OLD.completed_at) THEN RAISE EXCEPTION 'Frozen campaign cannot change';END IF;
  IF OLD.state IN('COMPLETED','COMPLETED_WITH_ERRORS','FAILED','CANCELLED') AND NEW.state<>OLD.state THEN RAISE EXCEPTION 'Terminal campaign cannot restart';END IF;
  IF NEW.state IS DISTINCT FROM OLD.state THEN
   SELECT count(*) FILTER(WHERE state IN('PENDING','RETRYABLE')),count(*) FILTER(WHERE state='DISPATCHING'),count(*) FILTER(WHERE state='DELIVERY_UNKNOWN'),count(*) FILTER(WHERE state='SENT'),count(*) FILTER(WHERE state='FAILED'),count(*) INTO pending_count,active_count,unknown_count,sent_count,failed_count,total_count FROM outreach_deliveries WHERE campaign_id=NEW.id;
   expected=CASE WHEN active_count>0 THEN CASE WHEN NEW.cancel_requested_at IS NOT NULL THEN 'CANCEL_REQUESTED' WHEN NEW.paused_at IS NOT NULL THEN 'PAUSE_REQUESTED' ELSE 'SENDING' END WHEN unknown_count>0 THEN 'DELIVERY_UNKNOWN' WHEN NEW.cancel_requested_at IS NOT NULL THEN 'CANCELLED' WHEN NEW.paused_at IS NOT NULL AND pending_count>0 THEN 'PAUSED' WHEN pending_count>0 THEN 'QUEUED' WHEN sent_count=total_count THEN 'COMPLETED' WHEN failed_count=total_count THEN 'FAILED' ELSE 'COMPLETED_WITH_ERRORS' END;
   IF NEW.state<>expected THEN RAISE EXCEPTION 'Campaign state does not match durable deliveries';END IF;
  END IF;
 END IF;
 IF TG_TABLE_NAME='outreach_deliveries' THEN
  IF to_jsonb(NEW)-ARRAY['state','attempt_count','lease_id','lease_expires_at','available_at','last_code','started_at','finished_at','updated_at'] IS DISTINCT FROM to_jsonb(OLD)-ARRAY['state','attempt_count','lease_id','lease_expires_at','available_at','last_code','started_at','finished_at','updated_at'] THEN RAISE EXCEPTION 'Delivery identity cannot change';END IF;
  IF OLD.state IN('SENT','RESTRICTED','FAILED','CANCELLED') AND NEW.state<>OLD.state THEN RAISE EXCEPTION 'Terminal delivery cannot resend';END IF;
  IF NEW.state IS DISTINCT FROM OLD.state AND NOT((OLD.state IN('PENDING','RETRYABLE') AND NEW.state IN('DISPATCHING','FAILED','CANCELLED')) OR (OLD.state='DISPATCHING' AND NEW.state IN('SENT','RESTRICTED','FAILED','RETRYABLE','DELIVERY_UNKNOWN','CANCELLED')) OR (OLD.state='DELIVERY_UNKNOWN' AND NEW.state IN('SENT','RETRYABLE','FAILED','CANCELLED'))) THEN RAISE EXCEPTION 'Invalid delivery transition';END IF;
  IF NEW.attempt_count<>OLD.attempt_count+(CASE WHEN NEW.state='DISPATCHING' AND OLD.state IN('PENDING','RETRYABLE') THEN 1 ELSE 0 END) OR (OLD.state='DISPATCHING' AND NEW.state='DISPATCHING' AND (NEW.lease_id,NEW.lease_expires_at) IS DISTINCT FROM(OLD.lease_id,OLD.lease_expires_at)) THEN RAISE EXCEPTION 'Invalid attempt or lease transition';END IF;
  IF OLD.state='DELIVERY_UNKNOWN' AND NEW.state<>OLD.state AND NOT EXISTS(SELECT 1 FROM outreach_reconciliation_proofs WHERE workspace_id=OLD.workspace_id AND delivery_id=OLD.id AND attempt_number=OLD.attempt_count AND provider_status=CASE WHEN NEW.state='SENT' THEN 'SENT' ELSE 'NOT_SENT' END) THEN RAISE EXCEPTION 'Unknown outcome requires provider proof';END IF;
 END IF;
 IF TG_TABLE_NAME='outreach_delivery_attempts' THEN IF (to_jsonb(NEW)-ARRAY['state','safe_code','finished_at'] IS DISTINCT FROM to_jsonb(OLD)-ARRAY['state','safe_code','finished_at'] OR (OLD.state<>'STARTED' AND NEW IS DISTINCT FROM OLD)) THEN RAISE EXCEPTION 'Attempt history cannot change';END IF;END IF;
 IF TG_TABLE_NAME='outreach_campaign_billing' THEN IF (to_jsonb(NEW)-ARRAY['status','captured_tokens','released_tokens','reserve_ledger_id','capture_ledger_id','release_ledger_id','settled_at'] IS DISTINCT FROM to_jsonb(OLD)-ARRAY['status','captured_tokens','released_tokens','reserve_ledger_id','capture_ledger_id','release_ledger_id','settled_at'] OR (OLD.status='SETTLED' AND NEW IS DISTINCT FROM OLD) OR (OLD.reserve_ledger_id IS NOT NULL AND NEW.reserve_ledger_id IS DISTINCT FROM OLD.reserve_ledger_id)) THEN RAISE EXCEPTION 'Campaign billing cannot change';END IF;END IF;
 RETURN NEW;
END $$;
CREATE TRIGGER outreach_channel_identity BEFORE UPDATE OR DELETE ON outreach_channels FOR EACH ROW EXECUTE FUNCTION outreach_identity_guard();
CREATE TRIGGER outreach_campaign_identity BEFORE UPDATE OR DELETE ON outreach_campaigns FOR EACH ROW EXECUTE FUNCTION outreach_identity_guard();
CREATE TRIGGER outreach_delivery_identity BEFORE UPDATE OR DELETE ON outreach_deliveries FOR EACH ROW EXECUTE FUNCTION outreach_identity_guard();
CREATE TRIGGER outreach_attempt_identity BEFORE UPDATE OR DELETE ON outreach_delivery_attempts FOR EACH ROW EXECUTE FUNCTION outreach_identity_guard();
CREATE TRIGGER outreach_billing_identity BEFORE UPDATE OR DELETE ON outreach_campaign_billing FOR EACH ROW EXECUTE FUNCTION outreach_identity_guard();
CREATE FUNCTION outreach_references_required() RETURNS trigger LANGUAGE plpgsql AS $$ DECLARE c outreach_campaigns;b outreach_campaign_billing;q billing_quotes;BEGIN
 IF TG_TABLE_NAME='outreach_campaigns' THEN SELECT * INTO c FROM outreach_campaigns WHERE id=NEW.id;ELSE SELECT * INTO c FROM outreach_campaigns WHERE id=NEW.campaign_id;END IF;SELECT * INTO b FROM outreach_campaign_billing WHERE campaign_id=c.id;SELECT * INTO q FROM billing_quotes WHERE id=b.quote_id;
 IF c.id IS NULL OR b.campaign_id IS NULL OR b.workspace_id<>c.workspace_id OR b.billing_account_id<>c.billing_account_id OR q.operation<>'OUTREACH' OR q.token_amount<>b.token_amount OR q.price_version_id<>b.price_version_id OR q.request_hash<>c.request_hash OR q.input_hash<>c.recipient_hash OR b.token_amount<>b.per_send*c.selected_count OR (SELECT count(*) FROM outreach_recipients WHERE campaign_id=c.id)<>c.selected_count OR (SELECT count(*) FROM outreach_deliveries WHERE campaign_id=c.id)<>c.selected_count OR (SELECT count(*) FROM outreach_outbox WHERE campaign_id=c.id)<>c.selected_count OR NOT EXISTS(SELECT 1 FROM token_ledger_entries WHERE id=b.reserve_ledger_id AND quote_id=b.quote_id AND entry_type='RESERVE') THEN RAISE EXCEPTION 'Outreach admission must be atomic';END IF;
 IF b.status='SETTLED' AND ((b.captured_tokens>0 AND NOT EXISTS(SELECT 1 FROM token_ledger_entries WHERE id=b.capture_ledger_id AND quote_id=b.quote_id AND entry_type='CAPTURE' AND reserved_delta=-b.captured_tokens)) OR (b.released_tokens>0 AND NOT EXISTS(SELECT 1 FROM token_ledger_entries WHERE id=b.release_ledger_id AND quote_id=b.quote_id AND entry_type='RELEASE' AND available_delta=b.released_tokens))) THEN RAISE EXCEPTION 'Outreach settlement must be atomic';END IF;RETURN NULL;
END $$;
CREATE CONSTRAINT TRIGGER outreach_billing_required AFTER INSERT OR UPDATE ON outreach_campaign_billing DEFERRABLE INITIALLY DEFERRED FOR EACH ROW EXECUTE FUNCTION outreach_references_required();
CREATE CONSTRAINT TRIGGER outreach_campaign_atomic AFTER INSERT ON outreach_campaigns DEFERRABLE INITIALLY DEFERRED FOR EACH ROW EXECUTE FUNCTION outreach_references_required();
-- Extend only the existing amount shape; all historic Job/payment cases remain byte-identical.
DO $$ DECLARE n text;definition text;BEGIN
 SELECT conname,pg_get_constraintdef(oid) INTO n,definition FROM pg_constraint WHERE conrelid='token_ledger_entries'::regclass AND contype='c' AND pg_get_constraintdef(oid) LIKE '%entry_type%RESERVE%' AND pg_get_constraintdef(oid) LIKE '%job_id%';
 IF n IS NULL THEN RAISE EXCEPTION 'Certified ledger shape not found';END IF;
 EXECUTE format('ALTER TABLE token_ledger_entries DROP CONSTRAINT %I',n);
 definition=substring(definition FROM 8 FOR length(definition)-8);
 EXECUTE 'ALTER TABLE token_ledger_entries ADD CONSTRAINT ledger_amount_shape CHECK (('||definition||') OR (job_id IS NULL AND payment_id IS NULL AND quote_id IS NOT NULL AND ((entry_type=''RESERVE'' AND available_delta<0 AND reserved_delta=-available_delta) OR (entry_type=''CAPTURE'' AND available_delta=0 AND reserved_delta<0) OR (entry_type=''RELEASE'' AND available_delta>0 AND reserved_delta=-available_delta))))';
END $$;
CREATE UNIQUE INDEX ledger_outreach_once ON token_ledger_entries(quote_id,entry_type) WHERE job_id IS NULL AND quote_id IS NOT NULL AND entry_type IN('RESERVE','CAPTURE','RELEASE');

CREATE OR REPLACE FUNCTION apply_token_ledger() RETURNS trigger LANGUAGE plpgsql AS $$
DECLARE b job_billing; p payments; j jobs; q billing_quotes; cb outreach_campaign_billing; oc outreach_campaigns; sent_tokens bigint;
BEGIN
 PERFORM 1 FROM billing_account_wallets WHERE billing_account_id=NEW.billing_account_id FOR UPDATE;
 IF NOT FOUND THEN RAISE EXCEPTION 'Account wallet not found';END IF;
 IF NEW.job_id IS NULL AND NEW.quote_id IS NOT NULL AND NEW.entry_type IN('RESERVE','CAPTURE','RELEASE') THEN
  SELECT * INTO cb FROM outreach_campaign_billing WHERE quote_id=NEW.quote_id AND workspace_id=NEW.workspace_id AND billing_account_id=NEW.billing_account_id;
  SELECT * INTO oc FROM outreach_campaigns WHERE id=cb.campaign_id;
  IF cb.campaign_id IS NULL OR cb.status<>'RESERVED' THEN RAISE EXCEPTION 'Campaign billing unavailable';END IF;
  IF NEW.entry_type='RESERVE' THEN
   IF NEW.reserved_delta<>cb.token_amount OR oc.state<>'QUEUED' THEN RAISE EXCEPTION 'Invalid campaign reservation';END IF;
  ELSE
   IF oc.state NOT IN('COMPLETED','COMPLETED_WITH_ERRORS','FAILED','CANCELLED') OR EXISTS(SELECT 1 FROM outreach_deliveries WHERE campaign_id=oc.id AND state IN('PENDING','DISPATCHING','RETRYABLE','DELIVERY_UNKNOWN')) THEN RAISE EXCEPTION 'Campaign outcome not definite';END IF;
   SELECT count(*)*cb.per_send INTO sent_tokens FROM outreach_deliveries WHERE campaign_id=oc.id AND state='SENT';
   IF (NEW.entry_type='CAPTURE' AND -NEW.reserved_delta<>sent_tokens) OR (NEW.entry_type='RELEASE' AND NEW.available_delta<>cb.token_amount-sent_tokens) THEN RAISE EXCEPTION 'Campaign settlement amount mismatch';END IF;
  END IF;
 END IF;
 IF NEW.job_id IS NOT NULL THEN
  SELECT * INTO b FROM job_billing WHERE job_id=NEW.job_id AND workspace_id=NEW.workspace_id AND billing_account_id=NEW.billing_account_id;
  SELECT * INTO j FROM jobs WHERE id=NEW.job_id;
  IF abs(CASE WHEN NEW.entry_type='CAPTURE' THEN NEW.reserved_delta ELSE NEW.available_delta END)<>b.token_amount THEN RAISE EXCEPTION 'Job amount mismatch'; END IF;
  IF NEW.entry_type='RESERVE' AND (b.status<>'RESERVED' OR NEW.quote_id<>b.quote_id OR j.status<>'QUEUED') THEN RAISE EXCEPTION 'Invalid reservation'; END IF;
  IF NEW.entry_type='CAPTURE' AND (b.status<>'RESERVED' OR j.status<>'SUCCEEDED' OR NOT EXISTS(SELECT 1 FROM content_publications WHERE job_id=j.id) OR NOT EXISTS(SELECT 1 FROM job_artifacts a JOIN job_attempts t ON t.id=a.attempt_id WHERE a.job_id=j.id AND a.status='READY' AND t.status='SUCCEEDED' AND t.attempt_number=j.attempt_count)) THEN RAISE EXCEPTION 'Invalid capture'; END IF;
  IF NEW.entry_type='RELEASE' AND (b.status<>'RESERVED' OR j.status NOT IN('FAILED','CANCELLED') OR EXISTS(SELECT 1 FROM provider_executions WHERE job_id=j.id AND state IN('SUBMITTING','SUBMISSION_UNKNOWN','SUBMITTED','RUNNING','OUTPUT_PENDING'))) THEN RAISE EXCEPTION 'Outcome not definite'; END IF;
  IF NEW.entry_type='REFUND' AND b.status<>'CAPTURED' THEN RAISE EXCEPTION 'Invalid token refund'; END IF;
 END IF;
 IF NEW.entry_type='PURCHASE' THEN
  SELECT * INTO p FROM payments WHERE id=NEW.payment_id AND workspace_id=NEW.workspace_id AND billing_account_id=NEW.billing_account_id;
  IF p.status<>'PAID' OR p.token_amount<>NEW.available_delta THEN RAISE EXCEPTION 'Invalid purchase'; END IF;
 END IF;
 UPDATE billing_account_wallets SET available_tokens=available_tokens+NEW.available_delta,reserved_tokens=reserved_tokens+NEW.reserved_delta,updated_at=now() WHERE billing_account_id=NEW.billing_account_id;
 RETURN NEW;
END $$;
DO $$ DECLARE realm text;catalog uuid;version uuid;BEGIN FOREACH realm IN ARRAY ARRAY['TEST','PRODUCTION'] LOOP
 catalog=gen_random_uuid();version=gen_random_uuid();INSERT INTO price_catalogs(id,operation,realm) VALUES(catalog,'OUTREACH',realm);
 INSERT INTO price_versions(id,catalog_id,version_number,label,rules) VALUES(version,catalog,1,CASE WHEN realm='TEST' THEN 'TEST INTERNAL BETA Outreach · 10 Tokens per confirmed send' ELSE 'INTERNAL BETA Outreach · 10 Tokens per confirmed send' END,jsonb_build_object('policyVersion','outreach-confirmed-send-v1','approval','INTERNAL_BETA','perSuccessfulSend','10','maxRecipients',500));UPDATE price_catalogs SET active_version_id=version WHERE id=catalog;
 END LOOP;END $$;

ALTER TABLE outreach_campaign_versions ADD UNIQUE(workspace_id,campaign_id,id);
ALTER TABLE outreach_recipients ADD FOREIGN KEY(workspace_id,campaign_id,version_id) REFERENCES outreach_campaign_versions(workspace_id,campaign_id,id),ADD UNIQUE(workspace_id,campaign_id,channel_id,id);
ALTER TABLE outreach_deliveries ADD FOREIGN KEY(workspace_id,campaign_id,channel_id,recipient_id) REFERENCES outreach_recipients(workspace_id,campaign_id,channel_id,id),ADD UNIQUE(workspace_id,campaign_id,id);
ALTER TABLE outreach_outbox ADD FOREIGN KEY(workspace_id,campaign_id,delivery_id) REFERENCES outreach_deliveries(workspace_id,campaign_id,id);

ALTER TABLE outreach_campaigns ADD UNIQUE(workspace_id,channel_id,id);
ALTER TABLE outreach_recipients ADD FOREIGN KEY(workspace_id,channel_id,campaign_id) REFERENCES outreach_campaigns(workspace_id,channel_id,id);
ALTER TABLE outreach_deliveries ADD UNIQUE(workspace_id,channel_id,creator_key,id),ADD UNIQUE(workspace_id,channel_id,id);
ALTER TABLE outreach_reservations ADD FOREIGN KEY(workspace_id,channel_id,creator_key,delivery_id) REFERENCES outreach_deliveries(workspace_id,channel_id,creator_key,id);
ALTER TABLE outreach_contact_state ADD FOREIGN KEY(workspace_id,channel_id,creator_key,last_delivery_id) REFERENCES outreach_deliveries(workspace_id,channel_id,creator_key,id),ADD FOREIGN KEY(workspace_id,channel_id,creator_key,unknown_delivery_id) REFERENCES outreach_deliveries(workspace_id,channel_id,creator_key,id);
ALTER TABLE outreach_test_receipts ADD FOREIGN KEY(workspace_id,channel_id,delivery_id) REFERENCES outreach_deliveries(workspace_id,channel_id,id);

-- Deferred checks also prevent appending recipients or intent to an already frozen campaign.
CREATE CONSTRAINT TRIGGER outreach_recipient_atomic AFTER INSERT ON outreach_recipients DEFERRABLE INITIALLY DEFERRED FOR EACH ROW EXECUTE FUNCTION outreach_references_required();
CREATE CONSTRAINT TRIGGER outreach_delivery_atomic AFTER INSERT ON outreach_deliveries DEFERRABLE INITIALLY DEFERRED FOR EACH ROW EXECUTE FUNCTION outreach_references_required();
CREATE CONSTRAINT TRIGGER outreach_outbox_atomic AFTER INSERT ON outreach_outbox DEFERRABLE INITIALLY DEFERRED FOR EACH ROW EXECUTE FUNCTION outreach_references_required();
ALTER TABLE outreach_recipients ADD UNIQUE(workspace_id,campaign_id,channel_id,creator_key,id);
ALTER TABLE outreach_deliveries ADD FOREIGN KEY(workspace_id,campaign_id,channel_id,creator_key,recipient_id) REFERENCES outreach_recipients(workspace_id,campaign_id,channel_id,creator_key,id);
CREATE INDEX outreach_campaign_history ON outreach_campaigns(workspace_id,created_at DESC);
CREATE INDEX outreach_delivery_counts ON outreach_deliveries(campaign_id,state);
CREATE INDEX outreach_outbox_campaign ON outreach_outbox(campaign_id);
