import {test,expect,chromium} from '@playwright/test';
import {fixture,close,evidence,render,base} from './support';
import {observe,mediaChecks} from '../stabilization/browser-checks';
for(const channel of ['chrome','msedge'] as const)test(`J: ${channel} editor in desktop/tablet/mobile and light/dark renders a customer variation`,async()=>{
 test.setTimeout(300000);const f=await fixture(),browser=await chromium.launch({channel}),results=[];try{
  for(const colorScheme of ['light','dark'] as const)for(const viewport of [{width:1440,height:1000},{width:768,height:1024},{width:390,height:844}]){
   const context=await browser.newContext({baseURL:base,viewport,colorScheme,storageState:await f.c.storageState()}),page=await context.newPage(),o=await observe(page);try{await page.goto(`/clipper/edit/${f.contentId}`);await expect(page.getByRole('heading',{name:'Creative setup'})).toBeVisible();await mediaChecks(page);await expect(page.getByRole('button',{name:'Render new variation'})).toBeEnabled();await expect(page.getByText('Internal beta price',{exact:false})).toBeVisible();
    await page.getByLabel('Text style',{exact:true}).selectOption('creator_bold_pop');await page.getByLabel('Color grade',{exact:true}).selectOption('warm');await page.getByLabel('Black bars',{exact:true}).check();await page.getByLabel('Automatic top-bar hook',{exact:true}).check();await page.getByLabel('Black bars',{exact:true}).uncheck();expect(await page.getByLabel('Automatic top-bar hook',{exact:true}).isChecked()).toBe(false);await expect(page.getByRole('button',{name:'Render new variation'})).toBeEnabled();
    const overflow=await page.evaluate(()=>({viewport:innerWidth,body:document.documentElement.scrollWidth,editor:document.querySelector('.variation-editor-layout')!.getBoundingClientRect().width}));expect(overflow.body).toBeLessThanOrEqual(overflow.viewport+1);
    const style=await page.locator('.variation-preview-panel').evaluate(e=>getComputedStyle(e).backgroundColor);if(colorScheme==='dark')expect(style).toBe('rgb(30, 37, 50)');
    const contrast=await page.locator('.token-quote strong').first().evaluate(e=>{const rgb=(s:string)=>s.match(/[\d.]+/g)!.slice(0,3).map(Number),luminance=(r:number[])=>r.map(n=>{const c=n/255;return c<=.04045?c/12.92:((c+.055)/1.055)**2.4;}).reduce((s,v,i)=>s+v*[.2126,.7152,.0722][i],0);let bg=e.parentElement!;while(getComputedStyle(bg).backgroundColor==='rgba(0, 0, 0, 0)')bg=bg.parentElement!;const a=luminance(rgb(getComputedStyle(e).color)),b=luminance(rgb(getComputedStyle(bg).backgroundColor));return (Math.max(a,b)+.05)/(Math.min(a,b)+.05);});expect(contrast,'Readable token quote contrast').toBeGreaterThanOrEqual(4.5);await page.evaluate(()=>scrollTo(0,0));
    await page.screenshot({path:`docs/phase-d-evidence/editor-${channel}-${viewport.width}-${colorScheme}.png`,fullPage:true});
    if(viewport.width===1440&&colorScheme==='light'){await page.getByLabel('Variation name',{exact:true}).fill(`${channel} edit`);await expect(page.getByRole('button',{name:'Render new variation'})).toBeEnabled();const stableKey=await page.evaluate(()=>JSON.parse(sessionStorage.getItem(Object.keys(sessionStorage).find(k=>k.startsWith('clipper-edit:'))!)!).key);await page.reload();await expect(page.getByLabel('Variation name',{exact:true})).toHaveValue(`${channel} edit`);expect(await page.evaluate(()=>JSON.parse(sessionStorage.getItem(Object.keys(sessionStorage).find(k=>k.startsWith('clipper-edit:'))!)!).key)).toBe(stableKey);await expect(page.getByRole('button',{name:'Render new variation'})).toBeEnabled();await page.getByRole('button',{name:'Render new variation'}).click();await expect(page).toHaveURL(/\/clipper\/[0-9a-f-]+$/);const id=new URL(page.url()).pathname.split('/').at(-1)!;const output=await render(f,id);await expect(page.getByText('Completed:',{exact:false})).toBeVisible({timeout:20000});await expect(page.getByText('Started:',{exact:false})).toBeVisible();await expect(page.getByRole('link',{name:'Edit / Create variation'})).toBeVisible();await page.goto(`/content/${output.content.id}`);await mediaChecks(page);await expect(page.getByRole('heading',{name:'Original and variations'})).toBeVisible();await expect(page.getByRole('link',{name:'Edit / Create variation'})).toBeVisible();await expect(page.getByRole('link',{name:'Original clip'})).toBeVisible();}
    await o.finish();expect(o.crashes).toEqual([]);expect(o.consoleErrors).toEqual([]);expect(o.leaks).toEqual([]);expect(o.network).toEqual([]);results.push({viewport,colorScheme,overflow,privatePreview:true,tokenQuoteContrast:contrast,consoleErrors:0,pageErrors:0,credentialLeaks:0,networkErrors:0});
   }finally{await context.close();}
  }
  await evidence(`variation-editor-${channel}`,{status:'PASS',channel,actualInstalledBrowser:true,checks:results,customerFormSubmission:true,realWorkerOutput:true});
 }finally{await browser.close();await close(f);}
});
