import {test,expect} from '@playwright/test';
import {mkdir,readFile,writeFile} from 'node:fs/promises';
import {resolve} from 'node:path';
import {fixture,variation,entries,originalUnchanged,close,dispatch,evidence,provision,worker,launch,killOwned,marker} from './support';
import {lease,type Claim} from '../clipper-helpers';
import {publishJob} from '../content-helpers';
for(const stage of ['RENDERING_VARIATION','DURING_FFMPEG','UPLOADING_VARIATION','UPLOAD_FINALIZE'])test(`variation worker process loss at ${stage} recovers under the same reservation`,async()=>{
 test.setTimeout(240000);const f=await fixture(),p=provision(),w=await worker(p.credential),work=resolve('../worker-agent/data',`phase-d-${process.env.STABILIZATION_RUN_ID}`,stage);await mkdir(work,{recursive:true});let first:ReturnType<typeof launch>|undefined,next:ReturnType<typeof launch>|undefined;
 try{const v=await variation(f.c,f.workspaceId,f.contentId,f.versionId,{colorGrade:'vivid'});dispatch();first=launch(p.credential,work,stage);let claim:Claim|undefined,paused:Record<string,unknown>|null=null;
  await expect.poll(async()=>{const r=(await f.db.query("SELECT l.job_id AS \"jobId\",l.attempt_id AS \"attemptId\",l.id AS \"leaseId\",l.fencing_token::text AS \"fencingToken\" FROM worker_leases l WHERE job_id=$1 AND status='ACTIVE'",[v.id])).rows[0];if(!r)return false;claim=r;paused=await marker(work,v.id,r.attemptId);return !!paused;},{timeout:90000,message:'Owned worker reached real interruption stage'}).toBe(true);
  if(stage==='DURING_FFMPEG')expect(paused!.realFfmpegChildRunning).toBe(true);if(stage==='UPLOAD_FINALIZE')expect(paused!.realClipPutCompleted).toBe(true);
  killOwned(first.child);await f.db.query("UPDATE worker_leases SET expires_at=now()-interval '1 second' WHERE id=$1",[claim!.leaseId]);dispatch();expect((await w.post(`/api/worker/jobs/${v.id}/progress`,{data:{...lease(claim!),sequence:999,percent:99,stage:'FINALIZING_VARIATION',message:'late'}})).status()).toBe(409);expect((await w.post(`/api/worker/jobs/${v.id}/complete`,{data:{...lease(claim!),artifactIds:[]}})).status()).toBe(409);
  await new Promise(r=>setTimeout(r,1200));dispatch();next=launch(p.credential,work);await expect.poll(async()=>(await f.db.query('SELECT status FROM jobs WHERE id=$1',[v.id])).rows[0].status,{timeout:90000}).toBe('SUCCEEDED');
  const attempts=(await f.db.query('SELECT id,status FROM job_attempts WHERE job_id=$1 ORDER BY attempt_number',[v.id])).rows;expect(attempts.map(a=>a.status)).toEqual(['LOST','SUCCEEDED']);let metrics:Record<string,number>|undefined;await expect.poll(async()=>{try{metrics=JSON.parse(await readFile(resolve(work,v.id,attempts[1].id,'receipt.json'),'utf8')).metrics;return true;}catch{return false;}}).toBe(true);expect(metrics!.transcription).toBe(0);expect(metrics!.analyzer).toBe(0);
  publishJob(f.workspaceId,v.id,3);for(let n=0;n<3;n++)dispatch();expect(await entries(f.db,v.id)).toEqual([{entry_type:'CAPTURE',count:1},{entry_type:'RESERVE',count:1}]);expect((await f.db.query('SELECT count(*)::int n FROM content_versions WHERE job_id=$1',[v.id])).rows[0].n).toBe(1);expect((await f.db.query('SELECT count(*)::int n FROM clipper_variations WHERE render_job_id=$1 AND result_content_id IS NOT NULL',[v.id])).rows[0].n).toBe(1);await originalUnchanged(f);
  await evidence(`variation-restart-${stage.toLowerCase()}`,{status:'PASS',stage,realWorkerProcessKilled:true,realFfmpegChild:stage==='DURING_FFMPEG',realClipPutBeforeKill:stage==='UPLOAD_FINALIZE',attempts:['LOST','SUCCEEDED'],oldLeaseProgress:409,oldLeaseComplete:409,metrics,transcriptionCalls:0,analysisCalls:0,reserves:1,captures:1,contentVersions:1,originalUnchanged:true});
 }finally{killOwned(first?.child);killOwned(next?.child);await writeFile(`${process.env.STABILIZATION_LOG_DIR}/${stage}.log`,`${first?.output()||''}\n${next?.output()||''}`);await f.db.query("UPDATE workers SET status='DISABLED' WHERE id=$1",[p.workerId]);await w.dispose();await close(f);}
});
test('variation retries stop at three lost attempts and release once',async()=>{const f=await fixture(),p=provision(),w=await worker(p.credential);try{const v=await variation(f.c,f.workspaceId,f.contentId,f.versionId);for(let i=0;i<3;i++){await w.post('/api/worker/heartbeat',{data:{agentVersion:'phase-d-bounds',pipelineVersion:'clipper-variation-v1',availableSlots:1,activeLeaseIds:[],clipperHealth:{transcriberAvailable:false,ffmpegAvailable:true,gpuAvailable:false,freeDiskBytes:20*1024**3,variationRenderAvailable:true}}});dispatch();const c=(await (await w.post('/api/worker/claim',{data:{}})).json()).claim as Claim;expect(c.jobId).toBe(v.id);await f.db.query("UPDATE worker_leases SET expires_at=now()-interval '1 second' WHERE id=$1",[c.leaseId]);dispatch();if(i<2)await new Promise(r=>setTimeout(r,2200));}for(let n=0;n<3;n++)dispatch();expect((await f.db.query('SELECT status,attempt_count FROM jobs WHERE id=$1',[v.id])).rows[0]).toEqual({status:'FAILED',attempt_count:3});expect(await entries(f.db,v.id)).toEqual([{entry_type:'RELEASE',count:1},{entry_type:'RESERVE',count:1}]);await originalUnchanged(f);await evidence('variation-retry-bounds',{status:'PASS',maxAttempts:3,fourthAttempt:false,reserve:1,release:1,originalUnchanged:true});}finally{await f.db.query("UPDATE workers SET status='DISABLED' WHERE id=$1",[p.workerId]);await w.dispose();await close(f);}});
