import {test,expect,chromium} from '@playwright/test';
import {fixture,close,base,render,entries,evidence,dispatch} from './support';
test('lost response and browser refresh replay one variation; a confirmed draft can start a new intent',async()=>{
 test.setTimeout(180000);const f=await fixture(),browser=await chromium.launch({channel:'chrome'}),context=await browser.newContext({baseURL:base,storageState:await f.c.storageState()}),page=await context.newPage();let id='';try{
  await page.goto(`/clipper/edit/${f.contentId}`);await expect(page.getByRole('button',{name:'Render new variation'})).toBeEnabled();const key=await page.evaluate(()=>JSON.parse(sessionStorage.getItem(Object.keys(sessionStorage).find(k=>k.startsWith('clipper-edit:'))!)!).key);
  await page.route('**/clipper/variations',async route=>{const r=await route.fetch();expect(r.status()).toBe(201);id=(await r.json()).job.id;await route.abort('failed');});await page.getByRole('button',{name:'Render new variation'}).click();await expect(page.locator('.variation-submit .notice.error')).toContainText('The service did not respond.');await page.unrouteAll({behavior:'wait'});await page.reload();await expect(page.getByRole('button',{name:'Render new variation'})).toBeEnabled();expect(await page.evaluate(()=>JSON.parse(sessionStorage.getItem(Object.keys(sessionStorage).find(k=>k.startsWith('clipper-edit:'))!)!).key)).toBe(key);
  await page.getByRole('button',{name:'Render new variation'}).click();await expect(page).toHaveURL(new RegExp(`/clipper/${id}$`));const output=await render(f,id);expect(output.metrics.render).toBe(1);expect(await entries(f.db,id)).toEqual([{entry_type:'CAPTURE',count:1},{entry_type:'RESERVE',count:1}]);expect((await f.db.query('SELECT count(*)::int n FROM clipper_variations WHERE root_content_id=$1',[f.contentId])).rows[0].n).toBe(1);
  await page.goto(`/jobs/${id}`);await expect(page).toHaveURL(new RegExp(`/clipper/${id}$`));await page.goto(`/clipper/edit/${f.contentId}`);await expect(page.getByRole('link',{name:'Open status',exact:true})).toHaveAttribute('href',`/clipper/${id}`);await expect(page.getByRole('button',{name:'Render new variation'})).toBeDisabled();await page.getByRole('button',{name:'Start another variation from this draft'}).click();await expect(page.getByRole('button',{name:'Render new variation'})).toBeEnabled();const newKey=await page.evaluate(()=>JSON.parse(sessionStorage.getItem(Object.keys(sessionStorage).find(k=>k.startsWith('clipper-edit:'))!)!).key);expect(newKey).not.toBe(key);
  await page.getByRole('button',{name:'Render new variation'}).click();await expect(page).toHaveURL(/\/clipper\/[0-9a-f-]+$/);const another=new URL(page.url()).pathname.split('/').at(-1)!;expect(another).not.toBe(id);await f.c.post(`/api/workspaces/${f.workspaceId}/jobs/${another}/cancel`);dispatch();
  await evidence('variation-lost-response',{status:'PASS',realBrowser:'chrome',responseAbortedAfterCommittedAdmission:true,refreshKeepsIdempotencyIdentity:true,jobsForOriginalIntent:1,rendersForOriginalIntent:1,reservesForOriginalIntent:1,capturesForOriginalIntent:1,knownDraftLinksToSavedJob:true,explicitAnotherIntentUsesNewKey:true,genericJobLinkRestoresClipperPage:true});
 }finally{await context.close();await browser.close();await close(f);}
});
