import {expect,request,type APIRequestContext} from '@playwright/test';
import {spawn,execFileSync,type ChildProcess} from 'node:child_process';
import {readFile,mkdir,writeFile,access} from 'node:fs/promises';
import {resolve} from 'node:path';
import {randomUUID,createHash} from 'node:crypto';
import {owner,source,submit,dispatch} from '../clipper-helpers';
import {fixtureClips,publishJob} from '../content-helpers';
import {fundFixture} from '../billing-helpers';
import {database,base,evidence} from '../stabilization/support';
import {defaultVariationSettings,type VariationSettings} from '../../src/lib/clipper-variation-settings';
export {database,base,evidence,dispatch};
if(!process.env.STABILIZATION_RUN_ID||!/^\/phase_[de]_[0-9]+_[a-f0-9]+$/.test(new URL(process.env.TEST_DATABASE_URL!).pathname)||! /^phase-[de]-\d+-[a-f0-9]+$/.test(process.env.OBJECT_STORAGE_BUCKET||''))throw new Error('Owned Phase D isolation required');
export async function fixture(amount='10000'){
 const email=`phase-d-${randomUUID()}@example.test`,a=await owner(email,false),db=await database();
 try{fundFixture(a.workspaceId,amount);const s=await source(a.c,a.workspaceId),r=await submit(a.c,a.workspaceId,s.id,randomUUID(),{captions:false});expect(r.status()).toBe(201);const jobId=(await r.json()).job.id;await fixtureClips(a.c,a.workspaceId,db,{jobId,source:s});const id=publishJob(a.workspaceId,jobId)[0][0] as string;dispatch();const v=(await db.query('SELECT * FROM content_versions WHERE content_item_id=$1',[id])).rows[0];return {...a,email,db,source:s,originalJobId:jobId,contentId:id,versionId:v.id as string,artifactId:v.artifact_id as string,originalVersion:JSON.stringify(v)};}catch(e){await a.c.dispose();await db.end();throw e;}
}
export async function quote(c:APIRequestContext,w:string,id:string,v:string,settings:Partial<VariationSettings>={}){const input={sourceContentId:id,sourceVersionId:v,settings:{...defaultVariationSettings,...settings}};const r=await c.post(`/api/workspaces/${w}/billing/quotes`,{data:{operation:'CLIPPER_VARIATION',...input}});expect(r.status(),'Variation quote status').toBe(200);const q=(await r.json()).quote;expect(q).toMatchObject({operation:'CLIPPER_VARIATION',tokenAmount:'100',internalBeta:true});return {...input,idempotencyKey:randomUUID(),quoteId:q.id,quoteHash:q.quoteHash};}
export async function variation(c:APIRequestContext,w:string,id:string,v:string,settings:Partial<VariationSettings>={}){const input=await quote(c,w,id,v,settings),r=await c.post(`/api/workspaces/${w}/clipper/variations`,{data:input});expect(r.status(),'Variation admission status').toBe(201);return {id:(await r.json()).job.id as string,input};}
export function provision(){return JSON.parse(execFileSync(process.execPath,['--env-file=.env.local','scripts/worker-admin.mjs','create',`phase-d-${randomUUID()}`,'CLIPPER_VARIATION_V1','1','--test'],{env:process.env,encoding:'utf8',windowsHide:true})) as {workerId:string;credential:string};}
export async function worker(credential:string){const c=await request.newContext({baseURL:base,extraHTTPHeaders:{Authorization:`Bearer ${credential}`}});expect((await c.post('/api/worker/heartbeat',{data:{agentVersion:'phase-d-acceptance',pipelineVersion:'clipper-variation-v1',availableSlots:1,activeLeaseIds:[],clipperHealth:{transcriberAvailable:false,ffmpegAvailable:true,gpuAvailable:false,freeDiskBytes:20*1024**3,variationRenderAvailable:true}}})).status()).toBe(200);return c;}
export function launch(credential:string,work:string,stage=''){
 let output='';const root=resolve('../worker-agent'),child=spawn('python',['worker_agent.py','--env',resolve(work,'isolated-no-provider.env')],{cwd:root,windowsHide:true,env:{...process.env,SAAS_BASE_URL:base,WORKER_TOKEN:credential,WORKER_WORK_DIR:work,WORKER_MAX_CONCURRENCY:'1',WORKER_POLL_SECONDS:'.2',WORKER_HEARTBEAT_SECONDS:'1',CLIP_ANALYZER_PROVIDER:'fake',ENABLE_FAKE_CLIP_ANALYZER:'1',WAVESPEED_API_KEY:'',OPENAI_API_KEY:'',PHASE_D_PROCESS_TEST:'1',PHASE_D_PAUSE_STAGE:stage,PYTHONPATH:resolve(root,'tests/phase_d_fixtures')},stdio:['ignore','pipe','pipe']});child.stdout!.on('data',b=>output+=b);child.stderr!.on('data',b=>output+=b);return {child,output:()=>output.replaceAll(credential,'[REDACTED]')};
}
export function killOwned(child?:ChildProcess){if(child?.pid&&child.exitCode===null)try{execFileSync('taskkill',['/PID',String(child.pid),'/T','/F'],{stdio:'pipe',windowsHide:true});}catch{}}
export async function marker(work:string,job:string,attempt:string){try{return JSON.parse(await readFile(resolve(work,job,attempt,'phase-d-paused.json'),'utf8'));}catch{return null;}}
export async function entries(db:Awaited<ReturnType<typeof database>>,id:string){return (await db.query('SELECT entry_type,count(*)::int AS count FROM token_ledger_entries WHERE job_id=$1 GROUP BY entry_type ORDER BY entry_type',[id])).rows;}
export async function render(f:Awaited<ReturnType<typeof fixture>>,id:string){const p=provision(),work=resolve('../worker-agent/data',`phase-d-${process.env.STABILIZATION_RUN_ID}`,id);await mkdir(work,{recursive:true});dispatch();const a=launch(p.credential,work);try{await expect.poll(async()=>{const j=(await f.db.query('SELECT status,error_code FROM jobs WHERE id=$1',[id])).rows[0];return ['FAILED','CANCELLED'].includes(j.status)?j.error_code||j.status:j.status;},{timeout:90000,message:'Real render-only worker completes'}).toBe('SUCCEEDED');const attempts=(await f.db.query('SELECT id FROM job_attempts WHERE job_id=$1 AND status=\'SUCCEEDED\'',[id])).rows;await expect.poll(async()=>{try{await access(resolve(work,id,attempts[0].id,'receipt.json'));return true;}catch{return false;}}).toBe(true);const receipt=JSON.parse(await readFile(resolve(work,id,attempts[0].id,'receipt.json'),'utf8'));expect(receipt.metrics.transcription).toBe(0);expect(receipt.metrics.analyzer).toBe(0);publishJob(f.workspaceId,id,3);dispatch();return {metrics:receipt.metrics,work,content:(await f.db.query('SELECT result_content_id id,result_version_id version FROM clipper_variations WHERE render_job_id=$1',[id])).rows[0]};}finally{killOwned(a.child);await writeFile(`${process.env.STABILIZATION_LOG_DIR}/${id}.log`,a.output());await f.db.query("UPDATE workers SET status='DISABLED' WHERE id=$1",[p.workerId]);}}
export async function originalUnchanged(f:Awaited<ReturnType<typeof fixture>>){expect(JSON.stringify((await f.db.query('SELECT * FROM content_versions WHERE id=$1',[f.versionId])).rows[0])).toBe(f.originalVersion);const m=await f.c.get(`/api/workspaces/${f.workspaceId}/content/${f.contentId}/versions/${f.versionId}/media?kind=download`);expect(m.status()).toBe(200);const r=await fetch((await m.json()).url),bytes=Buffer.from(await r.arrayBuffer());expect(createHash('sha256').update(bytes).digest('hex')).toBe(JSON.parse(f.originalVersion).sha256);}
export async function close(f:Awaited<ReturnType<typeof fixture>>){await f.c.dispose();await f.db.end();}
