"use client";
import { FormEvent,useState } from "react";
import { ThemeControl } from "@/components/theme-control";
import { Icon } from "@/components/icon";
export default function LoginPage(){
  const [password,setPassword]=useState("");const [error,setError]=useState("");const [busy,setBusy]=useState(false);
  async function submit(event:FormEvent){event.preventDefault();setBusy(true);setError("");try{const r=await fetch("/api/auth/login",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({password}),cache:"no-store"});const result=await r.json();if(!r.ok)throw new Error(result.error||"Sign in failed");setPassword("");window.location.replace("/");}catch(cause){setError(cause instanceof Error?cause.message:"Sign in failed");}finally{setBusy(false);}}
  return <main className="login-page"><div className="login-theme"><ThemeControl /></div><section className="login-visual"><div className="brand"><span className="brand-mark"><Icon name="sparkles" size={25} /></span><span className="brand-name">AI Site</span></div></section><div className="login-form-area"><section className="login-card"><div className="eyebrow">AI Site</div><h1>Welcome back</h1><p>Sign in to continue.</p><form onSubmit={e=>void submit(e)}><label className="field-label" htmlFor="account">Account</label><input className="input" id="account" value="Operator" readOnly autoComplete="username" /><label className="field-label" htmlFor="password">Password</label><input className="input" id="password" type="password" autoComplete="current-password" value={password} onChange={e=>setPassword(e.target.value)} required autoFocus placeholder="Enter your password" /><button className="button" type="submit" disabled={busy||!password}>{busy?"Signing in…":"Sign in"}<Icon name="arrow" size={17} /></button>{error&&<p className="login-error" role="alert">{error}</p>}</form><div className="login-footer"><Icon name="shield" size={15} />Secure operator access</div></section></div></main>;
}
