import Link from "next/link";
import { getBridgeStatus } from "@/lib/integrations/h3-bridge";
import { listVideoJobs } from "@/lib/integrations/h3-bridge/jobs";
import { getClipperOverview } from "@/lib/integrations/clipper";
import { getOutreachOverview } from "@/lib/integrations/outreach";
import { Icon } from "@/components/icon";
import { SystemStatus } from "@/components/system-status";
import { EmptyState,StatusBadge } from "@/components/ui";
export const dynamic="force-dynamic";
export default async function Home(){
  const [h3,jobResult,clipper,outreach]=await Promise.all([getBridgeStatus(),listVideoJobs().catch(()=>null),getClipperOverview(),getOutreachOverview()]);
  const jobs=jobResult??[];
  const completed=jobs.filter(j=>j.state==="COMPLETED").length;
  const activeCampaigns=outreach.state==="connected"?outreach.campaigns.filter(c=>["QUEUED","RUNNING","PAUSED","PAUSE_REQUESTED","SAFETY_PAUSED"].includes(c.state)).length:null;
  const activity=[...jobs.slice(0,4).map(j=>({label:j.state==="COMPLETED"?"AI video completed":j.state==="FAILED"?"AI generation failed":"AI video update",detail:j.prompt,date:j.updatedAt,href:"/ai-videos",icon:"video" as const})),...outreach.campaigns.slice(0,4).map(c=>({label:`Campaign ${c.state.toLowerCase().replaceAll("_"," ")}`,detail:c.name,date:c.createdAt,href:`/outreach/${c.id}`,icon:"send" as const})),...clipper.jobs.filter(j=>j.completedAt).slice(0,3).map(j=>({label:"Clipper job completed",detail:j.name||"Clipper job",date:j.completedAt!,href:"/clipper",icon:"scissors" as const}))].filter(i=>Number.isFinite(Date.parse(i.date))).sort((a,b)=>Date.parse(b.date)-Date.parse(a.date)).slice(0,6);
  return <>
  <div className="card-grid dashboard-tools">
  <article className="card tool-card"><div className="tool-header"><span className="tool-icon"><Icon name="video" size={26} /></span><div><h2>AI Videos</h2><p>From an idea to a portrait video.</p></div></div><div className="tool-summary"><div><strong>{jobResult===null?"—":completed}</strong><small>completed in recent history</small></div><StatusBadge tone={h3.readyToGenerate?"success":h3.comfy==="busy"||h3.creative==="busy"?"warning":"danger"}>{h3.readyToGenerate?"Available":h3.comfy==="busy"||h3.creative==="busy"?"Busy":h3.state==="connected"?"Unavailable":"Offline"}</StatusBadge></div><Link className="button" href="/ai-videos">Generate Video<Icon name="arrow" size={17} /></Link></article>
  <article className="card tool-card purple"><div className="tool-header"><span className="tool-icon"><Icon name="scissors" size={26} /></span><div><h2>Clipper</h2><p>Follow your content production.</p></div></div><div className="tool-summary"><div><strong>{clipper.state==="connected"?clipper.jobs.length:"—"}</strong><small>recent clipping jobs</small></div><StatusBadge tone={clipper.state==="connected"?"success":"danger"}>{clipper.state==="connected"?"Connected":"Offline"}</StatusBadge></div><a className="button-outline" href="http://127.0.0.1:5173" target="_blank" rel="noopener noreferrer">Open Clipper<Icon name="external" size={16} /></a></article>
  <article className="card tool-card blue"><div className="tool-header"><span className="tool-icon"><Icon name="send" size={26} /></span><div><h2>Outreach</h2><p>Keep your campaigns moving.</p></div></div><div className="tool-summary"><div><strong>{activeCampaigns??"—"}</strong><small>active in recent campaigns</small></div><StatusBadge tone={outreach.state==="connected"?"success":"danger"}>{outreach.state==="connected"?"Connected":"Offline"}</StatusBadge></div><Link className="button-outline" href="/outreach">View Campaigns<Icon name="arrow" size={17} /></Link></article></div>
  <div className="home-bottom"><section className="card panel"><div className="section-top"><h2><Icon name="clock" />Recent Activity</h2><span className="field-note">From connected tools</span></div>{activity.length?<div className="record-list">{activity.map((i,n)=><Link className="record-row activity-row" href={i.href} key={n}><div style={{display:"flex",gap:12,alignItems:"center"}}><span className="avatar"><Icon name={i.icon} size={18} /></span><div><strong>{i.label}</strong><small>{i.detail.slice(0,85)}{i.detail.length>85?"…":""}</small></div></div><span>{new Date(i.date).toLocaleString()}</span></Link>)}</div>:<EmptyState title="No recent activity" detail="Updates from your connected tools will appear here." icon="clock" />}</section><div className="home-right"><section className="card panel"><div className="section-top"><h2><Icon name="activity" />System Status</h2><Link className="text-link" href="/settings">Details<Icon name="arrow" size={15} /></Link></div><SystemStatus compact /></section><section className="card panel"><div className="section-top"><h2><Icon name="sparkles" />Quick Actions</h2></div><div className="quick-actions"><Link href="/ai-videos"><Icon name="video" size={24} />Generate Video</Link><Link href="/clipper"><Icon name="scissors" size={24} />Monitor Clipper</Link><Link href="/outreach"><Icon name="send" size={24} />View Campaigns</Link></div></section></div></div></>;
}
