"use client";
import Link from "next/link";
import {useEffect,useState} from "react";
import {api} from "./api";
import {PublishedContent} from "./published-content";
import type {Clip} from "@/lib/clipper-core";
type Job={kind?:string;variationNumber?:number|null;startedAt?:string|null;completedAt?:string|null;publicationPending?:boolean;billing?:{token_amount:string;status:string}|null;id:string;status:string;progressPercent:number;stage:string;message:string;cancelRequested:boolean;source:string;requested:number;goal:string;productName:unknown;errorMessage?:string|null;result:Record<string,unknown>|null};
function ArtifactLink({workspaceId,jobId,id,label,video=false}:{workspaceId:string;jobId:string;id:string;label:string;video?:boolean}){
  const [url,setUrl]=useState(""),[downloadUrl,setDownloadUrl]=useState("");useEffect(()=>{let alive=true;const refresh=()=>{void api<{url:string}>(`/api/workspaces/${workspaceId}/clipper/${jobId}/artifacts/${id}/download`).then(r=>{if(alive)setUrl(r.url);}).catch(()=>{});void api<{url:string}>(`/api/workspaces/${workspaceId}/clipper/${jobId}/artifacts/${id}/download?download=1`).then(r=>{if(alive)setDownloadUrl(r.url);}).catch(()=>{});};refresh();const timer=setInterval(refresh,240000);return()=>{alive=false;clearInterval(timer);};},[workspaceId,jobId,id]);return <>{url&&video&&<video className="video-preview" controls playsInline preload="metadata" src={url}/>}<p>{url?<a className="button secondary" href={downloadUrl||url} download>{label}</a>:"Preparing private file…"}</p></>;
}
export function ClipperJobView({workspaceId,initial,canCancel}:{workspaceId:string;initial:Job;canCancel:boolean}){
  const [job,setJob]=useState(initial),[error,setError]=useState("");useEffect(()=>{if(["SUCCEEDED","FAILED","CANCELLED"].includes(job.status)&&job.billing?.status!=="RESERVED"&&!job.publicationPending)return;const timer=setInterval(()=>void api<{job:Job}>(`/api/workspaces/${workspaceId}/clipper/${job.id}`).then(r=>setJob(r.job)).catch(()=>{}),2000);return()=>clearInterval(timer);},[workspaceId,job.id,job.status,job.billing?.status,job.publicationPending]);
  async function cancel(){try{await api(`/api/workspaces/${workspaceId}/jobs/${job.id}/cancel`,"POST");setJob({...job,cancelRequested:true});}catch(cause){setError(cause instanceof Error?cause.message:"Cancellation failed.");}}
  const clips=(job.result?.clips||[]) as (Clip&{contentId?:string|null})[];
  const statusNote=job.status==="SUCCEEDED"?"Your private clips are ready.":job.status==="CANCELLED"?"Processing was cancelled.":job.status==="FAILED"?"Processing stopped.":job.cancelRequested?"Cancellation requested":"Processing continues after you close this page.";
  const visibleError=error||(job.status!=="SUCCEEDED"&&job.errorMessage);
  return <>{job.billing&&<p className="notice">Token cost: {job.billing.token_amount} · {job.billing.status}</p>}{job.status==="SUCCEEDED"&&<PublishedContent workspaceId={workspaceId} jobId={job.id}/>}<section className="panel"><p className="eyebrow">CLIPPER STATUS</p><h2>{job.variationNumber?`Variation ${job.variationNumber} · `:""}{job.status.replaceAll("_"," ")}</h2><p>{job.message||job.stage.replaceAll("_"," ")}</p><progress className="job-progress" value={job.progressPercent} max={100}/><p>{job.progressPercent}% · Requested {job.requested}{job.status==="SUCCEEDED"?` · Found ${clips.length} valid moments`:""}</p><p className="muted">{statusNote}</p><p className="job-times">{job.startedAt?`Started: ${new Date(job.startedAt).toLocaleString("en-US",{timeZone:"Asia/Shanghai"})}`:"Waiting to start"}{job.completedAt&&` · Completed: ${new Date(job.completedAt).toLocaleString("en-US",{timeZone:"Asia/Shanghai"})}`}</p><dl className="job-facts"><div><dt>Source</dt><dd>{job.source}</dd></div><div><dt>Product</dt><dd>{String(job.productName||"Generic clipping")}</dd></div><div><dt>Goal</dt><dd>{job.goal}</dd></div></dl>{visibleError&&<p role="alert" className="notice error">{visibleError}</p>}{canCancel&&!["SUCCEEDED","FAILED","CANCELLED"].includes(job.status)&&<button className="button secondary" disabled={job.cancelRequested} onClick={()=>void cancel()}>Request cancellation</button>}</section>{job.status==="SUCCEEDED"&&<>{job.kind!=="CLIPPER_VARIATION"&&<section className="panel"><h2>Transcript and clip plan</h2><ArtifactLink workspaceId={workspaceId} jobId={job.id} id={String(job.result!.transcriptArtifactId)} label="Download transcript"/><ArtifactLink workspaceId={workspaceId} jobId={job.id} id={String(job.result!.planArtifactId)} label="Download clip plan"/></section>}<div className="clipper-results">{clips.map((clip,i)=><section className="panel" key={clip.artifactId}><p className="eyebrow">CLIP {i+1}</p><h2>{clip.hook}</h2><p>{clip.reason}</p><p className="muted">{clip.start.toFixed(1)}–{clip.end.toFixed(1)}s · {clip.duration.toFixed(1)} seconds · Score {clip.score}</p><ArtifactLink workspaceId={workspaceId} jobId={job.id} id={clip.artifactId} label={`Download clip ${i+1}`} video/>{clip.contentId&&<div className="form-actions"><Link className="button secondary" href={`/content/${clip.contentId}`}>Open in Content Library</Link>{canCancel&&<Link className="button primary" href={`/clipper/edit/${clip.contentId}`}>Edit / Create variation</Link>}</div>}</section>)}</div></>}</>;
}
