"use client";
import {useEffect,useState} from 'react';
import {useRouter} from 'next/navigation';
import Link from 'next/link';
import {ContentMedia} from './content-media';
import {api} from './api';
import {useTokenQuote,TokenQuoteView} from './token-quote';
import {applyVariationStyle,variationFonts,variationGrades,variationStyles,type VariationSettings} from '@/lib/clipper-variation-settings';
export type EditorInput={sourceContentId:string;sourceVersionId:string;title:string;rootContentId:string;hook:string;duration:number;settings:VariationSettings;parentLabel:string};
export function ClipperVariationEditor({workspaceId,initial}:{workspaceId:string;initial:EditorInput}){
 const router=useRouter(),[settings,setSettings]=useState(initial.settings),[busy,setBusy]=useState(false),[error,setError]=useState(''),[key,setKey]=useState(()=>crypto.randomUUID()),[restored,setRestored]=useState(false),[previousJob,setPreviousJob]=useState('');
 const draftKey=`clipper-edit:${workspaceId}:${initial.sourceContentId}:${initial.sourceVersionId}`;
 useEffect(()=>{let active=true;queueMicrotask(()=>{if(!active)return;try{const saved=JSON.parse(sessionStorage.getItem(draftKey)||'null');if(saved&&typeof saved.key==='string'&&/^[A-Za-z0-9:_-]{8,160}$/.test(saved.key)&&saved.settings&&Object.keys(saved.settings).every(k=>Object.hasOwn(initial.settings,k))){setSettings({...initial.settings,...saved.settings});setKey(saved.key);if(typeof saved.jobId==='string'&&/^[a-f0-9-]{36}$/i.test(saved.jobId))setPreviousJob(saved.jobId);}}catch{}setRestored(true);});return()=>{active=false;};},[draftKey,initial.settings]);
 useEffect(()=>{if(restored)try{sessionStorage.setItem(draftKey,JSON.stringify({key,settings,jobId:previousJob}));}catch{}},[restored,draftKey,key,settings,previousJob]);
 const quoteState=useTokenQuote(workspaceId,'CLIPPER_VARIATION',{sourceContentId:initial.sourceContentId,sourceVersionId:initial.sourceVersionId,settings},restored&&!previousJob);
 const {quote}=quoteState;
 function renewIdentity(){setKey(crypto.randomUUID());setPreviousJob('');setError('');quoteState.refreshQuote();}
 function change<K extends keyof VariationSettings>(field:K,value:VariationSettings[K]){setSettings(s=>{const next={...s,[field]:value};if(!next.letterboxEnabled||next.topBar<.05||next.hookType==='none')next.topHookEnabled=false;return next;});renewIdentity();}
 async function submit(){if(!quote||!quote.affordable||busy||previousJob)return;setBusy(true);setError('');try{const r=await api<{job:{id:string}}>(`/api/workspaces/${workspaceId}/clipper/variations`,'POST',{sourceContentId:initial.sourceContentId,sourceVersionId:initial.sourceVersionId,settings,idempotencyKey:key,quoteId:quote.id,quoteHash:quote.quoteHash});try{sessionStorage.setItem(draftKey,JSON.stringify({key,settings,jobId:r.job.id}));}catch{}setPreviousJob(r.job.id);router.push(`/clipper/${r.job.id}`);}catch(e){setError(e instanceof Error?e.message:'Could not create a variation.');quoteState.refreshQuote();setBusy(false);}}
 const fontOptions=Object.entries(variationFonts).map(([value,label])=><option key={value} value={value}>{label}</option>);
 const toggle=(field:keyof VariationSettings,label:string,disabled=false)=><label className="variation-toggle"><input type="checkbox" checked={!!settings[field]} disabled={disabled||busy} onChange={e=>change(field,e.target.checked as never)}/>{label}</label>;
 const percentage=(field:'subtitleY'|'topBar'|'bottomBar'|'hookX'|'hookY',label:string,min:number,max:number,disabled=false)=><label>{label}<span className="variation-range"><input type="range" aria-label={label} min={min} max={max} value={Math.round(settings[field]*100)} disabled={disabled||busy} onChange={e=>change(field,Number(e.target.value)/100)}/><output>{Math.round(settings[field]*100)}%</output></span></label>;
 return <div className="variation-editor-layout"><aside className="panel variation-preview-panel"><p className="eyebrow">{initial.parentLabel}</p><h2>{initial.title}</h2><ContentMedia workspaceId={workspaceId} contentId={initial.sourceContentId} versionId={initial.sourceVersionId} alt="Saved clip preview"/><p className="muted">{initial.duration.toFixed(1)} seconds · Original timing and audio are reused.</p><h3>Style guide</h3><div className="variation-style-guide" aria-label="Lightweight style guide" style={{background:settings.colorGrade==='warm'?'#674d3b':settings.colorGrade==='cool'?'#344d65':'#4b5563'}}><div className="variation-guide-bars" style={{height:settings.letterboxEnabled?`${settings.topBar*100}%`:'0%'}}/>{settings.hookType==='text'&&<span className="variation-guide-hook" style={{color:settings.hookColor,left:settings.topHookEnabled?`${settings.hookX*100}%`:'50%',top:settings.topHookEnabled?`${settings.topBar*settings.hookY*100}%`:'12%',fontFamily:settings.hookFont==='serif'?'Georgia,serif':settings.hookFont==='display'?'Impact,sans-serif':'Arial,sans-serif'}}>{initial.hook}</span>}{settings.subtitleEnabled&&<span className="variation-guide-subtitle" style={{top:`${settings.subtitleY*100}%`,color:settings.fontColor,fontSize:{compact:14,small:17,medium:20,large:23}[settings.subtitleSize],fontFamily:settings.subtitleFont==='serif'?'Georgia,serif':settings.subtitleFont==='display'?'Impact,sans-serif':'Arial,sans-serif'}}>Sample <b style={{color:settings.highlightEnabled?settings.highlightColor:settings.fontColor}}>caption</b></span>}<div className="variation-guide-bars bottom" style={{height:settings.letterboxEnabled?`${settings.bottomBar*100}%`:'0%'}}/></div><p className="muted">The style guide shows placement and color. Render the variation to preview the finished video.</p><Link href={`/content/${initial.sourceContentId}`}>Back to saved clip</Link></aside>
 <section className="variation-controls"><fieldset disabled={busy}><legend>Create a variation</legend><p>Your saved clip stays available. This edit creates a new private video with its own history.</p><section className="panel"><h2>Creative setup</h2><label>Variation name<input aria-label="Variation name" maxLength={80} value={settings.name} placeholder="Optional name" onChange={e=>change('name',e.target.value)}/></label><div className="variation-field-grid"><label>Text style<select aria-label="Text style" value={settings.textStyle} onChange={e=>{setSettings(s=>applyVariationStyle(s,e.target.value as VariationSettings['textStyle']));renewIdentity();}}>{Object.entries(variationStyles).map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label><label>Hook<select aria-label="Hook" value={settings.hookType} onChange={e=>{change('hookType',e.target.value as 'none'|'text');if(e.target.value==='none')change('topHookEnabled',false);}}><option value="text">Existing text hook</option><option value="none">No hook</option></select></label><label>Color grade<select aria-label="Color grade" value={settings.colorGrade} onChange={e=>change('colorGrade',e.target.value as VariationSettings['colorGrade'])}>{variationGrades.map(v=><option key={v} value={v}>{v[0].toUpperCase()+v.slice(1)}</option>)}</select></label>{toggle('mirror','Flip video')}</div></section>
 <section className="panel"><h2>Subtitles</h2>{toggle('subtitleEnabled','Show subtitles')}<div className="variation-field-grid"><label>Subtitle placement<select aria-label="Subtitle placement" value={settings.subtitlePosition} disabled={!settings.subtitleEnabled} onChange={e=>{const p=e.target.value as VariationSettings['subtitlePosition'];setSettings(s=>({...s,subtitlePosition:p,subtitleY:{top:.34,center:.58,bottom:.84}[p]}));renewIdentity();}}>{['top','center','bottom'].map(v=><option value={v} key={v}>{v[0].toUpperCase()+v.slice(1)}</option>)}</select></label><label>Subtitle size<select aria-label="Subtitle size" value={settings.subtitleSize} disabled={!settings.subtitleEnabled} onChange={e=>change('subtitleSize',e.target.value as VariationSettings['subtitleSize'])}>{['compact','small','medium','large'].map(v=><option key={v} value={v}>{v[0].toUpperCase()+v.slice(1)}</option>)}</select></label><label>Subtitle font<select aria-label="Subtitle font" value={settings.subtitleFont} disabled={!settings.subtitleEnabled} onChange={e=>change('subtitleFont',e.target.value as VariationSettings['subtitleFont'])}>{fontOptions}</select></label>{percentage('subtitleY','Exact subtitle position',8,92,!settings.subtitleEnabled)}<label>Text color<input type="color" aria-label="Text color" value={settings.fontColor} disabled={!settings.subtitleEnabled} onChange={e=>change('fontColor',e.target.value)}/></label><label>Highlight color<input type="color" aria-label="Highlight color" value={settings.highlightColor} disabled={!settings.subtitleEnabled} onChange={e=>change('highlightColor',e.target.value)}/></label></div>{toggle('highlightEnabled','Active-word highlighting',!settings.subtitleEnabled||settings.phraseCaptions)}{toggle('phraseCaptions','Phrase captions',!settings.subtitleEnabled)}<p className="muted">Captions reuse the saved transcript. Word highlighting uses existing word timing when available.</p></section>
 <section className="panel"><h2>Letterbox and hook</h2>{toggle('letterboxEnabled','Black bars')}<div className="variation-field-grid">{percentage('topBar','Top bar height',0,40,!settings.letterboxEnabled)}{percentage('bottomBar','Bottom bar height',0,40,!settings.letterboxEnabled)}</div>{toggle('topHookEnabled','Automatic top-bar hook',!settings.letterboxEnabled||settings.topBar<.05||settings.hookType!=='text')}<div className="variation-field-grid"><label>Hook font<select aria-label="Hook font" value={settings.hookFont} disabled={!settings.topHookEnabled} onChange={e=>change('hookFont',e.target.value as VariationSettings['hookFont'])}>{fontOptions}</select></label><label>Hook color<input aria-label="Hook color" type="color" value={settings.hookColor} disabled={!settings.topHookEnabled} onChange={e=>change('hookColor',e.target.value)}/></label><label>Hook size<input aria-label="Hook size" type="number" min={24} max={160} value={settings.hookSize} disabled={!settings.topHookEnabled} onChange={e=>change('hookSize',Number(e.target.value))}/></label>{percentage('hookX','Hook horizontal position',0,100,!settings.topHookEnabled)}{percentage('hookY','Hook vertical position',0,100,!settings.topHookEnabled)}</div></section></fieldset>
 <section className="panel variation-submit">{previousJob?<p className="notice">This draft already has a render. <Link href={`/clipper/${previousJob}`}>Open status</Link><button type="button" className="text-button" onClick={renewIdentity}>Start another variation from this draft</button></p>:<TokenQuoteView {...quoteState}/>}{error&&<p className="notice error" role="alert">{error}</p>}<button className="button primary" disabled={busy||!quote?.affordable} onClick={()=>void submit()}>{busy?'Creating variation…':'Render new variation'}</button><p className="muted">The shared account balance pays for this render. No new transcription or AI analysis is requested.</p></section></section></div>;
}
