"use client";
import {useState} from "react";
import {useRouter} from "next/navigation";
import {api} from "./api";
import {GENERIC_REJECTION_CATEGORIES,PRODUCT_REJECTION_CATEGORIES} from "@/lib/content-rules";
export function ContentActions({workspaceId,id,versionId,revision,productBacked,archived,posterFailed,parents}:{workspaceId:string;id:string;versionId:string;revision:number;productBacked:boolean;archived:boolean;posterFailed:boolean;parents:{id:string;title:string}[]}){
  const router=useRouter(),[category,setCategory]=useState("QUALITY_ISSUE"),[reason,setReason]=useState(""),[parent,setParent]=useState(""),[error,setError]=useState(""),[busy,setBusy]=useState(false),[requestKey,setRequestKey]=useState("");
  const categories=productBacked?PRODUCT_REJECTION_CATEGORIES:GENERIC_REJECTION_CATEGORIES;
  async function action(path:string,data:Record<string,unknown>={}){setBusy(true);setError("");try{await api(`/api/workspaces/${workspaceId}/content/${id}/${path}`,"POST",data);setRequestKey("");router.refresh();}catch(cause){setError(cause instanceof Error?cause.message:"Action failed.");}finally{setBusy(false);}}
  async function review(decision:string){const prefix=`${versionId}:${revision}:${decision}:`,key=requestKey.startsWith(prefix)?requestKey:`${prefix}${crypto.randomUUID()}`;setRequestKey(key);await action("review",{versionId,decision,expectedRevision:revision,requestKey:key,...(decision==="REJECT"?{reasonCategory:category,reasonText:reason}:{})});}
  return <section className="panel"><h2>Review this version</h2>{archived?<p>Archived content preserves its review history.</p>:<><p>Approval applies to version {versionId.slice(0,8)}. A later decision may change its status.</p><button className="button primary" disabled={busy} onClick={()=>void review("APPROVE")}>Approve content</button><div className="review-reject"><label>Rejection category<select aria-label="Rejection category" value={category} disabled={busy} onChange={e=>{setCategory(e.target.value);setRequestKey("");}}>{categories.map(c=><option key={c} value={c}>{c.replaceAll("_"," ")}</option>)}</select></label><label>Rejection reason<textarea aria-label="Rejection reason" value={reason} maxLength={1000} disabled={busy} onChange={e=>{setReason(e.target.value);setRequestKey("");}}/></label><button className="button secondary" disabled={busy} onClick={()=>void review("REJECT")}>Reject content</button></div><hr/><label>Parent content<select aria-label="Parent content" value={parent} disabled={busy} onChange={e=>setParent(e.target.value)}><option value="">Choose an existing item</option>{parents.filter(p=>p.id!==id).map(p=><option key={p.id} value={p.id}>{p.title}</option>)}</select></label><p className="muted">Register this item as a variant of the selected parent.</p><button className="button secondary" disabled={busy||!parent} onClick={()=>void action("relations",{relationType:"VARIANT_OF",parentContentId:parent})}>Register variant</button><p><button className="text-button" disabled={busy} onClick={()=>void action("archive")}>Archive content</button></p></>}{posterFailed&&<button className="button secondary" disabled={busy} onClick={()=>void action(`versions/${versionId}/poster/retry`)}>Retry poster</button>}{error&&<p className="notice error" role="alert">{error}</p>}</section>;
}
