'use client';
import {useState} from 'react';
import {api} from './api';
export function OperationsConsole({initial}:{initial:unknown}){
  const [result,setResult]=useState(initial),[path,setPath]=useState('/api/operations'),[error,setError]=useState(''),[action,setAction]=useState('WAKE_WORKFLOW'),[target,setTarget]=useState(''),[workspace,setWorkspace]=useState(''),[reason,setReason]=useState(''),[limit,setLimit]=useState('active_jobs'),[value,setValue]=useState('20');
  async function load(){try{if(!path.startsWith('/api/operations'))throw new Error('Use an operations endpoint.');setResult(await api(path));setError('');}catch(e){setError(e instanceof Error?e.message:'Unavailable');}}
  async function apply(){try{setResult(await api('/api/operations','POST',{action,targetId:target,workspaceId:workspace,reason,limitName:limit,value}));setError('');}catch(e){setError(e instanceof Error?e.message:'Unavailable');}}
  return <><section className="panel"><h2>Read-only investigation</h2><p>Use an exact email or identifier with <code>?q=</code>, <code>?view=audit</code>, or <code>/job/id</code>, <code>/workflow/id</code>, <code>/payment/id</code>, <code>/workspace/id</code>, <code>/content/id</code>.</p><label>Operations endpoint<input value={path} onChange={e=>setPath(e.target.value)}/></label><button onClick={()=>void load()}>Inspect</button></section><section className="panel"><h2>Audited recovery</h2><label>Action<select value={action} onChange={e=>setAction(e.target.value)}>{['WAKE_WORKFLOW','SETTLE_JOB','RECONCILE_PAYMENT','RETRY_PUBLICATION','RETRY_POSTER','RETRY_MAIL','SET_QUOTA'].map(a=><option key={a}>{a}</option>)}</select></label><label>Target identifier<input value={target} onChange={e=>setTarget(e.target.value)}/></label><label>Workspace identifier<input value={workspace} onChange={e=>setWorkspace(e.target.value)}/></label>{action==='SET_QUOTA'&&<><label>Limit<select value={limit} onChange={e=>setLimit(e.target.value)}>{['active_jobs','active_workflows','queued_ai_videos','queued_clipper_jobs','source_uploads_daily','storage_bytes','product_assets'].map(n=><option key={n}>{n}</option>)}</select></label><label>Value<input value={value} onChange={e=>setValue(e.target.value)}/></label></>}<label>Reason<input value={reason} maxLength={240} onChange={e=>setReason(e.target.value)}/></label><button onClick={()=>void apply()}>Apply audited action</button></section>{error&&<p role="alert">{error}</p>}<section className="panel"><h2>Result</h2><pre style={{whiteSpace:'pre-wrap',overflowWrap:'anywhere'}}>{JSON.stringify(result,null,2)}</pre></section></>;
}
