"use client";
import { useState, type FormEvent } from "react";
import { api } from "./api";

type Member={id:string;user_id:string;email:string;display_name:string;role:"OWNER"|"ADMIN"|"EDITOR"|"VIEWER";status:string};
type Invitation={id:string;email:string;intended_role:string;status:string;expires_at:string};
type Event={id:string;event_type:string;target_type:string;occurred_at:string;actor_email:string|null};
const dateOnly=new Intl.DateTimeFormat("en-US",{dateStyle:"medium",timeZone:"UTC"});
const dateTime=new Intl.DateTimeFormat("en-US",{dateStyle:"medium",timeStyle:"short",timeZone:"UTC"});
export function SettingsClient({workspace,userId,userEmail,userName,initialMembers,initialInvitations,events}:{workspace:{id:string;name:string;role:string};userId:string;userEmail:string;userName:string;initialMembers:Member[];initialInvitations:Invitation[];events:Event[]}) {
  const [name,setName]=useState(workspace.name);const [inviteEmail,setInviteEmail]=useState("");const [inviteRole,setInviteRole]=useState("EDITOR");const [members,setMembers]=useState(initialMembers);const [invitations,setInvitations]=useState(initialInvitations);const [error,setError]=useState("");const [message,setMessage]=useState("");const [busy,setBusy]=useState(false);
  const canManage=workspace.role==="OWNER"||workspace.role==="ADMIN";
  const ownerCount=members.filter(m=>m.role==="OWNER").length;
  async function refresh(){const m=await api<{members:Member[]}>(`/api/workspaces/${workspace.id}/members`);setMembers(m.members);if(canManage){const i=await api<{invitations:Invitation[]}>(`/api/workspaces/${workspace.id}/invitations`);setInvitations(i.invitations);}}
  async function run(action:()=>Promise<unknown>,success:string){setBusy(true);setError("");setMessage("");try{await action();await refresh();setMessage(success);}catch(cause){setError(cause instanceof Error?cause.message:"Request failed.");}finally{setBusy(false);}}
  async function rename(e:FormEvent){e.preventDefault();await run(()=>api(`/api/workspaces/${workspace.id}`,"PATCH",{name}),"Workspace updated.");}
  async function invite(e:FormEvent){e.preventDefault();await run(()=>api(`/api/workspaces/${workspace.id}/invitations`,"POST",{email:inviteEmail,role:inviteRole}),"Invitation created. Find the link in the local development mailbox.");setInviteEmail("");}
  return <><div className="page-heading"><div><p className="eyebrow">ADMINISTRATION</p><h1>Settings</h1><p>Manage this workspace, its team, and your account.</p></div></div>{error&&<p className="notice error" role="alert">{error}</p>}{message&&<p className="notice success" role="status">{message}</p>}
  <div className="settings-grid"><section className="panel"><div className="panel-head"><div><span className="eyebrow">WORKSPACE</span><h2>Workspace details</h2></div><span className="pill">{workspace.role}</span></div><form onSubmit={rename}><label>Name<input value={name} onChange={e=>setName(e.target.value)} disabled={!canManage||busy} minLength={2} maxLength={100} /></label>{canManage&&<button className="button secondary" disabled={busy}>Save changes</button>}</form><p className="helper">Workspace ID · {workspace.id}</p></section><section className="panel"><div className="panel-head"><div><span className="eyebrow">ACCOUNT</span><h2>Your access</h2></div></div><p><strong>{userName}</strong><br />{userEmail}</p><p>Your role in this workspace is <strong>{workspace.role.toLowerCase()}</strong>.</p><p className="helper">Account ID · {userId}</p></section></div>
  <section className="panel team-panel"><div className="panel-head"><div><span className="eyebrow">PEOPLE</span><h2>Team & roles</h2><p>Members share this workspace according to their role.</p></div><span className="count">{members.length} {members.length===1?"member":"members"}</span></div><div className="table-wrap"><table><thead><tr><th>Member</th><th>Email</th><th>Role</th><th>Status</th><th>Action</th></tr></thead><tbody>{members.map(member=><tr key={member.id}><td><strong>{member.display_name}</strong></td><td>{member.email}</td><td>{member.role}</td><td><span className="status-label">{member.status}</span></td><td>{canManage && !(workspace.role==="ADMIN"&&(member.role==="OWNER"||member.user_id===userId)) && !(member.role==="OWNER"&&ownerCount===1)?<div className="row-actions"><select aria-label={`Role for ${member.email}`} value={member.role} disabled={busy} onChange={e=>void run(()=>api(`/api/workspaces/${workspace.id}/members/${member.id}`,"PATCH",{role:e.target.value}),"Role updated.")}>{["OWNER","ADMIN","EDITOR","VIEWER"].filter(r=>workspace.role==="OWNER"||r!=="OWNER").map(r=><option key={r}>{r}</option>)}</select><button className="text-button danger" disabled={busy} onClick={()=>void run(()=>api(`/api/workspaces/${workspace.id}/members/${member.id}`,"DELETE"),"Member removed.")}>Remove</button></div>:<span className="muted">—</span>}</td></tr>)}</tbody></table></div></section>
  {canManage&&<div className="settings-grid"><section className="panel"><div className="panel-head"><div><span className="eyebrow">INVITE</span><h2>Add a teammate</h2></div></div><form onSubmit={invite}><label>Email address<input type="email" value={inviteEmail} onChange={e=>setInviteEmail(e.target.value)} required placeholder="teammate@company.com" /></label><label>Role<select value={inviteRole} onChange={e=>setInviteRole(e.target.value)}>{["OWNER","ADMIN","EDITOR","VIEWER"].filter(r=>workspace.role==="OWNER"||r!=="OWNER").map(r=><option key={r}>{r}</option>)}</select></label><button className="button primary" disabled={busy}>Send invitation <span>→</span></button></form></section><section className="panel"><div className="panel-head"><div><span className="eyebrow">PENDING</span><h2>Invitations</h2></div></div>{invitations.filter(i=>i.status==="PENDING").length?invitations.filter(i=>i.status==="PENDING").map(inv=><div className="list-row" key={inv.id}><div><strong>{inv.email}</strong><small>{inv.intended_role} · expires {dateOnly.format(new Date(inv.expires_at))} UTC</small></div><button className="text-button danger" disabled={busy} onClick={()=>void run(()=>api(`/api/workspaces/${workspace.id}/invitations/${inv.id}`,"DELETE"),"Invitation cancelled.")}>Cancel</button></div>):<p className="muted">No pending invitations.</p>}</section></div>}
  {canManage&&<section className="panel"><div className="panel-head"><div><span className="eyebrow">ACCESS LOG</span><h2>Recent workspace activity</h2></div></div>{events.length?events.map(event=><div className="list-row" key={event.id}><div><strong>{event.event_type.replaceAll("_"," ").toLowerCase()}</strong><small>{event.actor_email||"system"} · {event.target_type}</small></div><time>{dateTime.format(new Date(event.occurred_at))} UTC</time></div>):<p className="muted">No workspace activity yet.</p>}</section>}</>;
}
