"use client";
import {useEffect,useState} from "react";
import Link from "next/link";
import {api} from "./api";
export type TokenQuote={id:string;quoteHash:string;tokenAmount:string;availableTokens:string;reservedTokens:string;affordable:boolean;expiresAt:string;test:boolean;internalBeta?:boolean;priceLabel:string};
export function useTokenQuote(workspaceId:string,operation:"AI_VIDEO"|"CLIPPER"|"CLIPPER_VARIATION"|"OUTREACH",input:Record<string,unknown>,enabled:boolean){const serialized=JSON.stringify(input),identity=`${workspaceId}:${operation}:${serialized}`;const [stored,setStored]=useState<{quote:TokenQuote;request:string}|null>(null),[error,setError]=useState(""),[refresh,setRefresh]=useState(0);
 useEffect(()=>{if(!enabled)return;let active=true;const timer=setTimeout(()=>{void api<{quote:TokenQuote}>(`/api/workspaces/${workspaceId}/billing/quotes`,"POST",{...JSON.parse(serialized),operation}).then(r=>{if(active){setStored({quote:r.quote,request:identity});setError("");}}).catch(e=>{if(active){setStored(null);setError(e.message);}});},350);return()=>{active=false;clearTimeout(timer);};},[workspaceId,operation,serialized,identity,enabled,refresh]);
 const quote=enabled&&stored?.request===identity?stored.quote:null;
 useEffect(()=>{if(!quote)return;const timer=setTimeout(()=>{setStored(null);setRefresh(x=>x+1);},Math.max(1,Date.parse(quote.expiresAt)-Date.now()));return()=>clearTimeout(timer);},[quote]);
 return {quote,error:enabled?error:"",loading:enabled&&!quote&&!error,refreshQuote:()=>{setStored(null);setError('');setRefresh(x=>x+1);}};
}
export function TokenQuoteView({quote,error,loading,refreshQuote,settlementText}:{quote:TokenQuote|null;error:string;loading:boolean;refreshQuote:()=>void;settlementText?:string}){return <div className={`review-card token-quote ${quote&&!quote.affordable?'insufficient-tokens':''}`} aria-live="polite"><strong>{quote?`Required: ${BigInt(quote.tokenAmount).toLocaleString("en-US")} Tokens`:loading?"Calculating token quote…":"Configure your request for a token quote"}</strong>{quote&&<><strong>Available: {BigInt(quote.availableTokens).toLocaleString("en-US")} Tokens</strong><p>Reserved: {BigInt(quote.reservedTokens).toLocaleString("en-US")} Tokens</p><p>{settlementText||'Tokens are reserved when you submit, captured on success, and released after a definite failure or cancellation.'}</p>{quote.internalBeta&&<p>Internal beta price · {quote.priceLabel}. Final pricing has not been approved.</p>}{quote.test&&<p>TEST token price · {quote.priceLabel}</p>}{!quote.affordable&&<p className="notice error" role="alert"><b>Insufficient Tokens.</b> Add Tokens to continue. <Link href="/billing">Buy Tokens →</Link></p>}<button type="button" className="text-button" onClick={refreshQuote}>Refresh balance</button></>}{error&&<p role="alert">{error}</p>}</div>;}
