"use client";
import { useEffect, useState } from "react";
import Link from "next/link";
import { api } from "./api";
import {PublishedContent} from "./published-content";

type Job={billing?:{token_amount:string;status:string}|null;id:string;status:string;progressPercent:number;progressStage:string;progressMessage:string;errorMessage:string|null;createdAt:string;startedAt:string|null;finishedAt:string|null;cancelRequested:boolean;prompt:string;productId:string;productName:string;productVersionId:string;productVersion:number;ruleVersion:number;tier:string;durationSeconds:number;aspectRatio:string;referenceAssetVersionIds:string[];artifacts:{id:string;mimeType:string;byteSize:number;sha256:string}[]};
export function VideoJobView({workspaceId,initial}:{workspaceId:string;initial:Job}){
  const [job,setJob]=useState(initial),[videoUrl,setVideoUrl]=useState(""),[error,setError]=useState("");
  const artifactId=job.artifacts[0]?.id;
  useEffect(()=>{if(["SUCCEEDED","FAILED","CANCELLED"].includes(job.status)&&job.billing?.status!=="RESERVED")return;const timer=setInterval(()=>{void api<{job:Job}>(`/api/workspaces/${workspaceId}/ai-videos/${job.id}`).then(x=>setJob(x.job)).catch(()=>{});},3000);return()=>clearInterval(timer);},[workspaceId,job.id,job.status,job.billing?.status]);
  useEffect(()=>{if(!artifactId)return;let active=true;const refresh=()=>{void api<{url:string}>(`/api/workspaces/${workspaceId}/ai-videos/${job.id}/artifacts/${artifactId}/download`).then(x=>{if(active){setVideoUrl(x.url);setError("");}}).catch(cause=>{if(active)setError(cause instanceof Error?cause.message:"Video unavailable.");});};refresh();const timer=setInterval(refresh,240000);return()=>{active=false;clearInterval(timer);};},[workspaceId,job.id,artifactId]);
  async function cancel(){try{await api(`/api/workspaces/${workspaceId}/jobs/${job.id}/cancel`,"POST");const latest=await api<{job:Job}>(`/api/workspaces/${workspaceId}/ai-videos/${job.id}`);setJob(latest.job);}catch(cause){setError(cause instanceof Error?cause.message:"Cancellation failed.");}}
  return <>{job.billing&&<p className="notice">Token cost: {job.billing.token_amount} · {job.billing.status}</p>}{job.status==="SUCCEEDED"&&<PublishedContent workspaceId={workspaceId} jobId={job.id}/>}<div className="video-detail-grid"><section className="panel"><p className="eyebrow">GENERATION STATUS</p><h2>{job.status.replaceAll("_"," ")}</h2><p>{job.progressMessage||job.progressStage.replaceAll("_"," ")}</p><progress className="job-progress" value={job.progressPercent} max="100"/><p className="muted">{job.progressPercent}% · {job.cancelRequested?"Cancellation requested; provider outcome is being checked.":"Status updates continue after you close this page."}</p>{job.errorMessage&&<p role="alert" className="notice error">{job.errorMessage}</p>}{error&&<p role="alert" className="notice error">{error}</p>}{!["SUCCEEDED","FAILED","CANCELLED"].includes(job.status)&&<button className="button secondary" onClick={()=>void cancel()} disabled={job.cancelRequested}>Request cancellation</button>}</section><section className="panel"><p className="eyebrow">FROZEN REQUEST</p><h2>{job.productName}</h2><dl className="job-facts"><div><dt>Product version</dt><dd>v{job.productVersion}</dd></div><div><dt>Rules version</dt><dd>v{job.ruleVersion}</dd></div><div><dt>Tier</dt><dd>{job.tier}</dd></div><div><dt>Duration</dt><dd>{job.durationSeconds}s</dd></div><div><dt>Ratio</dt><dd>{job.aspectRatio}</dd></div><div><dt>References</dt><dd>{job.referenceAssetVersionIds.length} saved image versions</dd></div></dl><h3>Prompt</h3><p className="video-prompt">{job.prompt}</p><Link href={`/products/${job.productId}`}>View Product →</Link></section></div>{job.status==="SUCCEEDED"&&job.artifacts[0]&&<section className="panel"><p className="eyebrow">READY VIDEO</p><h2>Preview and download</h2>{videoUrl?<><video className="video-preview" controls playsInline src={videoUrl}/><p><a className="button primary" href={videoUrl} download={`${job.id}.mp4`}>Download MP4</a></p></>:<p>Preparing authorized preview…</p>}<p className="muted">Private file · {(job.artifacts[0].byteSize/1024/1024).toFixed(2)} MiB · SHA-256 {job.artifacts[0].sha256.slice(0,12)}…</p></section>}</>;
}
