"use client";
import {useState} from "react";
import {useRouter} from "next/navigation";
import {api} from "./api";
import type {WorkflowConfiguration,TemplateKey} from "@/lib/workflow-templates";

type Estimate={estimatedTokens:string;intendedChildren:number;budgetFits:boolean;quotes:{tokenAmount:string;childCount:number;priceLabel:string}[]};
export function WorkflowForm({workspaceId,products,sources,limit,initial}:{workspaceId:string;products:{id:string;name:string}[];sources:{id:string;filename:string;status:string}[];limit:string;initial?:{id:string;versionId:string;name:string;configuration:WorkflowConfiguration}}){
  const router=useRouter(),c=initial?.configuration;
  const [name,setName]=useState(initial?.name||""),[template,setTemplate]=useState<TemplateKey>(c?.kind||"PRODUCT_AI_VIDEO_REVIEW_V1"),[productId,setProduct]=useState(c?.productId||""),[sourceId,setSource]=useState(c?.kind==="SOURCE_CLIPPER_REVIEW_V1"?c.sourceAssetId:""),[scripts,setScripts]=useState(c?.kind==="PRODUCT_AI_VIDEO_REVIEW_V1"?c.scripts:[""]),[perScript,setPerScript]=useState(c?.kind==="PRODUCT_AI_VIDEO_REVIEW_V1"?c.videosPerScript:1),[duration,setDuration]=useState(c?.kind==="PRODUCT_AI_VIDEO_REVIEW_V1"?c.durationSeconds:5),[ratio,setRatio]=useState(c?.kind==="PRODUCT_AI_VIDEO_REVIEW_V1"?c.aspectRatio:"9:16"),[goal,setGoal]=useState(c?.kind==="SOURCE_CLIPPER_REVIEW_V1"?c.goal:""),[language,setLanguage]=useState(c?.kind==="SOURCE_CLIPPER_REVIEW_V1"?c.language:"auto"),[clips,setClips]=useState(c?.kind==="SOURCE_CLIPPER_REVIEW_V1"?c.targetClipCount:2),[min,setMin]=useState(c?.kind==="SOURCE_CLIPPER_REVIEW_V1"?c.minClipSeconds:10),[max,setMax]=useState(c?.kind==="SOURCE_CLIPPER_REVIEW_V1"?c.maxClipSeconds:30),[captions,setCaptions]=useState(c?.kind==="SOURCE_CLIPPER_REVIEW_V1"?c.captions:true),[budget,setBudget]=useState(c?.maxTokens||"5000"),[review,setReview]=useState(c?.reviewPolicy||"ALL_REVIEWED_AT_LEAST_ONE_APPROVED"),[failure,setFailure]=useState(c?.failurePolicy||"CONTINUE_PARTIAL"),[estimate,setEstimate]=useState<{signature:string;value:Estimate}|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState("");
  const configuration=template==="PRODUCT_AI_VIDEO_REVIEW_V1"?{productId,scripts,videosPerScript:perScript,tier:"QUALITY",durationSeconds:duration,aspectRatio:ratio,referenceAssetVersionIds:c?.kind==="PRODUCT_AI_VIDEO_REVIEW_V1"&&c.productId===productId?c.referenceAssetVersionIds:[],maxTokens:budget,reviewPolicy:review,failurePolicy:failure}:{sourceAssetId:sourceId,productId:productId||undefined,language,goal,targetClipCount:clips,minClipSeconds:min,maxClipSeconds:max,captions,aspectRatio:"9:16",maxTokens:budget,reviewPolicy:review,failurePolicy:"FAIL_FAST"};
  const signature=JSON.stringify({template,configuration}),validEstimate=estimate?.signature===signature;
  async function quote(){setBusy(true);setError("");try{const r=await api<{estimate:Estimate}>(`/api/workspaces/${workspaceId}/workflows/estimate`,"POST",{templateKey:template,configuration});setEstimate({signature,value:r.estimate});}catch(e){setError(e instanceof Error?e.message:"Estimate unavailable.");}finally{setBusy(false);}}
  async function save(){setBusy(true);setError("");try{const r=await api<{definition:{id:string}}>(`/api/workspaces/${workspaceId}/workflows${initial?`/${initial.id}`:""}`,initial?"PATCH":"POST",{name,templateKey:template,configuration,...(initial?{expectedVersionId:initial.versionId}:{})});router.push(`/workflows/${r.definition.id}`);router.refresh();}catch(e){setError(e instanceof Error?e.message:"Workflow could not be saved.");}finally{setBusy(false);}}
  return <form className="workflow-form" onSubmit={e=>{e.preventDefault();void save();}}>
    <div className="form-grid"><label>Workflow name<input required maxLength={160} value={name} onChange={e=>setName(e.target.value)}/></label><label>Template<select value={template} onChange={e=>setTemplate(e.target.value as TemplateKey)}><option value="PRODUCT_AI_VIDEO_REVIEW_V1">Product → AI Video → Review</option><option value="SOURCE_CLIPPER_REVIEW_V1">Source → Clipper → Review</option></select></label></div>
    <label>{template==="PRODUCT_AI_VIDEO_REVIEW_V1"?"Saved Product":"Product (optional)"}<select required={template==="PRODUCT_AI_VIDEO_REVIEW_V1"} value={productId} onChange={e=>setProduct(e.target.value)}><option value="">Select Product</option>{products.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></label>
    {template==="PRODUCT_AI_VIDEO_REVIEW_V1"?<>
      <h3>Customer-authored script / prompt variants</h3><p className="muted">Write your own creative briefs. Each variant produces the number of videos selected below.</p>
      {scripts.map((text,i)=><div key={i} className="workflow-script"><label>Script / prompt {i+1}<textarea required minLength={20} maxLength={2000} rows={3} value={text} onChange={e=>setScripts(scripts.map((s,j)=>i===j?e.target.value:s))}/></label>{scripts.length>1&&<button type="button" className="text-button" onClick={()=>setScripts(scripts.filter((_,j)=>j!==i))}>Remove variant {i+1}</button>}</div>)}
      {scripts.length<5&&<button type="button" className="button secondary" onClick={()=>setScripts([...scripts,""])}>Add script variant</button>}
      <div className="clipper-settings"><label>Videos per script<select value={perScript} onChange={e=>setPerScript(Number(e.target.value))}>{[1,2,3].map(n=><option key={n}>{n}</option>)}</select></label><label>Duration (seconds)<input type="number" min={4} max={30} value={duration} onChange={e=>setDuration(Number(e.target.value))}/></label><label>Aspect ratio<select value={ratio} onChange={e=>setRatio(e.target.value as typeof ratio)}>{["9:16","16:9","1:1"].map(r=><option key={r}>{r}</option>)}</select></label></div><p className="muted">QUALITY · {scripts.length*perScript} intended videos</p>
      <label>Child failure policy<select value={failure} onChange={e=>setFailure(e.target.value as typeof failure)}><option value="CONTINUE_PARTIAL">Continue with successful videos</option><option value="FAIL_FAST">Stop scheduling after a child fails</option></select></label>
    </>:<>
      <label>Uploaded source<select required value={sourceId} onChange={e=>setSource(e.target.value)}><option value="">Select source</option>{sources.filter(s=>["UPLOADED","VERIFIED"].includes(s.status)).map(s=><option key={s.id} value={s.id}>{s.filename}</option>)}</select></label><p className="muted">Upload a source on the Clipper page first.</p>
      <label>Clipping goal<textarea required maxLength={1000} rows={3} value={goal} onChange={e=>setGoal(e.target.value)}/></label><div className="clipper-settings"><label>Language<select value={language} onChange={e=>setLanguage(e.target.value)}>{["auto","en","id","zh","es","fr","de","ja","ko","pt","ar","hi"].map(l=><option key={l}>{l}</option>)}</select></label><label>Target clip count<input type="number" min={1} max={10} value={clips} onChange={e=>setClips(Number(e.target.value))}/></label><label>Minimum clip seconds<input type="number" min={10} max={90} value={min} onChange={e=>setMin(Number(e.target.value))}/></label><label>Maximum clip seconds<input type="number" min={10} max={90} value={max} onChange={e=>setMax(Number(e.target.value))}/></label></div><label className="check-row"><input type="checkbox" checked={captions} onChange={e=>setCaptions(e.target.checked)}/>Captions</label><p className="muted">One Clipper job · Vertical clips · Stops if the child fails</p>
    </>}
    <div className="form-grid"><label>Review policy<select value={review} onChange={e=>setReview(e.target.value as typeof review)}><option value="ALL_REVIEWED_AT_LEAST_ONE_APPROVED">Review every output; approve at least one</option><option value="ALL_APPROVED">Approve every output</option></select></label><label>Maximum token budget<input required inputMode="numeric" pattern="[1-9][0-9]*" value={budget} onChange={e=>setBudget(e.target.value)}/><small>Workspace limit: {limit} tokens. Tokens reserve as each child starts.</small></label></div>
    {error&&<p role="alert" className="notice error">{error}</p>}{validEstimate&&estimate&&<div className="notice workflow-estimate"><strong>Estimated using current pricing: {estimate.value.estimatedTokens} tokens</strong><p>{estimate.value.intendedChildren} paid child jobs. Each child freezes its own quote when admitted.</p>{estimate.value.quotes.map((q,i)=><p key={i}>{q.childCount} × {q.tokenAmount} tokens · {q.priceLabel}</p>)}{!estimate.value.budgetFits&&<p>The estimate exceeds this budget. The run will pause before it admits a child that would exceed the ceiling.</p>}</div>}
    <div className="detail-actions"><button type="button" className="button secondary" disabled={busy} onClick={()=>void quote()}>Estimate cost</button><button className="button primary" disabled={busy||!validEstimate}>{initial?"Save new version":"Save workflow"}</button></div>
  </form>;
}
export function WorkflowDefinitionActions({workspaceId,id,versionId,configuration,canEdit,archived}:{workspaceId:string;id:string;versionId:string;configuration:WorkflowConfiguration;canEdit:boolean;archived:boolean}){
  const router=useRouter(),[busy,setBusy]=useState(false),[error,setError]=useState(""),[estimate,setEstimate]=useState<Estimate|null>(null),[key]=useState(()=>crypto.randomUUID());
  async function perform(action:"estimate"|"start"|"archive"){setBusy(true);setError("");try{if(action==="estimate"){const r=await api<{estimate:Estimate}>(`/api/workspaces/${workspaceId}/workflows/estimate`,"POST",{templateKey:configuration.kind,configuration});setEstimate(r.estimate);}else if(action==="archive"){await api(`/api/workspaces/${workspaceId}/workflows/${id}/archive`,"POST");router.refresh();}else{const r=await api<{run:{id:string}}>(`/api/workspaces/${workspaceId}/workflows/${id}/runs`,"POST",{definitionVersionId:versionId,idempotencyKey:key});router.push(`/workflows/runs/${r.run.id}`);router.refresh();}}catch(e){setError(e instanceof Error?e.message:"Action failed.");}finally{setBusy(false);}}
  if(!canEdit||archived)return <p className="muted">{archived?"Archived definition · Run history remains available.":"Read-only access"}</p>;
  return <><div className="detail-actions"><button className="button secondary" disabled={busy} onClick={()=>void perform("estimate")}>Estimate run cost</button><button className="button primary" disabled={busy||!estimate} onClick={()=>void perform("start")}>Start workflow</button><button className="text-button" disabled={busy} onClick={()=>void perform("archive")}>Archive workflow</button></div>{estimate&&<p className="notice">Estimated using current pricing: {estimate.estimatedTokens} tokens · {estimate.intendedChildren} child jobs · Budget {configuration.maxTokens}</p>}{error&&<p role="alert" className="notice error">{error}</p>}</>;
}
