"use client";
import {useEffect,useState} from "react";
import Link from "next/link";
import {api} from "./api";
import type {WorkflowRunDetail} from "@/lib/workflows";
export function WorkflowRunView({workspaceId,initial,canEdit}:{workspaceId:string;initial:WorkflowRunDetail;canEdit:boolean}){
  const [detail,setDetail]=useState(initial),[busy,setBusy]=useState(false),[error,setError]=useState(""),[budget,setBudget]=useState(initial.run.maxTokens),run=detail.run,done=["SUCCEEDED","FAILED","CANCELLED"].includes(run.status);
  useEffect(()=>{if(done)return;const timer=setInterval(()=>{void api<WorkflowRunDetail>(`/api/workspaces/${workspaceId}/workflows/runs/${run.id}`).then(setDetail).catch(()=>{});},2000);return()=>clearInterval(timer);},[workspaceId,run.id,done]);
  async function action(name:string){setBusy(true);setError("");try{await api(`/api/workspaces/${workspaceId}/workflows/runs/${run.id}/${name}`,"POST",name==="budget"?{maxTokens:budget}:undefined);setDetail(await api<WorkflowRunDetail>(`/api/workspaces/${workspaceId}/workflows/runs/${run.id}`));}catch(e){setError(e instanceof Error?e.message:"Action failed.");}finally{setBusy(false);}}
  const completed=detail.children.filter(c=>["SUCCEEDED","FAILED","CANCELLED"].includes(c.status)).length,reviewed=detail.outputs.filter(o=>o.currentVersionId===o.versionId&&["APPROVED","REJECTED"].includes(o.status)).length;
  return <><section className="panel"><div className="workflow-status"><span className="pill">{run.cancelRequested&&!done?"CANCELLING":run.status.replaceAll("_"," ")}</span><span>{completed} / {run.intendedChildren} child jobs finished · {reviewed} / {detail.outputs.length} outputs reviewed</span></div><p className="muted">This run continues in the background. Human decisions use the existing Review Center.</p>{run.failureMessage&&<p className="notice">{run.failureCode}: {run.failureMessage} {run.status==="WAITING_FOR_FUNDS"&&<Link href="/billing">Buy Tokens →</Link>}</p>}
    <dl className="workflow-budget"><div><dt>Budget</dt><dd>{run.maxTokens}</dd></div><div><dt>Reserved</dt><dd>{detail.budget.reserved}</dd></div><div><dt>Spent / Captured</dt><dd>{detail.budget.captured}</dd></div><div><dt>Released</dt><dd>{detail.budget.released}</dd></div><div><dt>Remaining budget</dt><dd>{detail.budget.remaining}</dd></div></dl>
    {canEdit&&!done&&!run.cancelRequested&&<><div className="detail-actions">{run.status==="PAUSED"?<button className="button primary" disabled={busy} onClick={()=>void action("resume")}>Resume workflow</button>:<button className="button secondary" disabled={busy} onClick={()=>void action("pause")}>Pause workflow</button>}<button className="button secondary" disabled={busy} onClick={()=>void action("cancel")}>Cancel workflow</button></div><div className="workflow-increase"><label>New maximum token budget<input inputMode="numeric" value={budget} onChange={e=>setBudget(e.target.value)}/></label><button className="button secondary" disabled={busy} onClick={()=>void action("budget")}>Increase budget</button></div></>}{error&&<p role="alert" className="notice error">{error}</p>}
  </section><div className="video-detail-grid"><section className="panel"><h2>Step timeline</h2><ol className="workflow-timeline">{detail.steps.map(s=><li key={s.id}><div><strong>{s.step_key}</strong><small>{s.step_type.replaceAll("_"," ")}</small></div><span className="pill">{s.state}</span></li>)}</ol></section><section className="panel"><h2>Child jobs</h2>{detail.children.length?detail.children.map(c=><Link className="video-history-row" key={c.job_id} href={`/${c.type==="AI_VIDEO"?"ai-videos":"clipper"}/${c.job_id}`}><div><strong>{c.child_key}</strong><small>{c.token_amount} tokens · {c.billing_status}</small></div><span className="pill">{c.status}</span></Link>):<p className="muted">No children admitted yet.</p>}<p className="muted">Parent workflow charge: 0 tokens</p></section></div>
  <section className="panel"><h2>Content and review</h2>{detail.outputs.length?<div className="workflow-outputs">{detail.outputs.map(o=><Link className="video-history-row" key={o.versionId} href={`/content/${o.contentId}`}><div><strong>{o.title}</strong><small>Exact version {o.versionId.slice(0,8)} · {o.currentVersionId!==o.versionId?"Version changed":o.status.replaceAll("_"," ")}</small></div><span>{o.status==="PENDING_REVIEW"?"Review output →":"View content →"}</span></Link>)}</div>:<p className="muted">Published child results appear here.</p>}</section>
  {done&&run.result&&<section className="panel"><h2>Final results</h2><p>{Array.isArray(run.result.approvedContentIds)?run.result.approvedContentIds.length:0} approved · {Array.isArray(run.result.rejectedContentIds)?run.result.rejectedContentIds.length:0} rejected</p><Link href="/content">Open Content Library →</Link></section>}
  <section className="panel"><h2>Run history</h2><ul className="review-timeline">{detail.events.map((e,i)=><li key={i}>{e.event_type.replaceAll("_"," ")} · {new Date(e.created_at).toLocaleString("en-US",{timeZone:"Asia/Shanghai"})}</li>)}</ul></section></>;
}
