import {test} from "node:test";
import assert from "node:assert/strict";
import {integer,calculateTokens,canonicalHash} from "../../src/lib/billing-core";
import {fakeWebhookSignature,paymentProvider} from "../../src/lib/payment-providers";
import {can} from "../../src/lib/permissions";
import type {AiVideoInput,ClipperInput} from "../../src/lib/job-core";
test("integer token pricing never uses floating point and hashes normalize key order",()=>{assert.equal(integer("9007199254740991"),BigInt("9007199254740991"));for(const s of ["1.5","-1","01","1e3","9007199254740992"])assert.throws(()=>integer(s));assert.equal(calculateTokens("AI_VIDEO",{kind:"AI_VIDEO",tier:"QUALITY",durationSeconds:5,quantity:1} as AiVideoInput,{tier:"QUALITY",base:"0",perSecond:"140"}),BigInt(700));assert.equal(calculateTokens("CLIPPER",{kind:"CLIPPER",targetClipCount:2,captions:true} as ClipperInput,{base:"400",perClip:"100",captions:"100"}),BigInt(700));assert.equal(canonicalHash({a:1,b:2}),canonicalHash({b:2,a:1}));});
test("billing roles and local fake provider gates",()=>{assert.equal(can("ADMIN","billing:manage"),true);assert.equal(can("EDITOR","billing:manage"),false);assert.equal(can("VIEWER","future:spend"),false);const saved={...process.env};try{process.env.APP_ENV="production";process.env.ENABLE_FAKE_PAYMENT_PROVIDER="1";assert.throws(()=>paymentProvider("fake"));process.env.APP_ENV="local";process.env.APP_BASE_URL="http://127.0.0.1:3200";process.env.ENABLE_TEST_BILLING="1";process.env.FAKE_PAYMENT_WEBHOOK_SECRET="unit-test-only-secret-at-least-32-bytes";const p=paymentProvider("fake"),raw=Buffer.from('{"status":"PAID"}');p.verifyWebhook(raw,new Headers({"x-fake-signature":fakeWebhookSignature(raw)}));assert.throws(()=>p.verifyWebhook(raw,new Headers({"x-fake-signature":"invalid"})));}finally{process.env=saved;}});
test("Xendit sandbox adapter uses Sessions and authenticates/normalizes callbacks without delivery timestamps",async()=>{const saved={...process.env},original=globalThis.fetch,calls:{url:string;method:string}[]=[];try{process.env.XENDIT_MODE="test";process.env.XENDIT_SECRET_KEY="xnd_development_unit_fixture_only";process.env.XENDIT_CALLBACK_TOKEN="unit-callback-token";process.env.XENDIT_BUSINESS_ID="unit-business";process.env.XENDIT_RETURN_BASE_URL="https://sandbox.example.test";const data={payment_session_id:"ps-unit-session",reference_id:"topup_unit",session_type:"PAY",status:"COMPLETED",currency:"IDR",amount:10000,payment_id:"py-unit",payment_request_id:"pr-unit",payment_link_url:"https://dev.xen.to/unit",expires_at:"2026-10-01T00:00:00Z"};globalThis.fetch=async (url,init)=>{calls.push({url:String(url),method:init?.method||"GET"});assert.ok(String((init?.headers as Record<string,string>).Authorization).startsWith("Basic "));if(init?.body){const body=JSON.parse(String(init.body));assert.equal(body.amount,10000);assert.equal(body.currency,"IDR");assert.equal(body.session_type,"PAY");assert.equal(body.mode,"PAYMENT_LINK");}return Response.json(data);};const p=paymentProvider("xendit");await p.createPayment({id:"unit",workspaceId:"11111111-1111-4111-8111-111111111111",referenceId:"topup_unit",fiatMinor:"10000",currency:"IDR",email:"unit@example.test"});assert.equal((await p.getPayment(data.payment_session_id)).status,"PAID");assert.deepEqual(calls,[{url:"https://api.xendit.co/sessions",method:"POST"},{url:"https://api.xendit.co/sessions/ps-unit-session",method:"GET"}]);const payload={event:"payment_session.completed",business_id:"unit-business",created:"first delivery",data};const raw=Buffer.from(JSON.stringify(payload));p.verifyWebhook(raw,new Headers({"x-callback-token":"unit-callback-token"}));assert.throws(()=>p.verifyWebhook(raw,new Headers({"x-callback-token":"wrong"})));assert.deepEqual(p.parseWebhook(raw),p.parseWebhook(Buffer.from(JSON.stringify({...payload,created:"retry delivery"}))));assert.throws(()=>p.parseWebhook(Buffer.from(JSON.stringify({...payload,business_id:"other-account"}))));const refund=p.parseWebhook(Buffer.from(JSON.stringify({event:"refund.succeeded",business_id:"unit-business",data:{id:"rfd-unit",payment_request_id:"pr-unit",currency:"IDR",amount:10000,status:"SUCCEEDED"}})));assert.equal(refund.kind,"REFUND");assert.equal(refund.providerRequestId,"pr-unit");process.env.XENDIT_SECRET_KEY="xnd_production_rejected_fixture";assert.throws(()=>paymentProvider("xendit"));}finally{globalThis.fetch=original;process.env=saved;}});
