import { test } from 'node:test';
import assert from 'node:assert/strict';
import { randomUUID } from 'node:crypto';
import { validateCampaign, renderMessage, selectRecipients, settlementAmounts, aggregateState, type Creator } from '../../src/lib/outreach-core';
import { can } from '../../src/lib/permissions';
const raw = () => ({ channelId: randomUUID(), name: 'QA campaign', productName: 'QA product', messageTemplate: 'Hi {{creator_display_name}} — {{product_name}} / {{campaign_name}}', targetCount: 2, cooldownDays: 30, rankingMetric: 'FOLLOWERS', rankingDirection: 'DESC', filters: {} });
const creator = (ordinal: number): Creator => ({ id: randomUUID(), creator_key: `qa_${ordinal}`, display_name: `QA ${ordinal}`, username: `qa_${ordinal}`, category_ids: ['beauty'], followers: 1000 * ordinal, gmv: String(ordinal * 100), gmv_currency: 'USD', units_sold: ordinal * 2, video_views: ordinal * 10, live_viewers: ordinal, engagement: ordinal, ordinal });
test('Outreach rejects internal sender paths, credentials and arbitrary provider input before admission', () => { for (const field of ['nativeSenderId', 'provider', 'databaseUrl', 'apiUrl', 'session', 'credentials'])
    assert.throws(() => validateCampaign({ ...raw(), [field]: 'private' })); });
test('Outreach target, cooldown and numeric filter bounds reject malformed values', () => { for (const targetCount of [0, 501, 1.5, NaN])
    assert.throws(() => validateCampaign({ ...raw(), targetCount })); for (const cooldownDays of [-1, 3651, 0.5])
    assert.throws(() => validateCampaign({ ...raw(), cooldownDays })); for (const value of [NaN, Infinity, -1, '12'])
    assert.throws(() => validateCampaign({ ...raw(), filters: { minGmv: value } })); });
test('Outreach rejects reversed ranges, unsupported categories and unsupported ranking', () => { assert.throws(() => validateCampaign({ ...raw(), filters: { minFollowers: 200, maxFollowers: 100 } })); assert.throws(() => validateCampaign({ ...raw(), filters: { categoryIds: ['../private'] } })); assert.throws(() => validateCampaign({ ...raw(), rankingMetric: 'PAID_AI' })); });
test('Outreach template substitution is literal, never expression or replacement-string execution', () => { assert.equal(renderMessage('{{creator_display_name}}', { creator_display_name: '$& <script>QA</script>', product_name: '', campaign_name: '' }), '$& <script>QA</script>'); for (const messageTemplate of ['{{constructor}}', '{{process.env.KEY}}', '{{creator_display_name', '{{bad}}'])
    assert.throws(() => validateCampaign({ ...raw(), messageTemplate })); });
test('Outreach verifies required variable values and expanded per-recipient message length', () => { assert.throws(() => validateCampaign({ ...raw(), productName: '' })); assert.throws(() => renderMessage('{{creator_display_name}}'.repeat(20), { creator_display_name: 'x'.repeat(120), product_name: '', campaign_name: '' })); });
test('Outreach selection follows supported filters and stable ranking only', () => { const c = validateCampaign(raw()), r = selectRecipients(c, [creator(1), creator(3), creator(2)], new Map()); assert.deepEqual(r.selected.map(c => c.creatorKey), ['qa_3', 'qa_2']); const keyword = validateCampaign({ ...raw(), filters: { keyword: 'qa_1' } }); assert.equal(selectRecipients(keyword, [creator(1), creator(2)], new Map()).selected.length, 1); });
test('Outreach selection never mixes GMV currencies or estimates missing metrics', () => { const c = validateCampaign({ ...raw(), rankingMetric: 'GMV', filters: { minGmv: 1 } }), a = creator(1), b = { ...creator(2), gmv_currency: 'IDR' }, d = { ...creator(3), gmv: null }; assert.deepEqual(selectRecipients(c, [a, b, d], new Map()).selected.map(r => r.creatorKey), ['qa_1']); });
test('Outreach cooldown, active reservation, exclusion and unknown always constrain selection', () => { const c = validateCampaign({ ...raw(), targetCount: 5 }), creators = [1, 2, 3, 4, 5].map(creator), contacts = new Map([['qa_1', { do_not_contact: true, unknown_delivery_id: null, last_contacted_at: null, reserved: false }], ['qa_2', { do_not_contact: false, unknown_delivery_id: randomUUID(), last_contacted_at: null, reserved: false }], ['qa_3', { do_not_contact: false, unknown_delivery_id: null, last_contacted_at: null, reserved: true }], ['qa_4', { do_not_contact: false, unknown_delivery_id: null, last_contacted_at: new Date(), reserved: false }]]); assert.deepEqual(selectRecipients(c, creators, contacts).selected.map(r => r.creatorKey), ['qa_5']); });
test('Outreach partial settlement captures confirmed sends and releases other definite outcomes', () => { assert.deepEqual(settlementAmounts(40n, 10n, ['SENT', 'RESTRICTED', 'FAILED', 'CANCELLED']), { captured: 10n, released: 30n }); assert.throws(() => settlementAmounts(5n, 10n, ['SENT'])); });
test('Outreach uncertain or active outcomes cannot settle or be inferred as successful', () => { for (const state of ['PENDING', 'DISPATCHING', 'RETRYABLE', 'DELIVERY_UNKNOWN'] as const)
    assert.equal(settlementAmounts(10n, 10n, [state]), null); });
test('Outreach controls preserve in-flight and unknown boundaries', () => { assert.equal(aggregateState(['DISPATCHING', 'PENDING'], true, false), 'PAUSE_REQUESTED'); assert.equal(aggregateState(['DISPATCHING', 'CANCELLED'], false, true), 'CANCEL_REQUESTED'); assert.equal(aggregateState(['DELIVERY_UNKNOWN', 'CANCELLED'], false, true), 'DELIVERY_UNKNOWN'); assert.equal(aggregateState(['SENT', 'CANCELLED'], false, true), 'CANCELLED'); });
test('Outreach permissions remain separate from wallet management and conservative by workspace role', () => { assert.equal(can('VIEWER', 'outreach:view'), true); assert.equal(can('VIEWER', 'outreach:send'), false); assert.equal(can('EDITOR', 'outreach:create'), true); assert.equal(can('EDITOR', 'outreach:send'), false); assert.equal(can('EDITOR', 'outreach:channel_manage'), false); assert.equal(can('ADMIN', 'outreach:send'), true); assert.equal(can('OWNER', 'outreach:manage'), true); });
